### ISSUE TITLE
Dotnet run for mvc, web, webapi failed on OpenSuse 42.3 with sdk 1.1.11

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#10013]
## Steps to reproduce
Install sdk 1.1.11-msrc-fnl-005294 on OpenSuse 42.3
dotnet new mvc or web or webapi
dotnet run to observe

## Expected  behavior
Dotnet run works fine

## Actual behavior
Dotnet run failed with below error text

nicole@opensuse-1:~/mymvc> dotnet run
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.AggregateException: One or more errors occurred. (Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)<---

Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at mymvc.Program.Main(String[] args) in /home/nicole/mymvc/Program.cs:line 21
![image](https://user-images.githubusercontent.com/1578239/45616753-f43e6c00-baa2-11e8-9ad6-e63b2eb63b8e.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.1.11)

Product Information:
 Version:            1.1.11
 Commit SHA-1 hash:  d2610b5786

Runtime Environment:
 OS Name:     opensuse
 OS Version:  42.3
 OS Platform: Linux
 RID:         opensuse.42.3-x64
 Base Path:   /home/nicole/mytest/sdk/1.1.11

**Comment by muratg** [comment]
In 1.1.x, [Kestrel package](https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel/1.1.3) should be bringing libuv dependency. 

Can you share your deps file to see if the dependencies are right?

**Comment by JunTaoLuo** [comment]
We have discussed this for the previous 1.1 release and @natemcmaster's proposal was forgotten. The libuv dependency in 1.x is brought in by Microsoft.NETCore.App. We should update the dependency of that package from 1.9.2 to 1.10.0 which contains a generic libuv.dll that will work on openSUSE.

**Comment by leecow** [comment]
@muratg / @JunTaoLuo  - the libuv version available on the default openSUSE repositories (libuv1-1.6.1-7.1.x86_64) does not work so I'll need to know where 1.10 comes from in order to document.

**Comment by JunTaoLuo** [comment]
You can find libuv 1.10.0 on Nuget: https://www.nuget.org/packages/Libuv/1.10.0, would that work for you?

**Comment by peterhuene** [comment]
I've confirmed that `<PackageReference Include="libuv" Version="1.10.0" />` solves the issue due to the runtime in the package being `linux-x64` and not distro-specific.
