### ISSUE TITLE
dotnet sln list command doesn't list files of a read-only solution file

### ISSUE THREAD

**Issue by Eshva** [dotnet/cli#10166]
The ```dotnet sln list``` command cannot list project from a read-only .sln file. The list command shouldn't modify the .sln file so there is no reason to require write access to this file on open.

## Steps to reproduce
1. Create a new or take any .sln file.
2. Set read-only attribute on the .sln file.
3. Try execute command ```dotnet sln <solution.sln> list on the .sln file.

## Expected  behavior
Project files in the solution listed.

## Actual behavior
Due the solution file is read-only the tool throws an exception.
```
System.UnauthorizedAccessException: Access to the path 'name.sln' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.DotNet.Cli.Sln.Internal.SlnFile.Read(String file)
   at Microsoft.DotNet.Tools.Common.SlnFileFactory.FromFile(String solutionPath)
   at Microsoft.DotNet.Tools.Common.SlnFileFactory.CreateFromFileOrDirectory(String fileOrDirectory)
   at Microsoft.DotNet.Tools.Sln.List.ListProjectsInSolutionCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Sln.SlnCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-1-003177 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Jalalx** [comment]
Here is why:
https://github.com/dotnet/cli/blob/a936ffd2056383dfcd2dd028cc1676b5c62c7654/src/Microsoft.DotNet.Cli.Sln.Internal/SlnFile.cs#L114-L117

Do you think adding a `FileAccess.Read` to the `FileStream` constructor is enough? What if file is not `readonly` and is opened by another application like Visual Studio at the same time? I think `FileAccess.Read` should be applied only when file has a `readonly` attribute.

@peterhuene What do you think?

**Comment by peterhuene** [comment]
Hi @Jalalx.

I think your assessment is correct.  Passing `FileAccess.Read` should be sufficient to resolve this issue; it will still default to sharing read-access with other processes, which is the desired behavior.
