### ISSUE TITLE
Improve readability of dotnet test

### ISSUE THREAD

**Issue by terrajobst** [dotnet/cli#10207]
The command line output of `dotnet test` is extremely noisy which makes it hard to parse. Instead of this:

```
$ dotnet test
Build started, please wait...
Build completed.

Test run for P:\minsk\Minsk.Tests\bin\Debug\netcoreapp2.1\Minsk.Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.6522298]     Minsk.Tests.CodeAnalysis.Syntax.ParserTests.SyntaxFacts_Kind_AgreesWith_GetText [FAIL]
Failed   Minsk.Tests.CodeAnalysis.Syntax.ParserTests.SyntaxFacts_Kind_AgreesWith_GetText
Error Message:
 Assert.Equal() Failure
          ↓ (pos 0)
Expected: immo
Actual:   brad
          ↑ (pos 0)
Stack Trace:
   at Minsk.Tests.CodeAnalysis.Syntax.ParserTests.SyntaxFacts_Kind_AgreesWith_GetText() in P:\minsk\Minsk.Tests\CodeAnalysis\Syntax\ParserTests.cs:line 32

Total tests: 65. Passed: 64. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.2981 Seconds
```

I wish the output would be like:

```
Minsk.Tests\Minsk.Tests.csproj (.NETCoreApp,Version=v2.1)

ParserTests.SyntaxFacts_Kind_AgreesWith_GetText
    Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: immo
        Actual:   brad
                  ↑ (pos 0)
    at Minsk.Tests.CodeAnalysis.Syntax.ParserTests.SyntaxFacts_Kind_AgreesWith_GetText() in P:\minsk\Minsk.Tests\CodeAnalysis\Syntax\ParserTests.cs:line 32

Total tests:  65
     Passed:  64
     Failed:   1
    Skipped:   0
       Time: 1.3 secs
```

Requests like  #10165 are related and are an indicator that folks working on the command line want legible output.

> Be readable. Be brief. Be gone.
>       -- My opinion on good output.

**Comment by livarcocc** [comment]
@KathleenDollard @kendrahavens

**Comment by livarcocc** [comment]
Should probably move this issue to microsoft/vstest.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1836

**Comment by HeroMaxPower** [comment]
ï would vouch for this, especially when it comes to cloud testing it's difficult to parse as you don't have a gui (such as test explorer) to see the results in a more visually appealing way.
