### ISSUE TITLE
`dotnet run` throws Win32Exception on 3.0 arm 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#10295]
## Steps to reproduce
1. From a linux arm environment running the SDK within a Docker container (e.g. microsoft/dotnet-nightly:3.0-sdk-stretch-arm32v7).
2. mkdir app
3. cd app
4. dotnet new console
5. dotnet run

## Expected  behavior
The app should run without error.

## Actual behavior

```
System.ComponentModel.Win32Exception (8): Exec format error
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009734
 Commit:    841b50c4df

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-arm
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview-009734/

Host (useful for support):
  Version: 3.0.0-preview-27106-02
  Commit:  410cba8501

.NET Core SDKs installed:
  3.0.100-preview-009734 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 3.0.0-alpha1-10663 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10663 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27106-02 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/10291#issuecomment-436784162.
