### ISSUE TITLE
NullRef when Publishing a moved app with P2P Dependencies

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1033]
This is currently reproducible inside the repo.

Steps:
```
cd tests/TestProjects/TestLibraryWithRunner
dotnet restore
dotnet publish     # will pass
mkdir test
mv * ./test           # Ignore failure
cd test
dotnet publish    # Null Ref
```

The exception looks like this:
```
Publishing test for .NETFramework,Version=v4.5.1/win7-x64
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.ProjectModel.Compilation.LibraryExporter.ExportProject(ProjectDescription project) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.ProjectModel\Compilation\LibraryExporter.cs:line 164
   at Microsoft.DotNet.ProjectModel.Compilation.LibraryExporter.GetExport(LibraryDescription library) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.ProjectModel\Compilation\LibraryExporter.cs:line 120
   at Microsoft.DotNet.ProjectModel.Compilation.LibraryExporter.<ExportLibraries>d__9.MoveNext() in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.ProjectModel\Compilation\LibraryExporter.cs:line 82
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Build.ProjectDependenciesFacade.GetProjectDependencies(ProjectContext projectContext, String configuration) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\ProjectDependenciesFacade.cs:line 44
   at Microsoft.DotNet.Tools.Build.ProjectDependenciesFacade..ctor(ProjectContext rootProject, String configValue) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\ProjectDependenciesFacade.cs:line 21
   at Microsoft.DotNet.Tools.Build.CompileContext..ctor(ProjectContext rootProject, BuilderCommandApp args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 48
   at Microsoft.DotNet.Tools.Build.Program.<>c__DisplayClass1_0.<OnExecute>b__0(ProjectContext context) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\Program.cs:line 38
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Microsoft.DotNet.Tools.Build.Program.OnExecute(List`1 contexts, CompilerCommandApp args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\Program.cs:line 38
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.<>c__DisplayClass70_0.<Execute>b__0() in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Compiler\CompilerCommandApp.cs:line 122
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args) in C:\Users\brthor\.nuget\packages\Microsoft.Extensions.CommandLineUtils.Sources\1.0.0-rc2-16414\shared\CommandLineApplication.cs:line 263
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.Execute(OnExecute execute, String[] args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Compiler\CompilerCommandApp.cs:line 127
Publishing test for DNXCore,Version=v5.0/win7-x64
   at Microsoft.DotNet.Tools.Build.Program.Main(String[] args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\Program.cs:line 23
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.ProjectModel.Compilation.LibraryExporter.ExportProject(ProjectDescription project) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.ProjectModel\Compilation\LibraryExporter.cs:line 164
   at Microsoft.DotNet.ProjectModel.Compilation.LibraryExporter.GetExport(LibraryDescription library) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.ProjectModel\Compilation\LibraryExporter.cs:line 120
   at Microsoft.DotNet.ProjectModel.Compilation.LibraryExporter.<ExportLibraries>d__9.MoveNext() in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.ProjectModel\Compilation\LibraryExporter.cs:line 82
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Build.ProjectDependenciesFacade.GetProjectDependencies(ProjectContext projectContext, String configuration) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\ProjectDependenciesFacade.cs:line 44
   at Microsoft.DotNet.Tools.Build.ProjectDependenciesFacade..ctor(ProjectContext rootProject, String configValue) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\ProjectDependenciesFacade.cs:line 21
   at Microsoft.DotNet.Tools.Build.CompileContext..ctor(ProjectContext rootProject, BuilderCommandApp args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 48
   at Microsoft.DotNet.Tools.Build.Program.<>c__DisplayClass1_0.<OnExecute>b__0(ProjectContext context) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\Program.cs:line 38
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Microsoft.DotNet.Tools.Build.Program.OnExecute(List`1 contexts, CompilerCommandApp args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\Program.cs:line 38
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.<>c__DisplayClass70_0.<Execute>b__0() in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Compiler\CompilerCommandApp.cs:line 122
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args) in C:\Users\brthor\.nuget\packages\Microsoft.Extensions.CommandLineUtils.Sources\1.0.0-rc2-16414\shared\CommandLineApplication.cs:line 263
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.Execute(OnExecute execute, String[] args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Compiler\CompilerCommandApp.cs:line 127
Published 0/2 projects successfully
   at Microsoft.DotNet.Tools.Build.Program.Main(String[] args) in C:\Users\brthor\code\cli_args\src\Microsoft.DotNet.Tools.Builder\Program.cs:line 23
```

I understand this is probably not a supported scenario but we should probably throw a more helpful error message (e.g. Can't find P2P dependency?)

cc @anurse @davidfowl @piotrpMSFT

**Comment by anurse** [comment]
Yep, makes sense we should clean up this error message.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
