### ISSUE TITLE
dotnet new console failing with custom coreclr

### ISSUE THREAD

**Issue by adiaaida** [dotnet/cli#10399]
## Steps to reproduce

1. Use dotnet-install.ps1 to pull down the latest concurrent dotnet
2. Pull down dotnet/coreclr
3. build.cmd release x64 skiptests
4. Copy coreclr.dll, clrjit.dll, mscordaccore.dll, mscordbi.dll, sos.dll, sos.NETCore.dll, clretwrc.dll, System.Private.CoreLib.dll, mscorrc.debug.dll and mscorrc.dll into the shared framework of the dotnet install you got in step 1.
5. run dotnet.exe new console

## Expected  behavior

dotnet creates a hello world cs file and csproj

## Actual behavior
Dotnet fails with the following output:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.DotNet.Cli.Utils.Muxer.get_SharedFxVersion()
   at Microsoft.DotNet.Tools.New.NewCommandShim.CreateHost()
   at Microsoft.DotNet.Tools.New.NewCommandShim.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
I am seeing this with both of these dotnets (and yes, we are seeing the error when running dotnet --info too):
`dotnet --info` output:

```
.NET Command Line Tools (2.2.0-preview1-007558)

Product Information:
 Version:            2.2.0-preview1-007558
 Commit SHA-1 hash:  1b8c5b498b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18283
 OS Platform: Windows
System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.DotNet.Cli.Utils.FrameworkDependencyFile.CreateDependencyContext()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.Cli.Utils.FrameworkDependencyFile.IsRuntimeSupported(String runtimeIdentifier)
   at Microsoft.DotNet.Cli.Program.GetDisplayRid(DotnetVersionFile versionFile)
   at Microsoft.DotNet.Cli.Program.PrintInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Host (useful for support):
  Version: 2.1.0-preview3-26416-01
  Commit:  967b9806b2

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007341 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007354 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009088 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009324 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.2.0-preview1-007558 [C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\.dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26416-01 [C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5-servicing-26911-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
```
D:\output\CLRx64WINmas\PGO\cli\x64\dotnet.exe --info
00:36:45 .NET Core SDK (reflecting any global.json):
00:36:45  Version:   3.0.100-preview-009778
00:36:45  Commit:    20b40ce7b3
00:36:45 
00:36:45 Runtime Environment:
00:36:45  OS Name:     Windows
00:36:45  OS Version:  6.3.9600
00:36:45  OS Platform: Windows
00:36:47 System.ArgumentNullException: Path cannot be null.
00:36:47 Parameter name: path
00:36:47    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
00:36:47    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
00:36:47    at System.IO.File.OpenRead(String path)
00:36:47    at Microsoft.DotNet.Cli.Utils.FrameworkDependencyFile.CreateDependencyContext()
00:36:47    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
00:36:47    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
00:36:47    at System.Lazy`1.CreateValue()
00:36:47    at Microsoft.DotNet.Cli.Utils.FrameworkDependencyFile.IsRuntimeSupported(String runtimeIdentifier)
00:36:47    at Microsoft.DotNet.Cli.Program.GetDisplayRid(DotnetVersionFile versionFile)
00:36:47    at Microsoft.DotNet.Cli.Program.PrintInfo()
00:36:47    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
00:36:47    at Microsoft.DotNet.Cli.Program.Main(String[] args)
00:36:47 
00:36:47 Host (useful for support):
00:36:47   Version: 3.0.0-preview-27125-01
00:36:47   Commit:  7c25ee34e4
00:36:47 
00:36:47 .NET Core SDKs installed:
00:36:47   3.0.100-preview-009778 [D:\output\CLRx64WINmas\PGO\cli\x64\sdk]
00:36:47 
00:36:47 .NET Core runtimes installed:
00:36:47   Microsoft.AspNetCore.App 3.0.0-alpha1-10772 [D:\output\CLRx64WINmas\PGO\cli\x64\shared\Microsoft.AspNetCore.App]
00:36:47   Microsoft.NETCore.App 3.0.0-preview-27117-01 [D:\output\CLRx64WINmas\PGO\cli\x64\shared\Microsoft.NETCore.App]
00:36:47   Microsoft.NETCore.App 3.0.0-preview-27125-01 [D:\output\CLRx64WINmas\PGO\cli\x64\shared\Microsoft.NETCore.App]
00:36:47   Microsoft.WindowsDesktop.App 3.0.0-alpha-27119-7 [D:\output\CLRx64WINmas\PGO\cli\x64\shared\Microsoft.WindowsDesktop.App]
00:36:47 
00:36:47 To install additional .NET Core runtimes or SDKs:
00:36:47   https://aka.ms/dotnet-download
```

This failing both for one of our perf scenarios and for our PGO and IBC data collection jobs.

**Comment by livarcocc** [comment]
I am not sure why this is a CLI bug. We are just invoking corefx APIs. Seems to me like there is a chance that there are API changes between the version of coreclr that the CLI uses and the custom one you are inserting.

If you believe this is a CLI issue, please let us know why. Otherwise, maybe file an issue on coreclr or double check the CLI expected version and the version you are replacing.

**Comment by adiaaida** [comment]
I wasn't sure where to open it, but since it was happening during CLI code, or at least in what I thought was CLI code, I opened it here. As far as I can tell, we seem to be getting a null value for the FX_DEPS_FILE property. This may be an issue with corefx/coreclr, but I'm not sure.

Looking at some of the changes that came in around when this started to fail, I'm wondering if @jkotas's changes to AppDomain might be the root cause.

**Comment by jkotas** [comment]
The CLI code is doing private reflection against CoreLib here: 

https://github.com/dotnet/cli/blob/95c6eff6daa1a69f29c42b2d405400ad44bdec91/src/Microsoft.DotNet.Cli.Utils/Muxer.cs#L48

Could you please fix it to use `AppContext.GetData` instead?

Note that this was not accessing the actual public AppDomain type. It has been internal AppDomain type that is left-over from desktop and that is broken in number of different ways. We have been working on cleaning it up.

**Comment by jkotas** [comment]
Here is second place that does that: https://github.com/dotnet/cli/blob/95c6eff6daa1a69f29c42b2d405400ad44bdec91/TestAssets/TestPackages/dotnet-portable/Program.cs#L24

**Comment by adiaaida** [comment]
@livarcocc out of curiosity, about how long does it generally take for these kinds of changes to make it from being checked in to seeing it in the dotnet we pull down using -version Latest or -version Concurrent?

**Comment by livarcocc** [comment]
Right now, it will take a couple of days. We are kind of locked down due to preview1 shipping. But even usually, we push them as we need them.

We are working on making this automated to happen daily, but some of the infra changes are not there yet. We are targeting mid December to have the infra in place.

**Comment by adiaaida** [comment]
Thanks! I just wanted to check

**Comment by adiaaida** [comment]
I'm sorry to ping on this again, but without this change, we can't get new PGO data for preview1, which means that our data will be seriously behind for shipping (the PGO jobs have been failing for a week now because of this). Is there any way we could push this?

**Comment by livarcocc** [comment]
Build 3.0.100-preview-009815 should have the fix you need. However, it won't be in latest yet because our RHEL7 builds are failing due to some external dependencies that the RHEL7 machine has being on an outage.
