### ISSUE TITLE
Unhandled exception returned if run web application with sdk 3.0.100-preview-009784

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#10394]
## Steps to reproduce
1. Install sdk 3.0.100-preview-009784
2. dotnet new mvc /web /webapi
3. dotnet run

## Expected  behavior
Dotnet run for mvc, web and webap works well

## Actual behavior
It returns Unhandled Exception: System.ArgumentException: Value cannot be null or an empty string.
_nicole@ubu16-27:~/mywebapi$ dotnet run
Unhandled Exception: System.ArgumentException: Value cannot be null or an empty string.
Parameter name: userSecretId
at Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute..ctor(String userSecretId)
at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder1& derivedAttributes)
at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
at Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration, Assembly assembly, Boolean optional, Boolean reloadOnChange)
at Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration, Assembly assembly, Boolean optional)
at Microsoft.AspNetCore.WebHost.<>c__DisplayClass8_0.b__0(WebHostBuilderContext hostingContext, IConfigurationBuilder config)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at mywebapi.Program.Main(String[] args) in /home/nicole/mywebapi/Program.cs:line 17_

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
Version: 3.0.100-preview-009784
Commit: d86a1816c4
Runtime Environment:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /usr/share/dotnet/sdk/3.0.100-preview-009784/
Host (useful for support):
Version: 3.0.0-preview-27122-01
Commit: 00c5c8bc40
.NET Core SDKs installed:
3.0.100-preview-009784 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.0.0-preview-18572-0018 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.0-preview-27122-01 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
@natemcmaster

**Comment by natemcmaster** [comment]
Yes, we ran into this too. This should be fixed with https://github.com/aspnet/AspNetCore/pull/4240. Hopefully we'll have a build by tomorrow with this fix.

**Comment by livarcocc** [comment]
@natemcmaster Please, link the asp.net insertion PR with the fix to this issue.

**Comment by YunWeiaa** [comment]
Note: It will not be getting fixed for .Net Core 3.0 Preview 1. We will try to get that in by Preview 2 time frame.
