### ISSUE TITLE
LD_LIBRARY_PATH icu issue

### ISSUE THREAD

**Issue by spushpendra2000** [dotnet/cli#10509]
## Steps to reproduce
I am using dotnet core 2.1 on centos. and trying to load the dll.

When running , i am getting this error
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted (core dumped)

I can see the suggestion as per the link
https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

But I cannot change the icu path and when i tried creating the local folder 'netcoredeps' where my dll is residing it never work and i keep getting the same error.
Only after the setting the LD_LIBRARY_PATH, it is working.. Please suggest who to resolve this
## Environment data
`dotnet --info` output:

**Comment by spushpendra2000** [comment]
Even if i am keeping all libicu files in the same folder where my dll is residing, i am still getting the same error

**Comment by livarcocc** [comment]
This issue was moved to dotnet/corefx#34248
