### ISSUE TITLE
dotnet build throws Argument Null Exception for projects referencing projects with localized resx files

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#1101]
ProjectA contains Test.fr.resx
ProjectB references ProjectA

dotnet build produces the following stack trace:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Tools.Compiler.CompilerUtil.<>c__DisplayClass5_0.<GetCultureResources>b__6(<>f__AnonymousType4`2 <>h__TransparentIdentifier1) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Compiler\CompilerUtil.cs:line 90
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Compiler.CompilerUtil.GetCultureResources(Project project, String outputPath) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Compiler\CompilerUtil.cs:line 85
   at Microsoft.DotNet.Tools.Build.CompileContext.AddCultureResources(ProjectContext project, String outputPath, CompilerIO compilerIO) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 487
   at Microsoft.DotNet.Tools.Build.CompileContext.GetCompileIO(ProjectContext project, String buildConfiguration, String outputPath, String intermediaryOutputPath, ProjectDependenciesFacade dependencies) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 433
   at Microsoft.DotNet.Tools.Build.CompileContext.NeedsRebuilding(ProjectContext project, ProjectDependenciesFacade dependencies, String buildOutputPath, String intermediateOutputPath) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 100
   at Microsoft.DotNet.Tools.Build.CompileContext.DependencyNeedsRebuilding(ProjectContext project, ProjectDependenciesFacade dependencies) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 90
   at Microsoft.DotNet.Tools.Build.CompileContext.Compile(Boolean incremental) in D:\work\katana\cli\src\Microsoft.DotNet.Tools.Builder\CompileContext.cs:line 62
```

I am using a locally built copy of dotnet-cli that is at `rel/1.0.0`

**Comment by pranavkm** [comment]
Fixed in https://github.com/dotnet/cli/commit/656b59c5089609c2665be5b2e9a8c69727b8f525
