### ISSUE TITLE
dotnet-restore -? throws an exception

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1110]
C:\Microsoft\visualfsharp>packages\dotnet\bin\dotnet.exe restore /?
 
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal character
s in path.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
 
C:\Microsoft\visualfsharp>packages\dotnet\bin\dotnet.exe restore --help
 
Unhandled Exception: Microsoft.Dnx.Runtime.Common.CommandLine.CommandParsingException: Unrecognized option '--help'
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, Str
ing[] args, Int32 index, String argTypeName)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
 
C:\Microsoft\visualfsharp>packages\dotnet\bin\dotnet.exe restore -help
 
Unhandled Exception: Microsoft.Dnx.Runtime.Common.CommandLine.CommandParsingException: Unrecognized option '-help'
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, Str
ing[] args, Int32 index, String argTypeName)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
 
C:\Microsoft\visualfsharp>

**Comment by livarcocc** [comment]
This is what we show now:

dotnet restore /?
error: /?

Still not ideal, but seems like a NuGet issue, really.
