### ISSUE TITLE
"dotnet run" for project targeting .NET Framework fails with unhelpful error on Linux

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#11351]
Trying to `dotnet run` a project targeting .NET Framework fails with the following error on Linux (and probably Mac):

```
System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
```

We should fail with a more graceful error.

**Comment by peterhuene** [comment]
I think corefx should probably provide one and not the CLI.

**Comment by dsplaisted** [comment]
I'm not sure of the details of how it all works, but I think to .NET Core / the OS it's simply an invalid file to execute, while the .NET Core SDK knows that it's a .NET Framework project which would be useful to include in the error.

**Comment by peterhuene** [comment]
That's fair, although users would probably then expect that `dotnet run` when you've set `RuntimeIdentifier` to a RID other than your current platform to behave the same, which becomes trickier to implement.
