### ISSUE TITLE
Failure in Telemetry sending should not be printed to output

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#11403]
## Steps to reproduce
* macOS
* .NET Core 3.0 preview 5
* call an unknown `dotnet` command

## Expected  behavior
Command is run or error message is written that a command is not found

## Actual behavior
```
╰─ dotnet asdfs
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-asdfs does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Internal CLR error. (0x80131506)
   at Interop+Sys.EnumerateGatewayAddressesForInterface(UInt32, DnsAddessDiscoveredCallback)
   at Interop+Sys.EnumerateGatewayAddressesForInterface(UInt32, DnsAddessDiscoveredCallback)
   at System.Net.NetworkInformation.BsdIpInterfaceProperties.GetGatewayAddresses(Int32)
   at System.Net.NetworkInformation.BsdIpInterfaceProperties..ctor(System.Net.NetworkInformation.BsdNetworkInterface, Int32)
   at System.Net.NetworkInformation.BsdNetworkInterface..ctor(System.String)
   at System.Net.NetworkInformation.BsdNetworkInterface.GetOrCreate(System.Collections.Generic.Dictionary`2<System.String,System.Net.NetworkInformation.BsdNetworkInterface>, System.String)
   at System.Net.NetworkInformation.BsdNetworkInterface+<>c__DisplayClass5_0.<GetBsdNetworkInterfaces>b__2(System.String, LinkLayerAddressInfo*)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at System.Net.NetworkInformation.BsdNetworkInterface.GetBsdNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)                                         
```

## Environment data
`netstat -nr` output:
```
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            10.0.20.1          UGSc          212        0     en0       
10.0.20/24         link#10            UCS             3        0     en0      !
10.0.20.1/32       link#10            UCS             1        0     en0      !
10.0.20.1          88:f7:c7:19:af:38  UHLWIir        53       63     en0   1183
10.0.20.21         74:81:14:3e:b8:82  UHLWIi          1       99     en0   1071
10.0.20.25/32      link#10            UCS             1        0     en0      !
10.0.20.25         f0:18:98:2a:14:55  UHLWIi          3    26429     lo0       
10.0.20.153        40:9c:28:55:70:55  UHLWIi          2    29726     en0   1097
10.0.20.255        ff:ff:ff:ff:ff:ff  UHLWbI          0        2     en0      !
127                127.0.0.1          UCS             0        0     lo0       
127.0.0.1          127.0.0.1          UH              4    99561     lo0       
169.254            link#10            UCS             2        0     en0      !
169.254.164.251    70:56:81:c7:5d:3e  UHLSW           0       12     en0      !
224.0.0/4          link#10            UmCS            3        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0      119     en0       
224.0.0.252        1:0:5e:0:0:fc      UHmLWI          0      106     en0       
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0      724     en0       
255.255.255.255/32 link#10            UCS             1        0     en0      !
255.255.255.255    ff:ff:ff:ff:ff:ff  UHLWbI          0        2     en0      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0       
default                                 fe80::%utun1                    UGcI          utun1       
default                                 fe80::%utun2                    UGcI          utun2       
::1                                     ::1                             UHL             lo0       
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0       
fe80::1%lo0                             link#2                          UHLI            lo0       
fe80::%en5/64                           link#8                          UCI             en5       
fe80::aede:48ff:fe00:1122%en5           ac:de:48:0:11:22                UHLI            lo0       
fe80::aede:48ff:fe33:4455%en5           ac:de:48:33:44:55               UHLWIi          en5       
fe80::%awdl0/64                         link#12                         UCI           awdl0       
fe80::dcd9:4cff:fef2:f19e%awdl0         de:d9:4c:f2:f1:9e               UHLI            lo0       
fe80::%utun0/64                         fe80::1bde:11de:239f:14e8%utun0 UcI           utun0       
fe80::1bde:11de:239f:14e8%utun0         link#18                         UHLI            lo0       
fe80::%utun1/64                         fe80::570:21dd:179:a871%utun1   UcI           utun1       
fe80::570:21dd:179:a871%utun1           link#20                         UHLI            lo0       
fe80::%utun2/64                         fe80::8be:f0d8:93e3:7e3c%utun2  UcI           utun2       
fe80::8be:f0d8:93e3:7e3c%utun2          link#21                         UHLI            lo0       
ff01::%lo0/32                           ::1                             UmCI            lo0       
ff01::%en5/32                           link#8                          UmCI            en5       
ff01::%awdl0/32                         link#12                         UmCI          awdl0       
ff01::%utun0/32                         fe80::1bde:11de:239f:14e8%utun0 UmCI          utun0       
ff01::%utun1/32                         fe80::570:21dd:179:a871%utun1   UmCI          utun1       
ff01::%utun2/32                         fe80::8be:f0d8:93e3:7e3c%utun2  UmCI          utun2       
ff02::%lo0/32                           ::1                             UmCI            lo0       
ff02::%en5/32                           link#8                          UmCI            en5       
ff02::%awdl0/32                         link#12                         UmCI          awdl0       
ff02::%utun0/32                         fe80::1bde:11de:239f:14e8%utun0 UmCI          utun0       
ff02::%utun1/32                         fe80::570:21dd:179:a871%utun1   UmCI          utun1       
ff02::%utun2/32                         fe80::8be:f0d8:93e3:7e3c%utun2  UmCI          utun2  
```

`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.100-rtm-009602 [/usr/local/share/dotnet/sdk]
  2.2.100 [/usr/local/share/dotnet/sdk]
  2.2.103 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  2.2.202 [/usr/local/share/dotnet/sdk]
  2.2.203 [/usr/local/share/dotnet/sdk]
  3.0.100-preview-010184 [/usr/local/share/dotnet/sdk]
  3.0.100-preview3-010431 [/usr/local/share/dotnet/sdk]
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-rtm-35673 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-rtm-35673 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-rtm-27109-04 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by dasMulli** [comment]
My concern is mostly that telemetry should fail silently.

About the underlying issue, I couldn't get `System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()` to throw when run from a simple netcoreapp3.0 console app.

**Comment by livarcocc** [comment]
@wli3 can you take a look?

**Comment by wli3** [comment]
it should @vitek-karas how to silence Internal CLR error output? This is not a exception, I cannot catch it

**Comment by FiniteReality** [comment]
I can reproduce this on a Linux install, too. However, I also occasionally get another stack trace, coming from System.Globalization:
```
Internal CLR error. (0x80131506)
   at Interop+Globalization.EnumCalendarInfo(EnumCalendarInfoCallback, System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, IntPtr)
   at Interop+Globalization.EnumCalendarInfo(EnumCalendarInfoCallback, System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, IntPtr)
   at System.Globalization.CalendarData.EnumCalendarInfo(System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, EnumCalendarsData ByRef)
   at System.Globalization.CalendarData.EnumDatePatterns(System.String, System.Globalization.CalendarId, System.Globalization.CalendarDataType, System.String[] ByRef)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(System.String, System.Globalization.CalendarId)
   at System.Globalization.CalendarData..ctor(System.String, System.Globalization.CalendarId, Boolean)
   at System.Globalization.CultureData.GetCalendar(System.Globalization.CalendarId)
   at System.Globalization.CultureData.DateSeparator(System.Globalization.CalendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(System.Globalization.CultureData, System.Globalization.CalendarId)
   at System.Globalization.DateTimeFormatInfo.set_Calendar(System.Globalization.Calendar)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.Globalization.CultureInfo.GetFormat(System.Type)
   at System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
   at System.Globalization.DateTimeFormatInfo.GetInstance(System.IFormatProvider)
   at System.Globalization.TimeSpanFormat.TryFormat(System.TimeSpan, System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
   at System.TimeSpan.TryFormat(System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
   at System.Text.StringBuilder.AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.TimeZoneInfo..ctor(Byte[], System.String, Boolean)
   at System.TimeZoneInfo.GetTimeZoneFromTzData(Byte[], System.String)
   at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile()
   at System.TimeZoneInfo+CachedData.CreateLocal()
   at System.DateTime.get_Now()
   at System.DateTimeOffset.get_Now()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Clock..cctor()
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Track(Microsoft.ApplicationInsights.Channel.ITelemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.TrackEvent(Microsoft.ApplicationInsights.DataContracts.EventTelemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.TrackEvent(System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Double>)
   at Microsoft.DotNet.Cli.Telemetry.Telemetry.TrackEventTask(System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Double>)
   at Microsoft.DotNet.Cli.Telemetry.Telemetry+<>c__DisplayClass15_0.<TrackEvent>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

As for GetIsNetworkAvailable:
```
Internal CLR error. (0x80131506)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

**Comment by FiniteReality** [comment]
Interestingly, the actual stack trace seems to vary each time the command is ran. Sometimes, no exception is thrown at all, while other times differing amounts of each exception are thrown.
