### ISSUE TITLE
dotnet-restore lock file crash

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1140]
When I run `dotnet restore` on a certain project of mine (private repo), I get the following error message:

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for C:\Users\William\Documents\Visual Studio 2015\Projects\ChocolateyApps\Core\Microsoft.Win32.UserInterface.EventedWindow\project.json...

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Commands.RestoreCommand.GetDependencyVersionRange(LibraryDependency dependency)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.Commands.RestoreCommand.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, NuGetv3LocalRepository repository, RemoteWalkContext context)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<ExecuteRestore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```

Apparently, it cannot write out the `project.lock.json` file. Unfortunately, I don't have any more information that that. This is preventing me from moving from DNX to .NET CLI. Any pointers?

**Comment by brthor** [comment]
Please give us some more details.

What OS are you on? (which version too)
Can you share your project.json?

**Comment by wjk** [comment]
Here is the `dotnet --version` output:

```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

And here is my `project.json`:

```json
{
    "version": "1.0.0",
    "description": "Win32 User Interface EventedWindow Library",
    "authors": [ "William Kent" ],
    "compilationOptions": { "allowUnsafe": true },

    "dependencies": {
        "Microsoft.Win32.UserInterface": { "target": "project" },
        "Microsoft.Win32.UserInterface.CommonControls": { "target": "project" },
        "Microsoft.Win32.UserInterface.Graphics": { "target": "project" },

        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.ComponentModel": "4.0.1-rc2-23707",
        "System.Runtime.InteropServices": "4.0.20-beta-23127"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

**Comment by wjk** [comment]
Also, I think I have managed to isolate the crash to [this code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand.cs#L863-L881).

**Comment by wjk** [comment]
Yet, weirdly, it seems to work now! I'm keeping the issue open, though, because I am still curious as to the cause.

**Comment by blackdwarf** [comment]
@wjk has the issue reproed/resurfaced with recent builds of the CLI? Or is it gone?

**Comment by wjk** [comment]
@blackdwarf This issue has not cropped up in a while, during which time I have updated the .NET CLI several times. I am now using version `1.0.0-beta-001483` (commit sha `f81ba05a7c`). I am therefore going to posit that this bug has been since resolved. I will reopen this issue if it reoccurs in the future.
