### ISSUE TITLE
Telemetry Exception in EnumerateInterfaceAddresses

### ISSUE THREAD

**Issue by daholste** [dotnet/cli#11531]
Hey .NET CLI,

To build the ML.NET CLI, we forked the telemetry portion of this repo. When @justinormont was executing this code on a Mac, during one run, the following exception occurred:

```
Internal CLR error. (0x80131506)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at System.Net.NetworkInformation.BsdNetworkInterface.GetBsdNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

Out of four runs today (and many in the past) on the Mac of the same code, this only happened one time.

Any thoughts on what the issue could be?

**Comment by daholste** [comment]
I also filed the upper portion of this stack trace in the .NET Core CLR repo https://github.com/dotnet/coreclr/issues/25091

**Comment by daholste** [comment]
Looks like this is known -- https://github.com/dotnet/coreclr/issues/25091#issuecomment-500990375
