### ISSUE TITLE
Install global tool failed with System.TypeLoadException: Could not load type 'System.Text.Json.Serialization.JsonSerializer' from assembly 'System.Text.Json

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#11545]
## Steps to reproduce
Require: machine also install netcoreapp2.1 runtime since "dotnetsay" is targeting 2.1. This should not be required when netcoreapp3.0 is released and dotnetsay is updated
1. Create empty directory
2. not yet implemented Run dotnet new tool-manifest
a. In the meantime copy the following and create file called dotnet-tools.json
 
{
"version": 1,
"isRoot": true,
"tools": {}
}

3. cd to the directory with manifest file
4. run dotnet tool install dotnetsay

## Expected  behavior
Run dotnet tool install dotnetsay succeeded.

## Actual behavior
Run failed with System.TypeLoadException: Could not load type 'System.Text.Json.Serialization.JsonSerializer' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```
   at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.Save(IDictionary`2 restoredCommandMap)
   at Microsoft.DotNet.Tools.Tool.Install.LocalToolsResolverCacheExtensions.SaveToolPackage(ILocalToolsResolverCache localToolsResolverCache, IToolPackage toolDownloadedPackage, String targetFrameworkToInstall)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.Install(FilePath manifestFile)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
`![image](https://user-images.githubusercontent.com/33921754/59422747-74f88180-8e03-11e9-9328-00b4f116c905.png)

## Environment data
D16.2/29011.391(16.2.0 preview3.0) + CLI/SDK:  3.0.100-preview7-012386

`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012386
 Commit:    23f19c91df

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012386\

Host (useful for support):
  Version: 3.0.0-preview7-27812-08
  Commit:  094b6111d3

.NET Core SDKs installed:
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010219 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012386 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19311.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27812-08 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27812-08 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download







```

**Comment by wli3** [comment]
fixed in https://github.com/dotnet/cli/pull/11532 need sometime to flow to core-sdk
