### ISSUE TITLE
System.ComponentModel.Win32Exception when using ef tools

### ISSUE THREAD

**Issue by jhoward321** [dotnet/cli#11542]
## Steps to reproduce
Run any dotnet ef command inside a working repo. I'm using the 2.2.107 sdk from the https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/ repo. Unfortunately there is not a newer sdk available.

## Expected  behavior
Show existing migrations

## Actual behavior
```
$ dotnet ef migrations list                          
System.ComponentModel.Win32Exception (2): No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.EntityFrameworkCore.Tools.Exe.Run(String executable, IReadOnlyList`1 args, String workingDirectory, Boolean interceptOutput)
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
No such file or directory
```

## Environment data
```
$ dotnet --info            
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826

Runtime Environment:
 OS Name:     fedora
 OS Version:  30
 OS Platform: Linux
 RID:         fedora.30-x64
 Base Path:   /usr/lib64/dotnet/sdk/2.2.107/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.107 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.5 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by RheaAyase** [comment]
2.1.507 and 2.2.107 are the latest up to date.
Looking into this with @aslicerh @omajid

**Comment by omajid** [comment]
The output of `dotnet ef -v migrations list ` would be nice to have.

**Comment by wli3** [comment]
This issue was moved to aspnet/EntityFrameworkCore#16071
