### ISSUE TITLE
dotnet restore (OSX)

### ISSUE THREAD

**Issue by seesharper** [dotnet/cli#1161]
```
dotnet new 
dotnet restore
```

error: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.

While this seems related to Curl, I also get an error in REPL
```
Console.WriteLine("Hello");
```

```
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Crypto.GetMaxMdSize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.EvpSha1()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.SHA1.Implementation..ctor()
   at System.Security.Cryptography.SHA1.Create()
   at Roslyn.Utilities.SHA1CryptoServiceProvider..ctor()
   at Microsoft.CodeAnalysis.CryptographicHashProvider.ComputeSha1(Byte[] bytes)
   at Microsoft.CodeAnalysis.AssemblyIdentity.CalculatePublicKeyToken(ImmutableArray`1 publicKey)
   at Microsoft.CodeAnalysis.AssemblyIdentity.get_PublicKeyToken()
   at Microsoft.CodeAnalysis.DesktopAssemblyIdentityComparer.Port(AssemblyIdentity identity)
   at Microsoft.CodeAnalysis.DesktopAssemblyIdentityComparer.ApplyUnificationPolicies(AssemblyIdentity& reference, AssemblyIdentity& definition, AssemblyIdentityParts referenceParts, Boolean& isDefinitionFxAssembly)
   at Microsoft.CodeAnalysis.AssemblyIdentityComparer.Compare(AssemblyIdentity reference, String referenceDisplayName, AssemblyIdentity definition, Boolean& unificationApplied, Boolean ignoreVersion)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMissingAssembly(AssemblyIdentity referenceIdentity, PortableExecutableReference peReference, MetadataImportOptions importOptions, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveAndBindMissingAssemblies(TCompilation compilation, ImmutableArray`1 explicitAssemblies, ImmutableArray`1 explicitModules, ImmutableArray`1 explicitReferences, ImmutableArray`1 explicitReferenceMap, MetadataReferenceResolver resolver, MetadataImportOptions importOptions, Boolean supersedeLowerVersions, ArrayBuilder`1 referenceBindings, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& allAssemblies, ImmutableArray`1& metadataReferences, ImmutableArray`1& resolvedReferences, DiagnosticBag resolutionDiagnostics)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.Bind(TCompilation compilation, ImmutableArray`1 explicitAssemblies, ImmutableArray`1 explicitModules, ImmutableArray`1 explicitReferences, ImmutableArray`1 explicitReferenceMap, MetadataReferenceResolver resolverOpt, MetadataImportOptions importOptions, Boolean supersedeLowerVersions, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& allAssemblies, ImmutableArray`1& implicitlyResolvedReferences, ImmutableArray`1& implicitlyResolvedReferenceMap, DiagnosticBag resolutionDiagnostics, Boolean& hasCircularReference, Int32& corLibraryIndex)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.BindScriptClass()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetEntryPointAndDiagnostics(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetEntryPoint(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetEntryPoint(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.Build[T](Compilation compilation, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.CommonCompile(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.TryBuildAndRun(Script`1 newScript, InteractiveScriptGlobals globals, ScriptState`1& state, ScriptOptions& options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveLoop(ScriptOptions options, String initialScriptCodeOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveCore(ErrorLogger errorLogger)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractive()
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.Csi.Main(String[] args)

```

Any ideas?

**Comment by shahid-pk** [comment]
you should also log this in dotnet/corefx may be its a problem in Curl.

**Comment by moozzyk** [comment]
I am seeing the same issue:

```
xxxxxxxxxx:SignalR-SqlServer Administrator$ cat /usr/local/share/dotnet/cli/.version
1e45e35d2070b50b7a51adea96a5158f7b49dc9d
1.0.1.001200
xxxxxxxxxx:SignalR-SqlServer Administrator$ dotnet restore
error: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
```

Darwin xxxxxxxxxx 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

**Comment by moozzyk** [comment]
Looks like this fixes the issue:
```
brew update
brew install openssl
```

Credit goes to @davidfowl

**Comment by akoeplinger** [comment]
There's a warning in the pkg installer about the openssl dependency since https://github.com/dotnet/cli/pull/880:

![image](https://cloud.githubusercontent.com/assets/1376924/12768764/53b9b0ba-ca12-11e5-983d-ba725db1820e.png)

**Comment by moozzyk** [comment]
@akoeplinger - I get my using the obtain script from the cli repo or indirectly when building aspnet repos so I have no chance of seeing this screen. I was not aware of the very recent move to a higherversion of openssl - the build worked fine last week.

**Comment by akoeplinger** [comment]
@moozzyk yep, maybe the cli should do some basic checks to see if the dependencies are there.

**Comment by blackdwarf** [comment]
@seesharper the higher version of libssl should solve the issue. Closing this, if it still repros please reopen.

**Comment by NickCraver** [comment]
Hit this today - I think that installer warning should be much stronger since you're going to hit issues with `https://` feeds very quickly.

**Comment by kedare** [comment]
Hmm same problem on my setup even with openssl installed :


```
Ξ Desktop/WebApplication → brew install openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2h_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2h_1.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2h_1: 1,691 files, 12M
Ξ Desktop/WebApplication → dotnet restore
log  : Restoring packages for /Users/kedare/Desktop/WebApplication/project.json...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   The type initializer for 'Crypto' threw an exception.
error:   The type initializer for 'CryptoInitializer' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
↑1 Desktop/WebApplication →
```

On 1.0.0-preview2-002973

How can I solve this ?

**Comment by jijiechen** [comment]
And after installing openssl, you may also need to add soft links:

    brew link --force openssl

Refer to https://www.microsoft.com/net/core#macosx

**Comment by volnet** [comment]
brew link --force openssl
Linking /usr/local/Cellar/openssl/1.0.2h_1... 
Error: Could not symlink share/man/man3/ASN1_OBJECT_free.3ssl
/usr/local/share/man/man3 is not writable.
localhost:dotnet gongcen$

**Comment by asteinberger** [comment]
@moozzyk is there a way to do this using MacPorts?

**Comment by moozzyk** [comment]
@asteinberger I guess it does not matter how you get the libs as long as the dynamic linker is able to find and load the required version.

**Comment by onionhammer** [comment]
Anyone running into this?

`Warning: Refusing to link: openssl`

**Comment by blackdwarf** [comment]
@onionhammer yes, that is the new `brew` behavior. The instructions on https://dot.net/core have been updated with a workaround.

**Comment by onionhammer** [comment]
Thanks, that worked

**Comment by legomushroom** [comment]
@blackdwarf the page has no the instructions anymore :/
