### ISSUE TITLE
dotnet restore throws System.MissingMethodException

### ISSUE THREAD

**Issue by YEVHENO** [dotnet/cli#1188]
"dotnet restore" returns following error:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.Platform Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment.get_OperatingSystemPlatform()'.
   at Microsoft.Extensions.PlatformAbstractions.RuntimeEnvironmentRidExtensions.<GetOverrideRestoreRuntimeIdentifiers>d__0.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__20`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__63`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Restore.Program.Main(String[] args)
```

OS: Microsoft Windows [Version 6.1.7601]
.NET CLI: win-x64.latest

**Comment by emgarten** [comment]
Are you running dotnet restore along with anything DNX related?

I get this same stack trace when running NuGet.CommandLine.Xplat under DNX RC1 since NuGet uses an assembly of a higher version from DNX RC2.

**Comment by YEVHENO** [comment]
I have created new project with "dotnet new" and run "dotnet restore". See console input/output below:

```
C:\Temp\app1>dotnet new
Created new project in C:\Temp\app1.

C:\Temp\app1>dotnet restore

Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft
.Extensions.PlatformAbstractions.Platform Microsoft.Extensions.PlatformAbstracti
ons.IRuntimeEnvironment.get_OperatingSystemPlatform()'.
   at Microsoft.Extensions.PlatformAbstractions.RuntimeEnvironmentRidExtensions.
<GetOverrideRestoreRuntimeIdentifiers>d__0.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__20`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__63`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 sour
ce, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Restore.Program.Main(String[] args)
```

**Comment by marono** [comment]
@YEVHENO I've seen this recently. It's related to the NuGet.Client version that you're using. I think they've recently switched to 1.0.0-rc2-16357 (from the unstable feed) and you're most likely using the current stable version (rc1-update1).

It happened to me when trying to run Nuget.Client dev branch.

Give it a go with the RC2.

**Comment by blackdwarf** [comment]
@YEVHENO have you tried @marono's suggestion? Did it work?

**Comment by SalvatoreMeschini** [comment]
I have a similar issue, see comments below:

INITIAL STATUS (1.0.0-rc2-20221 coreclr x64):

sal@SALinux ~/Dev/Test/NandoWebNew $ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-update2    coreclr x64          linux           rc1
  *    1.0.0-rc2-20221      coreclr x64          linux           default

----------------------------------------------------------------------------------------------------------------------

sal@SALinux ~/Dev/Test/NandoWebNew $ dnu restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc2-20221

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /home/sal/Dev/Test/NandoWebNew/project.json
Writing lock file /home/sal/Dev/Test/NandoWebNew/project.lock.json
Restore complete, 4506ms elapsed

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
sal@SALinux ~/Dev/Test/NandoWebNew $ dnx web
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IAssemblyLoadContextAccessor Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_AssemblyLoadContextAccessor()'.
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

----------------------------------------------------------------------------------------------------------------------

I SWITCH BACK TO RC1:

sal@SALinux ~/Dev/Test/NandoWebNew $ dnvm use rc1
Adding /home/sal/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-update2/bin to process PATH
sal@SALinux ~/Dev/Test/NandoWebNew $ dnu restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16609

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /home/sal/Dev/Test/NandoWebNew/project.json
Writing lock file /home/sal/Dev/Test/NandoWebNew/project.lock.json
Restore complete, 3406ms elapsed

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
sal@SALinux ~/Dev/Test/NandoWebNew $ dnx web
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/home/sal/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
^Csal@SALinux ~/Dev/Test/NandoWebNew $ 

NO ERRORS!
----------------------------------------------------------------------------------------------------------------------

NOW LET'S GO BACK TO RC2:

sal@SALinux ~/Dev/Test/NandoWebNew $ dnvm use default
Adding /home/sal/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc2-20221/bin to process PATH
sal@SALinux ~/Dev/Test/NandoWebNew $ dnu restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc2-20221

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /home/sal/Dev/Test/NandoWebNew/project.json
Writing lock file /home/sal/Dev/Test/NandoWebNew/project.lock.json
Restore complete, 4677ms elapsed

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
sal@SALinux ~/Dev/Test/NandoWebNew $ dnx web
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IAssemblyLoadContextAccessor Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_AssemblyLoadContextAccessor()'.
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
sal@SALinux ~/Dev/Test/NandoWebNew $

**Comment by marono** [comment]
@SalvatoreMeschini try using this feed [https://www.myget.org/gallery/aspnetvnext](https://www.myget.org/gallery/aspnetvnext).

Make sure you reference rc2-* packages.
