### ISSUE TITLE
dotnet publish assembly with whitespace in filename

### ISSUE THREAD

**Issue by rpc-scandinavia** [dotnet/cli#11990]
## Steps to reproduce
1) In a "netcoreapp3" application, comsume a "netstandard2.1" library assembly (DLL) with spaces in its names (project directory, csproj-file and build assembly).

2) Restore, build and publish:
dotnet  publish  --self-contained true  --configuration release  --runtime "linux-x86"  --output "../bin.release"

3) Execute the application, which gives this exception:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'RPC Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'RPC Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null'
   at RpcScandinavia.ITDD.ItddApplication..ctor(String[] args)
   at RpcScandinavia.ITDD.ItddApplication.Main(String[] args) in /data/users/rpc@rpc-scandinavia.dk/Development/Projects3/ITDD/ITDD - Program.cs:line 55

Aborted
```

But "RPC Core.dll" is where it should be.

## Expected  behavior
The runtime assembly loader, should be able to handle assemblies with whitespaces in their file name, in my case "RPC Core.dll", "RPC Core OpenSource.dll" and "RPC Core Resources.dll".

## Actual behavior
Please see step 3 above.

I have tried to build the same assemblies without whitespaces in their filenames, and then everything works as expected. But really here about 30 years after DOS!

I have newer experienced this with MONO, only now then I try to migrate to dotnet 3.

I have no problem running the same build from the debug directory, and manually copying the missing assemblies from the publish directory. So the problem must be the self-contained runtime assembly loader.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.2.300 [/usr/share/dotnet/sdk]
  3.0.100-preview6-012264 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by rpc-scandinavia** [comment]
Sorry, just tried with "3.0.100-preview7-012821" and now it works with the whitespace assemblies.
