### ISSUE TITLE
dotnet build of app+library fail (exception) if library pdb doesnt exists

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#1199]
App reference a library project ( example is `test/FSharpTestProjects/TestApp` or `test/TestProjects/TestApp` )

the f# compiler (and dotnet-compile-fsc) doesnt create .pdb files atm (not supported, wip).

This error it's a regression because before the `dotnet build` of app+library worked ok, now the library .pdb is expected and a bad `System.IO.FileNotFoundException` expection is raised if not exists (at least that should be an error message)

A feedback, maybe it's useful to create two helper methods in this repo:

- `FileHelper.CopyRequired(source,to,errorMessage)` => raise error message if source file doesnt exists
- `FileHelper.CopyOptional(source,to)` => no error if source file doesnt exists

And review current code to use only these two, not directly `File.Copy`. 

I can trace commit but it's not important. 

What's a possible fix?

1. copy pdb only if exists
2. error message if pdb doesnt exists **and it's enabled in project.json** (it's possible to disable pdb in project.json?)

the example:

```
PS D:\github\cli\test\FSharpTestProjects\TestApp> dotnet build
Compiling TestLibrary for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.9888705
Compiling TestApp for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.4152821
System.IO.FileNotFoundException: Could not find file 'D:\github\cli\test\FSharpTestProjects\TestLibrary\bin\Debug\dnxcor
e50\TestLibrary.pdb'.
File name: 'D:\github\cli\test\FSharpTestProjects\TestLibrary\bin\Debug\dnxcore50\TestLibrary.pdb'
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at Microsoft.DotNet.Cli.Compiler.Common.LibraryExporterExtensions.CopyTo(IEnumerable`1 assets, String destinationPath
)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.WriteDepsFileAndCopyProjectDependencies(LibraryExporter exporter,
String projectFileName, String outputPath)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.MakeCompilationOutputRunnableForCoreCLR(String outputPath, Library
Exporter exporter)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.ExportRuntimeAssets(String outputPath, String configuration)
   at Microsoft.Dotnet.Cli.Compiler.Common.Executable.MakeCompilationOutputRunnable(String configuration)
   at Microsoft.DotNet.Tools.Build.CompileContext.MakeRunnableIfNecessary()
   at Microsoft.DotNet.Tools.Build.CompileContext.InvokeCompileOnRootProject()
   at Microsoft.DotNet.Tools.Build.CompileContext.Compile(Boolean incremental)
   at Microsoft.DotNet.Tools.Build.BuildCommand.<>c__DisplayClass1_0.<OnExecute>b__2(CompileContext c)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Tools.Build.BuildCommand.OnExecute(List`1 contexts, CompilerCommandApp args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.<>c__DisplayClass70_0.<Execute>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.Execute(OnExecute execute, String[] args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
```

**Comment by davidfowl** [comment]
We should make it check for existence. That's the simplest fix

**Comment by enricosada** [comment]
thx @davidfowl i'll send a pr
