### ISSUE TITLE
sni.dll does not load on Windows 7

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#1210]
System.Data.SqlClient.SqlConnection fails to initialize native library sni.dll on Windows 7 x64.

Using dotnet 1.0.1.001200

To repro:
```
> dotnet restore -s https://myget.org/F/dotnet-core -s https://myget.org/F/aspnetcidev
> dotnet run
(open web browser to https://localhost:5000/)
```

This works fine on Windows 10.

**project.json**. [See project.lock.json in this gist](https://gist.github.com/natemcmaster/04945e2b9a77caf850f1#file-project-lock-json)
```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
"dependencies": {
  "NETStandard.Library": "1.0.0-*",
  "Microsoft.Extensions.Logging.Console": "1.0.0-*",
  "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
  "System.Data.SqlClient": "4.0.0-*"
},
  "frameworks": {
    "dnxcore50": { }
  }
}
```
**Program.cs**
```c#
using System;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;

namespace ConsoleApplication
{
  public class Startup
  {
    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
    {
      loggerFactory.AddConsole(LogLevel.Trace);
      app.Run(async context => {
        try {
          using(var con = new SqlConnection(" { connection string here } "))
          {
            con.Open();
            await context.Response.WriteAsync("Connection opened :)");
          }
        }
        catch(Exception e)
        {
          Console.WriteLine(e.ToString());
          throw e;
        }
        });
      }

      public static void Main(string[] args)
      {
        var host = new WebHostBuilder()
        .UseDefaultConfiguration(args)
        .UseStartup<Startup>()
        .UseServer("Microsoft.AspNetCore.Server.Kestrel")
        .Build();

        host.Run();
      }
    }
  }
```

*Error*. [Full stack trace here](https://gist.github.com/natemcmaster/04945e2b9a77caf850f1)
```
      Request starting HTTP/1.1 GET http://localhost:5000/
System.TypeInitializationException: The type initializer for 'System.Data.SqlCli
ent.TdsParser' threw an exception. ---> System.TypeInitializationException: The
type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. -
--> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified mod
ule could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
```

**Comment by natemcmaster** [comment]
cc @kkurni @saurabh500 still can't get SqlClient working on Windows 7 with RC2 bits

**Comment by saurabh500** [comment]
@natemcmaster  The fix for the removal of C++ redist dependency is not checked in yet.
Does this issue occur inspite of the C++ redist installation?

**Comment by natemcmaster** [comment]
No, it works find with the C++ redist. Thanks for clarifying. I was somehow under the impression we had removed our dependency on vcredist.

**Comment by saurabh500** [comment]
Related to https://github.com/dotnet/corefx/issues/3760
