### ISSUE TITLE
Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault() : Could not load file or assembly System.Reflection, Version=4.1.0.0

### ISSUE THREAD

**Issue by adrien-constant** [dotnet/cli#1227]
I have an ASP.NET Core 1.0 application, which crashes at startup after the update from ASP.NET 5 rc2.

This is similar to the following issue : https://github.com/aspnet/KestrelHttpServer/issues/606

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.DependencyModel.DependencyContext.get_Default()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DependencyContextAssemblyProvider.GetCandidateLibraries()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DependencyContextAssemblyProvider.get_CandidateAssemblies()
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerTypeProvider.get_ControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.ClaimsTransformationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

=== Pre-bind state information ===
LOG: DisplayName = System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Adrien/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc2-16357/bin/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Fusion is hosted. Check host about this assembly.
LOG: Try host assembly store with assembly system.reflection, version=4.1.0.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a, processorarchitecture=x86.
LOG: Try host assembly store with assembly system.reflection, version=4.1.0.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a, processorarchitecture=msil.
LOG: Try host assembly store with assembly system.reflection, version=4.1.0.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a.
WRN: Host assembly store does not contain this assembly.
LOG: Attempting download of new URL file:///C:/Users/Adrien/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc2-16357/bin/System.Reflection.DLL.
LOG: Attempting download of new URL file:///C:/Users/Adrien/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc2-16357/bin/System.Reflection/System.Reflection.DLL.
LOG: Attempting download of new URL file:///C:/Users/Adrien/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc2-16357/bin/System.Reflection.EXE.
LOG: Attempting download of new URL file:///C:/Users/Adrien/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc2-16357/bin/System.Reflection/System.Reflection.EXE.
```

And my project json :

```
{
  "webroot": "wwwroot",
  "version": "0.34-*",
  "dependencies": {
    "DocumentFormat.OpenXml": "2.5.0",
    "WindowsAzure.Storage": "6.2.2-preview",
    "Microsoft.Extensions.Options": "1.0.0-rc2-16027",
    "Microsoft.Framework.Configuration.Json": "1.0.0-rc1-15678",
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-rc2-16811",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-16811",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-16346",
    "Microsoft.AspNetCore.Authorization": "1.0.0-rc2-16346",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-16547",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-16547",
    "Microsoft.AspNetCore.Identity": "1.0.0-rc2-16422",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-16422",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-17011",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0-rc2-17011",
    "Microsoft.AspNetCore.Mvc.Localization": "1.0.0-rc2-17011",
    "Microsoft.AspNetCore.Mvc.Razor": "1.0.0-rc2-17011",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-17011",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.0-rc2-17011",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0-rc2-16035",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-16035",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-16033",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc2-16002",
    "Microsoft.Extensions.Localization": "1.0.0-rc2-16265",
    "Microsoft.Extensions.Localization.Abstractions": "1.0.0-rc2-16265",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-16049",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-16049",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-16049",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-16336",
    "Microsoft.AspNetCore.Tooling.Razor": "1.0.0-rc2-16143",
    "Microsoft.AspNetCore.Hosting": "1.0.0-rc2-16276",
    "Microsoft.AspNetCore.Http.Abstractions": "1.0.0-rc2-16198",
    "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-rc2-16198",
    "Microsoft.AspNetCore.Localization": "1.0.0-rc2-16265",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-16373",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-rc2-16214",
    "Microsoft.AspNetCore.Session": "1.0.0-rc2-16234",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-16225"
  },
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "System.Reflection": "4.1.0-rc2-23728"
      },
      "frameworkAssemblies": {
        "WindowsBase": ""
      }    
    }
  }
}
```
Using the latest version 4.1.0-rc3-23803 System.Reflection version did not work either.

**Comment by adrien-constant** [comment]
Just doing the following code raises the exception :

```
        public static void Main(string[] args)
        {
            var deps = DependencyContext.Default;
        }
```

**Comment by eaardal** [comment]
Hi

I got a similar error and stack trace with a different exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DependencyContextAssemblyProvider.GetCandidateLibraries()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DependencyContextAssemblyProvider.get_CandidateAssemblies()
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerTypeProvider.get_ControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DietMaestro.WebApplication.Startup.AuthenticateStaticFileRequest.<Invoke>d__3.MoveNext() in C:\Dev\Projects\DietMaestro\src\DietMaestro.WebApplication\Startup\AuthenticateStaticFileRequests.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

![image](https://cloud.githubusercontent.com/assets/2316274/12955920/9f1dc2b2-d025-11e5-8921-3f177d8c87fa.png)

Using 1.0.0-rc2-16357

**Comment by sunsided** [comment]
Same for me on 16357 using
```xml
  <packageSources>
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnetvnext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
    <add key="AspNet Contrib" value="https://www.myget.org/F/aspnet-contrib/" />
    <add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="xUnit CI" value="https://www.myget.org/F/xunit/" />
  </packageSources>
```

**Comment by blackdwarf** [comment]
@sunsided can you confirm that using newer version doesn't repro this?

**Comment by sunsided** [comment]
Yup, works like a charm, also on 16549 as well.

**Comment by blackdwarf** [comment]
@sunsided thanks, will close then. Reopen if it still repros.
