### ISSUE TITLE
Make delete more robust

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#126]
```
> dotnet-compile
Compiling WebApplication106 for DNXCore,Version=v5.0
System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Microsoft.DotNet.Tools.Compiler.Program.Compile(ProjectContext context, String configuration, String outputPath, Boolean buildProjectReferences)
   at Microsoft.DotNet.Tools.Compiler.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.Program.Main(String[] args)
< dotnet-compile exited with 1 in 1347 ms.
```

**Comment by blackdwarf** [comment]
@davidfowl is this still an issue?
