### ISSUE TITLE
dotnet cli, test, build, run, broken; Infinite recursion

### ISSUE THREAD

**Issue by t-hart** [dotnet/cli#12890]
Hey! I ran into an issue today with the CLI, where suddenly nothing seems to work anymore. I'm not sure how I got into this state, but now I can't seem to get out. I tried reinstalling, rebooting, upgrading my OS. Almost every single `dotnet` command I've tried (the only exception being `--version`) terminates with an infinite recursion error.

## Steps to reproduce

Not sure how I got into this state, but now most any command I try and run gives me the same error. `test`, `build`, `run`, `publish`, and `--info` all yield the same result. 

## Expected  behavior

The commands should do what they are designed to, not throw an infinite recursion error.

## Actual behavior

The processes terminate with this output:
```
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Argument_InvalidResourceCultureName
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Globalization.CultureInfo.VerifyCultureName(System.String, Boolean)
   at System.Resources.ResourceManager.GetResourceFileName(System.Globalization.CultureInfo)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Globalization.CultureInfo.VerifyCultureName(System.String, Boolean)
   at System.Resources.ResourceManager.GetResourceFileName(System.Globalization.CultureInfo)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at Microsoft.TemplateEngine.Cli.LocalizableStrings.get_DisplaysHelp()
   at Microsoft.TemplateEngine.Cli.CommandParsing.CommandParserSupport.get_NewCommandVisibleArgs()
   at Microsoft.TemplateEngine.Cli.CommandParsing.CommandParserSupport.CreateNewCommandWithoutTemplateInfo(System.String)
   at Microsoft.DotNet.Cli.Parser..cctor()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(System.String[], Microsoft.DotNet.Cli.Telemetry.ITelemetry)
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
```

## Environment data
`dotnet --info` output: `dotnet --info` exits with the same message as above, but `dotnet --version` yields `3.0.100`

On macOS. Was on Mojave, tried updating to Catalina to get around this, but nothing changed.

Sorry for not being able to dump `--info` output, but just let  me know what you need, and I'll try and find out for you.

**Comment by livarcocc** [comment]
@t-hart can you run a separate framework dependent app through `dotnet <path_to_app_dll>`?

@stephentoub could you help debug or redirect this issue?

**Comment by tarekgh** [comment]
Need to know how and what culture is used in 

```
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at Microsoft.TemplateEngine.Cli.LocalizableStrings.get_DisplaysHelp()
```

Looks somehow the culture is created with a strange name or with characters that are not classified as Unicode char or number. would be interesting you know the culture name used there.

**Comment by t-hart** [comment]
@livarcocc From what I gather,  a framework-dependent app is the default build target, right? Here's a 3.0 console app. It spins up, logs two lines of output, and then runs into the same problem:

```
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Argument_InvalidResourceCultureName
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Globalization.CultureInfo.VerifyCultureName(System.String, Boolean)
   at System.Resources.ResourceManager.GetResourceFileName(System.Globalization.CultureInfo)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Globalization.CultureInfo.VerifyCultureName(System.String, Boolean)
   at System.Resources.ResourceManager.GetResourceFileName(System.Globalization.CultureInfo)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Text.EncodingTable.GetDisplayName(Int32, Int32)
   at System.Text.EncodingTable.InternalGetCodePageDataItem(Int32, Int32)
   at System.Text.EncodingTable.GetCodePageDataItem(Int32)
   at System.Text.Encoding.GetDataItem()
   at System.Text.Encoding.get_WebName()
   at System.Xml.XmlTextReaderImpl.SwitchEncoding(System.Text.Encoding)
   at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean)
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(System.IO.Stream, System.String, Boolean, System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   at System.Configuration.BaseConfigurationRecord.Init(System.Configuration.Internal.IInternalConfigRoot, System.Configuration.BaseConfigurationRecord, System.String, System.String)
   at System.Configuration.RuntimeConfigurationRecord.Create(System.Configuration.Internal.InternalConfigRoot, System.Configuration.Internal.IInternalConfigRecord, System.String)
   at System.Configuration.Internal.InternalConfigRoot.GetConfigRecord(System.String)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(System.String)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at Microsoft.Data.SqlClient.SqlConnection..cctor()
   at Microsoft.Data.SqlClient.SqlConnection..ctor(System.String)
   at AdProducer.IO+<FetchData>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at AdProducer.IO.FetchData(System.String)
   at AdProducer.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at AdProducer.Program.Main()
   at AdProducer.Program.<Main>()
```

@tarekgh: how would I know what culture is used? The value of the `LANG` env var is `en_US=UTF-8`. Which, now that I look at it, doesn't look right. And that seems to have been it! Re-sourcing my config (after having corrected the value to  `en_US.UTF-8`) seems to have solved  it.

I guess it came down to user error in the end, but this was the only thing that was acting up which is probably why I hadn't thought to look there. Thanks for your help with that!
