### ISSUE TITLE
Random AV in Roslyn?

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#132]
Got the following randomly while building dotnet-ci. It doesn't repro consistently (hasn't even happened a second time yet), but wanted to raise it in case anyone has seen it, or sees it in the future.

/cc @jaredpar @agocke @davidfowl 

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items, Func`2 selector)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.SelectAsArray[TItem,TResult](ImmutableArray`1 items, Func`2 map)
   at Microsoft.CodeAnalysis.CSharp.MergedTypeDeclaration.get_SyntaxReferences()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.get_SyntaxReferences()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.get_DeclaringSyntaxReferences()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.GetNonNullSyntaxNode(Symbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass20_0.<CompileNamedTypeAsTask>b__0()
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by krwq** [comment]
I already opened one bug on them with some other AV, I added ref to this issue:
https://github.com/dotnet/roslyn/issues/6993

**Comment by agocke** [comment]
I think this should stay open. This looks definitively like a bug in CoreCLR.

https://github.com/dotnet/roslyn/issues/6993 could theoretically be the DiaSymReader, so it can stay as a separate issue.

**Comment by agocke** [comment]
Alternatively, we can open a bug on CoreCLR. This won't be actionable without a dump, though.

**Comment by krwq** [comment]
Also added https://github.com/dotnet/coreclr/issues/2153
