### ISSUE TITLE
'dotnet run' without a project.lock.json file doesn't have a good user experience

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#1335]
To repro:

```
make a new directory, cd into it
dotnet new
dotnet run
```

Gives the following output:

```
System.InvalidOperationException: Couldn't find default target with framework: DNXCore,.NETStandardApp
   at Microsoft.DotNet.Tools.Run.RunCommand.CalculateDefaultsForNonAssigned() in C:\cli\src\dotnet\commands\dotnet-run\RunCommand.cs:line 80
   at Microsoft.DotNet.Tools.Run.RunCommand.RunExecutable() in C:\cli\src\dotnet\commands\dotnet-run\RunCommand.cs:line 98
   at Microsoft.DotNet.Tools.Run.RunCommand.Start() in C:\cli\src\dotnet\commands\dotnet-run\RunCommand.cs:line 34
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args) in C:\cli\src\dotnet\commands\dotnet-run\Program.cs:line 58
```

At this point as a user, I don't know what I should do. This error message doesn't tell me what is wrong.

**Comment by Boglen** [comment]
Try 
dotnet run -f net451
