### ISSUE TITLE
FileNotFoundException: dotnet test 

### ISSUE THREAD

**Issue by endeffects** [dotnet/cli#1343]
Hi, when i run dotnet test for my test project i'm getting a FileNotFoundException and the corehost.exe crashes.

```
dotnet test
 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 
'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
or one of its dependencies. The system cannot find the file specified.
```

```
    "dependencies": {
        "NETStandard.Library": "1.0.0-*",
        "Microsoft.AspNetCore.TestHost": "1.0.0-*",
        "xunit": "2.2.0-*",
        "dotnet-test-xunit": "1.0.0-*"
    },

    "frameworks": {
        "dnxcore50": { }
    },

    "testRunner": "xunit"
```

**Comment by livarcocc** [comment]
@endeffects Did you run dotnet build before running dotnet test? Just plain dotnet build?

**Comment by endeffects** [comment]
yes, for sure :)

**Comment by livarcocc** [comment]
This usually happens because you haven't built the project, see https://github.com/dotnet/cli/issues/1152. Other than that, a few weeks ago we had an issue where we were not passing the deps file correctly to the corehost. How old/new is your version of the CLI?

**Comment by endeffects** [comment]
i have installed the latest cli yesterday

**Comment by livarcocc** [comment]
Sorry to ask you this, but is your project on github? Can you share the repo with me so that I can try to repro this?

If not, can you give me a repro on a project that you can share?

**Comment by endeffects** [comment]
well it's a really simple test project without any special stuff, but i can upload it tomorrow. i'm out of office for today.

**Comment by livarcocc** [comment]
All right, I will wait for it and try it then. We are using dotnet test for most of our tests now and it seems to be working, that's why I am asking for the repro.

**Comment by endeffects** [comment]
to speed things up, is there anything else you need? is there any way to print the cli / runtime versions?

**Comment by livarcocc** [comment]
dotnet --version
Also, you can run dotnet -v test, which prints out more details about what dotnet is doing including the exact commands we are using to run the tests, that would be helpful too.

**Comment by endeffects** [comment]
thanks, i'll prepare it for tomorrow. :)

**Comment by tushargupta51** [comment]
@livarcocc I am facing the exact same issue. It started showing up today.

Repo I am building: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet, KDev branch

dotnet version:
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

Error:
info:   program: dotnet
info:   commandline: test
info:   workingdir: test\Microsoft.IdentityModel.Logging.Tests
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
fail: Exit code 255 from dotnet
fail: Stack trace:
   at View8bfa37c6d03a44059cf257ce5dcec7ee.Dotnet(String command, String dotnetDir) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 1273
   at View8bfa37c6d03a44059cf257ce5dcec7ee.DotnetTest(String projectFile, Boolean testParallel) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 1498
   at View8bfa37c6d03a44059cf257ce5dcec7ee.<RenderViewLevel0>b__d0(String projectFile) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 10648
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at View8bfa37c6d03a44059cf257ce5dcec7ee.<RenderViewLevel0>b__ce() in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 10648
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View8bfa37c6d03a44059cf257ce5dcec7ee.StartingTarget(String name) in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 3522
   at View8bfa37c6d03a44059cf257ce5dcec7ee.<RenderViewLevel0>b__74() in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 4006
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View8bfa37c6d03a44059cf257ce5dcec7ee.<RenderViewLevel0>b__6c() in c:\Users\tugupta.REDMOND\AppData\Local\Temp\b16ec15fadfe4c2aa62f7b472557dd85-1.cs:line 3862
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by livarcocc** [comment]
I haven't seen a repro for this. @tushargupta51 if this is still happening to you, please, re-activate.

**Comment by tushargupta51** [comment]
@livarcocc I no longer get this error. I think it went away after I updated to a later version of dotnet. Thanks!
