### ISSUE TITLE
If a single framework is specific in project.json use it for dotnet run

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1414]
I currently get this error:

```
System.InvalidOperationException: Couldn't find default target with framework: DNXCore,.NETStandardApp
   at Microsoft.DotNet.Tools.Run.RunCommand.CalculateDefaultsForNonAssigned()
   at Microsoft.DotNet.Tools.Run.RunCommand.RunExecutable()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
```

/cc @pakrym

**Comment by pakrym** [comment]
Run restore, there is no runtime target in project.lock

**Comment by davidfowl** [comment]
This used to work and it broke. Running `dotnet run -f net451` works.

**Comment by pakrym** [comment]
Will fix.

**Comment by blackdwarf** [comment]
@pakrym @davidfowl is this fixed? Should we close?
