### ISSUE TITLE
dotnet compile fails to resolve depedencies on Linux

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#151]
The repro program and project.json are below. On Windows, doing dotnet compile and then running the exe works. On Linux, the compile passes but running it fails with the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.NameResolution, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.Net.Sockets.Socket.InitializeSockets()
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.TcpListener..ctor(IPAddress localaddr, Int32 port)
   at SampleEchoServer.Server.Start(Int32 port)
   at SampleEchoServer.Program.Main(String[] args)
Aborted (core dumped)`
```

```csharp
using System;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

namespace SampleEchoServer
{
    class Program
    {
        //Let's assume that port 8888 is available
        static void Main(string[] args) => new Server().Start(8888);
    }

    public class Server
    {

        public void Start(int port)
        {

            TcpListener server = new TcpListener(IPAddress.Any, port);
            server.Start();
            Console.WriteLine($"Server started on port {port}");
            while (true)
            {
                try
                {
                    HandleClient(server.AcceptTcpClient());
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"That hurt... trying to recover from an exception:'{ex.Message}'");
                }
            }
        }

        public void HandleClient(TcpClient c)
        {
            string msg = null;
            bool connected = true;

            Console.WriteLine($"Connection accepted {DateTime.Now}");
            using (var output = new StreamWriter(c.GetStream(), UTF32Encoding.ASCII) { AutoFlush = true })
            {
                using (var input = new StreamReader(c.GetStream(), UTF32Encoding.ASCII))
                {
                    while (connected)
                    {
                        switch (msg = input.ReadLine())
                        {
                            case "done":
                                connected = false;
                                break;
                            default:
                                output.WriteLine(msg);
                                break;
                        }
                    }
                }

            }
            //  c.Close();
            Console.WriteLine("bye...");
        }
    }
}
```

```json
{
    "compilationOptions": {
        "emitEntryPoint": true
    },
  "dependencies": {
    "System.Console": "4.0.0-beta-23419",
    "Microsoft.NETCore.Runtime": "1.0.1-beta-23419",
    "Microsoft.NETCore.ConsoleHost": "1.0.0-beta-23419",
    "Microsoft.NETCore.TestHost": "1.0.0-beta-23419",
    "System.Net.Sockets": "4.1.0-beta-23409"
  },
  "frameworks": {
    "dnxcore50": {}
  }
}
```

**Comment by piotrpMSFT** [comment]
#498 tracks the OS X RID issue
@blackdwarf can you reopen if this still repros?
