### ISSUE TITLE
corehost.exe not throwing proper error while resolving run time dependency

### ISSUE THREAD

**Issue by mayabans** [dotnet/cli#1517]
A run time dependency for user dll was created on some another dll, and while resolving this dependency corehost.exe did not throw a proper  Exception like System.IO.FileNotFoundException, but instead following error was thrown

```
Error: test-xunit returned '-532462766'.

Error: Error discovering tests in 'C:\Users\maban\Desktop\DotNetTooling_Latest\SampleProject\web\KWebDemo\KWebDemo\src\KTestingDemo\project.json'.
Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: test-xunit returned '-532462766'.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at Microsoft.VisualStudio.ProjectSystem.DotNet.UnitTestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.ProjectSystem.DotNet.UnitTestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: test-xunit returned '-532462766'.<---
```

**Comment by piotrpMSFT** [comment]
@schellap

**Comment by schellap** [comment]
Please reopen with better repro steps.

**Comment by blackhill** [comment]
I had the same error when I added : "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final" as a dependecy in my project.json
