### ISSUE TITLE
[DotNet.ProjectModel.Server] exception Value cannot be null.  Parameter name: o

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1683]
## Steps to reproduce
We have an automated test that creates 8 new projects quickly one after another and it can see this exception almost everytime from dotnet projectmodel.server.  I can not repo it manually consistently, so maybe stack trace would help with investigation. If not I could share Apex test for debugging.

fail: Microsoft.DotNet.ProjectModel.Server.ProjectManager[0]
      A unexpected exception occurred: System.ArgumentNullException: Value cannot be null.
      Parameter name: o
         at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
         at Microsoft.DotNet.ProjectModel.Server.Models.Message.FromPayload(String messageType, Int32 contextId, Object payload) in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-projectmodel-server\Models\Message.cs:line 13
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.Transmit(String messageType, Object payload) in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-projectmodel-server\ProjectManager.cs:line 100
         at Microsoft.DotNet.ProjectModel.Server.Messengers.Messenger`1.UpdateRemote(T local, T remote) in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-projectmodel-server\Messengers\Messenger.cs:line 29
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.SendOutgingMessages() in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-projectmodel-server\ProjectManager.cs:line 294
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.DoProcessLoop() in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-projectmodel-server\ProjectManager.cs:line 160
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.ProcessLoop() in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-projectmodel-server\ProjectManager.cs:line 121
info: Microsoft.DotNet.ProjectModel.Server.ProcessingQueue[0]
      OnSend ((556032041a374b37b48e7456ba0b43c2, Dependencies, 5) -> {
        "Framework": {
          "FrameworkName": ".NETStandardApp,Version=v1.5",
          "FriendlyName": ".NETStandardApp,Version=v1.5",
          "ShortName": "netstandardapp1.5",
          "RedistListPath": null
        },

## Environment data
`dotnet --version` output:

**Comment by abpiskunov** [comment]
Closing as dupe of #1674
