### ISSUE TITLE
Remove dotnet-resgen as a top level command (until we support codegen)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1702]
## Steps to reproduce
```
dotnet resgen
```

## Expected  behavior
```
No executable found matching command "dotnet-resgen"
```

## Actual behavior
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tools.Resgen.ResgenCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001634)

Product Information:
 Version:     1.0.0-beta-001634
 Commit Sha:  3ed9361763

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

**Comment by brthor** [comment]
It doesn't look like anything invokes resgen out of process that I can find so this should be fairly straightforward.
