### ISSUE TITLE
Transient failure during package.sh on Ubuntu

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1765]
This build: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?favDefinitionId=601&_a=summary&buildId=102679 had a weird failure in package.sh that went away on rebuild. Some details (more available in the full log linked above:

```
... snipped a LOT ...
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.884Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.885Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.885Z: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2016-03-08T23:39:32.885Z: 
2016-03-08T23:39:32.885Z: util.js:35
2016-03-08T23:39:32.885Z:   var str = String(f).replace(formatRegExp, function(x) {
2016-03-08T23:39:32.885Z:                       ^
2016-03-08T23:39:32.885Z: RangeError: Maximum call stack size exceeded
2016-03-08T23:39:32.885Z: [0;31merror:[0m uploading the dotnet_1.0.0.001672-1_amd64.deb to blob storage - 
2016-03-08T23:39:32.885Z: EC       <] IL]  /opt/code/scripts/package/package.sh exited with 1
2016-03-08T23:39:33.076Z: RGET     <] IL]  Publish                                     (Microsoft.DotNet.Cli.Build.PublishTargets.Publish)
2016-03-08T23:39:33.077Z:  Default                                     (Standard Goals)
2016-03-08T23:39:33.078Z: Build failed: Microsoft.DotNet.Cli.Build.Framework.BuildFailureException: Command failed with exit code 1: /opt/code/scripts/package/package.sh 
2016-03-08T23:39:33.079Z:    at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful()
2016-03-08T23:39:33.079Z:    at Microsoft.DotNet.Cli.Build.PublishTargets.Publish(BuildTargetContext c)
2016-03-08T23:39:33.079Z:    at Microsoft.DotNet.Cli.Build.Framework.BuildContext.ExecTarget(BuildTarget target)
##[Error] 2016-03-08T23:39:46.823Z: Bash failed with error: /bin/bash failed with return code: 1
##[Error] 2016-03-08T23:39:46.823Z: 
```

/cc @brthor @livarcocc

**Comment by brthor** [comment]
Azure CLI bug? :smile: 

@Sridhar-MS is switching us to the c# api so I think we can safely ignore this transient failure until that goes in.
https://github.com/dotnet/cli/pull/1739/files

**Comment by blackdwarf** [comment]
@brthor @anurse I'm gonna close this then, we can reopen if this thing keeps popping up.
