### ISSUE TITLE
[dotnet native] NullReferenceException for 2 modules project

### ISSUE THREAD

**Issue by songdongsheng** [dotnet/cli#1787]
## Steps to reproduce

Create module EventBus (dll) and EventBusTest (exe), EventBusTest depend EventBus.

dotnet build works fine, but if I run native build, I got NullReferenceException:

Error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory context)
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.get_MarkedNodeList()
   at ILCompiler.Compilation.CompileSingleFile()
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)

## Environment data
`dotnet --version` output:

C:\>dotnet --version
.NET Command Line Tools (1.0.0-beta-001687)

Product Information:
 Version:     1.0.0-beta-001687
 Commit Sha:  7c6a2ad8b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by songdongsheng** [comment]
ubuntu 14.04 have the same issue:
    
    [root@ubuntu-1404-01:~/EventBus/EventBusTest]# dotnet build -c Release -n
    Project EventBus (.NETStandardApp,Version=v1.5) will be compiled because some of its inputs were newer than its oldest output.
    Compiling EventBus for .NETStandardApp,Version=v1.5

    Compilation succeeded.
        0 Warning(s)
        0 Error(s)

    Time elapsed 00:00:02.6907405
    Compiling EventBusTest for .NETStandardApp,Version=v1.5

    Compilation succeeded.
        0 Warning(s)
        0 Error(s)

    Time elapsed 00:00:02.4298683
    Input Assembly: /root/EventBus/EventBusTest/bin/Release/netstandardapp1.5/EventBusTest.dll
    Error: Object reference not set to an instance of an object.
    System.NullReferenceException: Object reference not set to an instance of an object.
       at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory context)
       at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
       at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
       at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.get_MarkedNodeList()
       at ILCompiler.Compilation.CompileSingleFile()
       at ILCompiler.Program.Run(String[] args)
       at ILCompiler.Program.Main(String[] args)

[root@ubuntu-1404-01:~/EventBus/EventBusTest]# dotnet --version
.NET Command Line Tools (1.0.0-beta-001694)

Product Information:
 Version:     1.0.0-beta-001694
 Commit Sha:  88c1340f6d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

**Comment by blackdwarf** [comment]
As native compilation is not part of the CLI I will be closing this. If it still repros, please reopen on dotnet/corert.
