### ISSUE TITLE
Unable to load DLL 'libuv'

### ISSUE THREAD

**Issue by noliar** [dotnet/cli#1830]
## Steps to reproduce
I install dotnet cli in Deepin 2014.3 based on Ubuntu 14.04.
![20160313100837](https://cloud.githubusercontent.com/assets/5773982/13726495/5fdb9ee2-e904-11e5-9682-08305f97825f.png)

But I ran [aspnet/cli_samples](https://github.com/aspnet/cli-samples/tree/master/HelloMvc) only to get a exception 
![20160313101839](https://cloud.githubusercontent.com/assets/5773982/13726502/0ef381c4-e905-11e5-97c6-5cce7710602c.png)

So I think that is losing libuv.so/libuv.dll.

And I search  'libuv' in project.lock.json. The result is:
![20160313102035](https://cloud.githubusercontent.com/assets/5773982/13726510/85f98b1a-e905-11e5-9a3e-b229009b3f92.png)
![20160313102412](https://cloud.githubusercontent.com/assets/5773982/13726516/c888967e-e905-11e5-98a3-ae0c023c0ccd.png)

So I copy libuv.so from `Microsoft.AspNetCore.Server.Kestrel` folder to my output folder. 

It looks like 'working'.
![20160313102657](https://cloud.githubusercontent.com/assets/5773982/13726523/271d67aa-e906-11e5-88a7-1912e8f15409.png)

But when I visit localhost:5000

the output is :

-------------------------------------------------------------
```

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JObject root)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultAssemblyProvider..ctor(IApplicationEnvironment environment)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

```

I guess the reason is that the `Microsoft.Extensions.DependencyModel` package file in cdn server of myget  is too old.

**Comment by weidazhao** [comment]
I'm seeing the same error on Windows.

**Comment by mmalolepszy** [comment]
I've also seen this error, but since 1.0.0-beta-001829 its gone.

**Comment by weidazhao** [comment]
Microsoft.AspNetCore.Mvc has got rid of the dependency on Microsoft.Extensions.DependencyModel since https://github.com/aspnet/Mvc/commit/4299a4d50bd782b9253c0e69a0505463492bfc5f. Should be good now.
