### ISSUE TITLE
dotnet-test-xunit incompatible with build 23921

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#1975]
We're trying to upgrade our packages to NETStandard.Library 1.5.0-rc2-23921, and cannot move forward as `dotnet-test-xunit` is incompatible.

This [repo](https://github.com/andschwa/xunit-bug) has a simple repro.

After restoring and building,

```sh
$ dotnet test
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Xunit.Runner.DotNet.Program..ctor()
   at Xunit.Runner.DotNet.Program.Main(String[] args)
```

dotnet/corefx#7038 tracks a similar compatibility issue.

@livarcocc and I can both reproduce this on Windows and Linux with various recent versions of CLI; the issue is an incompatible package the runner is bringing in.

**Comment by andschwa** [comment]
Note that the same failure reproduces despite trying a build with dotnet/coreclr.xunit#15.

**Comment by livarcocc** [comment]
This is happening when reading the JObject in the DependencyContext. I already tried adding System.Collections to the project.json of the runner but no success. I am not sure how to proceed in the investigation of this issue.

@ericstj @pakrym Is this something that you guys can help me with? 

Project dotnet-test-xunit (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JObject root)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)

**Comment by andschwa** [comment]
It is compatible with Build 23922.
