### ISSUE TITLE
NullRefException when trying to run a tool that was not restored correctly

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2119]
## Steps to reproduce
- Create an application with a tool (or a version of a tool) that doesn't exist
- Run restore - it will restore the application just fine but will fail to restore the tool 
- Run the tool - e.g. `dotnet watch` 
## Expected  behavior

An error saying that the tool was to restored correctly
## Actual behavior

```
    C:\source\dotnet-watch\artifacts\build
PS C:\source\dotnet-watch\testWorkDir\8f45772d-5d7a-40c4-96f3-788e71ec1e7a\work\NoDepsApp> dotnet watch
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.ToolPathCalculator.GetLockFilePath(String packageId, NuGetVersion version, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFilePath(LibraryRange toolLibrary, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFile(LibraryRange toolLibrary, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(LibraryRange toolLibraryRange, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(String commandName, IEnumerable`1 args, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
## Environment data

`dotnet --version` output:

```
PS C:\source\dotnet-watch\testWorkDir\8f45772d-5d7a-40c4-96f3-788e71ec1e7a\work\NoDepsApp> dotnet --version
1.0.0-beta-002111
```

**Comment by livarcocc** [comment]
Restore will fail if you add a reference to a non-existing tool (or a non-existing version).
