### ISSUE TITLE
Cannot run Test Projects unless restored with --infer-runtimes

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2201]
## Steps to reproduce

clone a clean repo with no restored projects

```
dotnet restore src
cd test/dotnet-compile.UnitTests
dotnet test
```
## Expected  behavior

Runs Test
## Actual behavior

```
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.
CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```
## Environment data

`dotnet --info` output:
Seeing this everywhere.

```
/opt/code/cli/test/dotnet-compil
e.UnitTests# dotnet --info
.NET Command Line Tools (1.0.0-beta-002184)

Product Information:
 Version:     1.0.0-beta-002184
 Commit Sha:  9f23b7adf5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
root@0fe3e765b619:/opt/code/cli/test/dotnet-compil
e.UnitTests#
```

cc @anurse @pakrym @piotrpMSFT 

What does the `--infer-runtime` switch actually do and how can i reason about it? 

I think we can fix this by changing the ProjectDependenciesResolver to not rely on a rid in the project context.

**Comment by pakrym** [comment]
Not a bug, for standalone projects you either need to have rid list in `project.json` or restore with `--infer-runtime` to tell `nuget` to restore for current runtimes.

**Comment by hal-ler** [comment]
Is `--infer-runtimes` supported long-term, or just temporarily? I would prefer not to have all runtimes listed in the `project.json` of all the test projects.

**Comment by GuardRex** [comment]
and ...

> or restore with `--infer-runtimes` to tell nuget to restore for current runtimes.

... but what are the "current runtimes" if they are not specified in `project.json`?

**Comment by blackdwarf** [comment]
@brthor is this still an issue?
