### ISSUE TITLE
dotnet-compile-fsc template needs imports

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2213]
This error is output otherwise:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.DotNet.Cli.Utils.DepsJsonCommandResolver.LoadDependencyContextFromFile(String depsJsonFile)
   at Microsoft.DotNet.Tools.Compiler.Fsc.CompileFscCommand.ResolveFsc(List`1 fscArgs, String temp)
   at Microsoft.DotNet.Tools.Compiler.Fsc.CompileFscCommand.Main(String[] args)
/usr/share/dotnet/dotnet compile-fsc @/opt/code/hef/obj/Debug/netstandard1.5/dotnet-compile.rsp returned Exit Code 134

Compilation failed.
```

**Comment by mmalolepszy** [comment]
@brthor I'm facing exactly the same error, but replacing my project.json with one from your PR didn't help.

**Comment by brthor** [comment]
@mmalolepszy 

Try this out, then try again with imports:
```
rm -r ~/.nuget/packages/dotnet-compile-fsc
rm -r ~/.nuget/packages/.tools/dotnet-compile-fsc
```

**Comment by mmalolepszy** [comment]
@brthor Cleaning packages and nuget cache helped. Thanks.
