### ISSUE TITLE
ubuntu sdk's csc throws FileVersionInfo exception

### ISSUE THREAD

**Issue by ctaggart** [dotnet/cli#2221]
## Steps to reproduce

```
root@fdc45e826de4:/# echo $sdk
/usr/share/dotnet/sdk/1.0.0-beta-002199
root@fdc45e826de4:/# $sdk/corehost $sdk/csc.dll

Unhandled Exception: System.TypeInitializationException: The type initializer for 'FileVersionInfo' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Roslyn.Utilities.PortableShim.FileVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
Aborted (core dumped)
```
## Environment data

I setup the Docker image like so:

```
docker run --rm -ti ubuntu:trusty

apt-get --no-install-recommends install -y curl ca-certificates
curl http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
apt-get update

curl -O https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
curl -O https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
curl -O https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sdk-ubuntu-x64.latest.deb

dpkg -i dotnet-host-ubuntu-x64.latest.deb
dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb
apt-get --no-install-recommends -f install -y
dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb
dpkg -i dotnet-sdk-ubuntu-x64.latest.deb
apt-get --no-install-recommends -f install -y
dpkg -i dotnet-sdk-ubuntu-x64.latest.deb

shared=/usr/share/dotnet/shared
sdk=/usr/share/dotnet/sdk/$(ls /usr/share/dotnet/sdk)
ln -s $shared $sdk/shared
```

**Comment by ctaggart** [comment]
I'm able to reproduce the problem using `dotnet-dev-ubuntu-x64.latest.tar.gz` as well.
```
root@e311962a6505:/# mkdir -p /usr/share/dotnet
root@e311962a6505:/# tar xf dotnet-dev-ubuntu-x64.latest.tar.gz -C /usr/share/dotnet
root@e311962a6505:/# shared=/usr/share/dotnet/shared
root@e311962a6505:/# sdk=/usr/share/dotnet/sdk/$(ls /usr/share/dotnet/sdk)
root@e311962a6505:/# echo $sdk
/usr/share/dotnet/sdk/1.0.0-beta-002200
root@e311962a6505:/# $sdk/corehost $sdk/csc.dll 
Could not load host policy library [/usr/share/dotnet/sdk/1.0.0-beta-002200/shared/Microsoft.NETCore.App/1.0.0-rc2-23931]
root@e311962a6505:/# ln -s $shared $sdk/shared
root@e311962a6505:/# $sdk/corehost $sdk/csc.dll
corehost: lttng-ust-comm.c:1446: lttng_ust_init: Assertion `!ret' failed.
Aborted (core dumped)
root@e311962a6505:/# $sdk/corehost $sdk/csc.dll

Unhandled Exception: System.TypeInitializationException: The type initializer for 'FileVersionInfo' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Roslyn.Utilities.PortableShim.FileVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
Aborted (core dumped)
```

To setup the docker container, I did:
```
docker run --rm -ti ubuntu:trusty

apt-get --no-install-recommends install -y curl ca-certificates
curl http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
apt-get update

apt-get --no-install-recommends install -y libcurl3 libgssapi-krb5-2 libicu52 liblldb-3.6 liblttng-ust0 libunwind8

curl -O https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-dev-ubuntu-x64.latest.tar.gz
```

**Comment by ctaggart** [comment]
This is still happening with the latest build, 1.0.0-beta-002266. Any ideas?

root@63dd78325fcc:/# echo $sdk
/usr/share/dotnet/sdk/1.0.0-beta-002266
root@63dd78325fcc:/# $sdk/corehost $sdk/csc.dll

Unhandled Exception: System.TypeInitializationException: The type initializer for 'FileVersionInfo' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Roslyn.Utilities.PortableShim.FileVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
Aborted

**Comment by blackdwarf** [comment]
@ctaggart is this still reproing with the latest tooling?

**Comment by ctaggart** [comment]
Yes, still erroring with 1.0.0-preview2-sdk. Here are the steps to reproduce:

```
docker run --rm -it microsoft/dotnet:1.0.0-preview2-sdk
sdk=/usr/share/dotnet/sdk/$(ls /usr/share/dotnet/sdk)
ln -s /usr/share/dotnet/shared $sdk/shared
$sdk/corehost $sdk/csc.dll
```

Here is the output:
```
cameron@echo:~$ docker run --rm -it microsoft/dotnet:1.0.0-preview2-sdk
root@c7bcdecdaf7a:/# sdk=/usr/share/dotnet/sdk/$(ls /usr/share/dotnet/sdk)
root@c7bcdecdaf7a:/# ln -s /usr/share/dotnet/shared $sdk/shared
root@c7bcdecdaf7a:/# $sdk/corehost $sdk/csc.dll

Unhandled Exception: System.IO.FileNotFoundException: /usr/share/dotnet/sdk/1.0.0-preview2-003121/Microsoft.CodeAnalysis.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CommonCompiler.GetAssemblyFileVersion()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Boolean utf8Output, TextWriter textWriter, Func`2 func)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
Aborted (core dumped)
root@c7bcdecdaf7a:/#
```

**Comment by piotrpMSFT** [comment]
The sub-components of CLI are not intended to be addressed directly. If you want to invoke CSC please do so via `dotnet build`.
