### ISSUE TITLE
Triage question on this System.ArgumentNullException

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2222]
@blackdwarf  --- Triage question on this one. Here? ... or Mvc repo?
## Exception
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: assemblyName
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at www_guardrex_com.Program.Main(String[] args)
```
## Environment data
```
.NET Command Line Tools (1.0.0-beta-002198)

Product Information:
 Version:     1.0.0-beta-002198
 Commit Sha:  813049dabe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by Petermarcu** [comment]
Looks like mvc to me...

**Comment by GuardRex** [comment]
Moved to https://github.com/aspnet/Mvc/issues/4399
