### ISSUE TITLE
dotnet build doesn't correctly handle special chars in project paths

### ISSUE THREAD

**Issue by PinpointTownes** [dotnet/cli#2230]
## Steps to reproduce

Create a new folder containing accents/special chars (e.g `I love special chars - éèàôöç`)
Run `dotnet new` to initialize a new project.
Run `dotnet restore`.
Run `dotnet run`.

## Expected  behavior

```
Hello World!
```

## Actual behavior

```
PS G:\I love special chars - éèàôöç> dotnet new
Created new C# project in G:\I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§.

PS G:\I love special chars - éèàôöç> dotnet restore
log  : Restoring packages for G:\I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§\project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: G:\I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§\project.lock.json
log  : G:\I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§\project.json
log  : Restore completed in 1395ms.

NuGet Config files used:
    G:\I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§\NuGet.Config
    C:\Users\Chalet KÃ©vin\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json

PS G:\I love special chars - éèàôöç> dotnet run
Compiling I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§ for .NETStandard,Version=v1.5
dotnet : Response file 'G:\I love special chars - ÃƒÂ©ÃƒÂ¨ÃƒÂ ÃƒÂ´ÃƒÂ¶ÃƒÂ§\obj\Debug\netstandard1.5\dotnet-compile.rsp' doesn't exist.
At line:1 char:1
+ dotnet build
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Response file '... doesn't exist.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Program Files\dotnet\dotnet.exe compile-csc "@G:\I love special chars - Ã©Ã¨Ã Ã´Ã¶Ã§\obj\Debug\netstandard1.5\dotnet-compile.rsp" returned Exit Code 1

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.1348554
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by PinpointTownes** [comment]
Hum, looks like this repo needs a serious effort on triage... :trollface:

**Comment by PinpointTownes** [comment]
**Really, why isn't this ticket labelled with the "bug" flag?**

This is literally making .NET CLI crash for every user having a special char in his session folder. It even makes Omnisharp for VS Code choke when it comes to download and install the .NET Core debugger:

```
Error: Access to the path 'C:\Users\Chalet KÃ©vin\.vscode\extensions\omnisharp\coreclr-debug\debugAdapters' is denied.
Error: 

System.UnauthorizedAccessException: Access to the path 'C:\Users\Chalet KÃ©vin\.vscode\extensions\omnisharp\coreclr-debug\debugAdapters' is denied.
   at System.IO.Win32FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishProjectContext(ProjectContext context, String buildBasePath, String outputPath, String configuration, Boolean nativeSubdirectories)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishAllProjects()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
```

**Comment by brthor** [comment]
@PinpointTownes 

https://github.com/dotnet/cli/issues/2486

Is tracking fixing this for rc2

**Comment by PinpointTownes** [comment]
Wonderful, thanks! :clap:

**Comment by PinpointTownes** [comment]
Closing, since https://github.com/dotnet/cli/issues/2486 is already triaged (even if this thread is older :smile:).
