### ISSUE TITLE
dotnet-test fails to find system when portable-net45+win8 is before dnxcore50 in the imports statement

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#2262]
## Steps to reproduce
Create a simple test project and have your project json like below. Note the portable import before dnxcore50.

```
{
    "version": "1.0.0-*",
    "dependencies": {
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0-rc2-23931"
        },
        "xunit": "2.1.0",
        "dotnet-test-xunit": "1.0.0-*"
    },
    "frameworks": {
       "netstandardapp1.5": {
           "imports": [ 
                "portable-net45+win8",
                "dnxcore50"
           ]
        }
    },
    "testRunner": "xunit"
}
```
do a dotnet restore --infer-runtimes
do a dotnet test

## Expected  behavior
Tests run successfully

## Actual behavior
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
Closing this one in favor of this https://github.com/NuGet/Home/issues/2453.
