### ISSUE TITLE
dotnet-test does not find dotnet-test-xunit executable

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#2278]
## Steps to reproduce

``` json
{
    "version": "1.0.0-*",
    "dependencies": {
        "System.Data.SqlClient": "4.1.0-rc2-23931",
        "xunit": "2.1.0"
    },
    "frameworks": {
        "netstandardapp1.5": {
            "dependencies": {
                "dotnet-test-xunit": "1.0.0-dev-128011-22",
                "NETStandard.Library": "1.5.0-rc2-23931"
            },
            "imports": [
                "dnxcore50",
                "portable-net451+win8"
            ]
        }
    },
    "testRunner": "xunit"
}
```

``` c#
using Xunit;

namespace ConsoleApplication
{
    public class Test
    {
        [Fact]
        public void ShouldFail()
        {
            Assert.True(false);
        }
    }
}
```

Attached full repro project and lock file.
[sni-test.zip](https://github.com/dotnet/cli/files/204959/sni-test.zip)

`dotnet restore`
`dotnet test`
## Expected  behavior

Execute the one test in the project.
## Actual behavior

```
Compiling sni-test for .NETStandardApp,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.2853214


dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

Happens on osx.10.11-x64 too.

This seems odd. Am I missing something obvious?

**Comment by piotrpMSFT** [comment]
restore with --infer-runtimes to get unblocked. @livarcocc was taking a look into root caus.

**Comment by natemcmaster** [comment]
Aha. So, is there going to be a warning when cli/nuget aretrying to produce a standalone app and no runtimes are specified?

**Comment by piotrpMSFT** [comment]
The standalone app story is in need of a terrible amount of love before rtm.

**Comment by natemcmaster** [comment]
@piotrpMSFT this reproduces in portable apps too, by the way.

**Comment by piotrpMSFT** [comment]
Livar took a look today. Looks like we will need to make a breaking change in dotnet test to fix this. Will do post-RC.

**Comment by chrizy** [comment]
Is there an update to when this will be fixed?
Thanks

**Comment by jaredcnance** [comment]
I'm having the same issue for net451 when I specify net451 and netcoreapp frameworks. 

`dotnet restore --infer-runtimes` has no effect.

```
{
  "version": "1.0.0-alpha",
  "testRunner": "xunit",
  "dependencies": {
    "MyApp": "0.1.0",
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "xunit": "2.2.0-beta2-build3300"
  },
  "frameworks": {
    "net451": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1"
      }
    },
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      }
    }
  },
  "buildOptions": {
    "copyToOutput": {
      "include": [
        "xunit.runner.json"
      ]
    }
  }
}
```

With output:

```
Compiling MyAppTests for .NETCoreApp,Version=v1.0

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.4300915

Unit.net .NET CLI test runner (64-bit .NET Core osx.10.11-x64)
  Discovering: MyAppTests
  Discovered:  MyAppTests
  Starting:    MyAppTests
  Finished:    MyAppTests
=== TEST EXECUTION SUMMARY ===
   MyAppTests  Total: 13, Errors: 0, Failed: 0, Skipped: 0, Time: 0.578s

Compiling MyAppTests for .NETFramework,Version=v4.5.1

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.4428625

No executable found matching command "dotnet-test-xunit"
```

**Comment by piotrpMSFT** [comment]
since `dotnet test` was reimplemented as a wrapper on vstest.console, this approach to finding test runners is no longer in existence. Closing the issue.
