### ISSUE TITLE
Package names should not be case-sensitive

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#236]
DNX treats package names as case-sensitive but NuGet does not. E.g. using "Microsoft.NetCore.Platforms" instead of "Microsoft.NETCore.Platforms" can crash restore. This is evident when running `dotnet restore` on the following project json on darwin/linux. 
```json
{
	"frameworks": {
		"dnxcore50": {
			"dependencies": {
				"Microsoft.NetCore.Platforms": "1.0.1-*",
				"System.Console": "4.0.0-*"
			}
		}
	}
}
```

Error:
```
System.ArgumentException: More than one runtime.json file has declared imports for 'osx.10.11-x64'
Parameter name: runtimeName
   at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2 effectiveRuntimeSpecs, HashSet`1 allRuntimeNames, Func`2 circularImport)
   at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2 effectiveRuntimeSpecs, HashSet`1 allRuntimeNames)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
```

This can also lead to other build errors (See https://github.com/aspnet/EntityFramework/issues/3779 for example)

**Comment by natemcmaster** [comment]
cc @anurse @ericstj

**Comment by anurse** [comment]
Technically this code is moving to NuGet, but we can track this here for now. `dotnet restore` (if it exists) in the final product will be a shim around `nuget`. Currently, it is a shim around `dnu restore`, which means it has the same issues.

**Comment by piotrpMSFT** [comment]
We've moved to NuGet crossplat client. If you still see repros, please reopen!
