### ISSUE TITLE
Exception during dotnet build: error : Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\antonpis\.nuget\packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-rc2-20466\netstandardapp1.5\Microsoft.AspNetCore.Server.IISIntegration.Tools.deps.json' because it is being used by another process.

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2374]
## Steps to reproduce

I can not repro it manually, it is one of our integration tests that randomly fails. It creates 8 new projects one after another, waits for restores and builds. Sometimes we see this exception below and test fails. Note: tooling does not even know about that file that is being used by another process, so it is in cli.

```
1>------ Build started: Project: Project1, Configuration: Debug Any CPU ------
2>------ Build started: Project: Project2, Configuration: Debug Any CPU ------
3>------ Build started: Project: Project3, Configuration: Debug Any CPU ------
4>------ Build started: Project: Project4, Configuration: Debug Any CPU ------
5>------ Build started: Project: Project5, Configuration: Debug Any CPU ------
6>------ Build started: Project: Project6, Configuration: Debug Any CPU ------
7>------ Build started: Project: Project7, Configuration: Debug Any CPU ------
8>------ Build started: Project: Project8, Configuration: Debug Any CPU ------
6>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\junk\Project6" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
7>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Src\Sub\Project7" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
1>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Project1" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
3>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Src\Project3" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
2>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Project2" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
4>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Project4" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
5>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Src\Sub\Project5" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
8>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\Src\Sub\Sub2\Project8" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts"
6>  Compiling Project6 for .NETStandardApp,Version=v1.5
1>  Compiling Project1 for .NETStandardApp,Version=v1.5
4>  Compiling Project4 for .NETStandard,Version=v1.5
7>  Compiling Project7 for .NETCoreApp,Version=v1.0
2>  Compiling Project2 for .NETStandardApp,Version=v1.5
3>  Compiling Project3 for .NETCoreApp,Version=v1.0
5>  Compiling Project5 for .NETStandardApp,Version=v1.5
8>  Compiling Project8 for .NETCoreApp,Version=v1.0
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error : Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\antonpis\.nuget\packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-rc2-20466\netstandardapp1.5\Microsoft.AspNetCore.Server.IISIntegration.Tools.deps.json' because it is being used by another process.
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.EnsureToolJsonDepsFileExists(LibraryRange toolLibrary, LockFile toolLockFile, String depsPath)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolDepsFilePath(LibraryRange toolLibrary, LockFile toolLockFile, String depsPathRoot)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(LibraryRange toolLibraryRange, String commandName, IEnumerable`1 args, ProjectContext projectContext)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, ProjectContext projectContext)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(String commandName, IEnumerable`1 args, String projectDirectory)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Tools.Compiler.Csc.CompileCscCommand.RunCsc(String[] cscArgs)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Tools.Compiler.Csc.CompileCscCommand.Run(String[] args)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error :    at Microsoft.DotNet.Cli.Program.Main(String[] args)
7>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(240,5): error : C:\Program Files\dotnet\dotnet.exe compile-csc "@D:\dd\WTE\Release\TestResults\Deploy_antonpis 2016-04-08 11_00_14\Out\sln1\artifacts\Project7\obj\Debug\netcoreapp1.0\dotnet-compile.rsp" returned Exit Code -532462766
7>  Compilation failed.
7>      0 Warning(s)
7>      0 Error(s)
7>  Time elapsed 00:00:04.1173024
6>  Compilation succeeded.
6>      0 Warning(s)
6>      0 Error(s)
6>  Time elapsed 00:00:07.6049864
1>  Compilation succeeded.
1>      0 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:00:07.5626404
4>  Compilation succeeded.
4>      0 Warning(s)
4>      0 Error(s)
4>  Time elapsed 00:00:07.5410569
6>
1>
2>  Compilation succeeded.
2>      0 Warning(s)
2>      0 Error(s)
2>  Time elapsed 00:00:07.4296353
4>
2>
5>  Compilation succeeded.
5>      0 Warning(s)
5>      0 Error(s)
5>  Time elapsed 00:00:07.5964018
5>
3>  Compilation succeeded.
3>      0 Warning(s)
3>      0 Error(s)
3>  Time elapsed 00:00:08.5320992
3>
8>  Compilation succeeded.
8>      0 Warning(s)
8>      0 Error(s)
8>  Time elapsed 00:00:08.0902900
8>
========== Build: 7 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

## Expected  behavior

No exceptions

## Environment data
`dotnet --info` output:

D:\dd\WTE\Release\src\ProjectSystem>dotnet --info
.NET Command Line Tools (1.0.0-beta-002275)

Product Information:
 Version:     1.0.0-beta-002275
 Commit Sha:  4af7437aa6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by cdmihai** [comment]
The exception is thrown from somewhere inside this method call: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolution/ProjectToolsCommandResolver.cs#L198

There's a good likelihood of a check then act race here. Two processes pass the !File.Exists(depsPath) check, then both want to write the deps file.

@abpiskunov: The calls to dotnet build are happening in parallel right (log suggests they're in parallel)? This would cause a race in the nuget cache over the deps file. 

It looks strange that the CLI wants to write extra data inside the nuget cache though. That method was added in this commit: https://github.com/dotnet/cli/commit/f0c2cb2c1806b8c699352d0a15fbdf45672dbf07
@brthor, any ideas how to avoid this race? Does the deps file need to remain there (if not, can you compute whatever is necessary from the deps file in memory / generate the deps in memory)? Can the writing of the deps file happen after restore, rather than just in time?

**Comment by brthor** [comment]
@cdmihai 
This is exactly the cause we are thinking. 

The deps file is a necessary artifact for the host to consume so in-memory is not an easy task.

Keep in mind that this is a specific directory for the project tools (`.tools`) and not the general purpose nuget cache.

One way we can go about this is to minimize the opportunity for a race condition and detect the rare chance of it happening to continue gracefully. 

@piotrpMSFT suggested writing to a temp file, renaming it to the depsJson file, and catching on the rename. If the rename fails, it's generally safe to continue.

**Comment by brthor** [comment]
#2387

**Comment by brthor** [comment]
I have reproed this against rel on Windows and am unable to repro it against #2387.
