### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by powerhai** [dotnet/cli#2393]
## Steps to reproduce
Run command:  dotnet ef migrations add FirstMigration
## Actual behavior

```
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ICollection`1 diagnostics, ProjectReaderSettings settings)
   at Microsoft.EntityFrameworkCore.Commands.ReflectionOperationExecutor.GetCompatibleProjectContext(String projectPath)
   at Microsoft.EntityFrameworkCore.Commands.ReflectionOperationExecutor..ctor(String startupProject, String environment)
   at Microsoft.EntityFrameworkCore.Commands.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Commands.Program.Main(String[] args)
Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002339)

Product Information:
 Version:     1.0.0-rc2-002339
 Commit Sha:  2be5e84f87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by renatohh** [comment]
same issue here, on windows 10

**Comment by gtbull80** [comment]
anyone have any luck with this?

**Comment by livarcocc** [comment]
This tool is actually developed at this repo: https://github.com/aspnet/EntityFramework.

Please open this bug there, you will get more traction.
