### ISSUE TITLE
[dotnet build] null exception during build when no packages are resolved

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2397]
## Steps to reproduce

- create a new web app (you need to simulate a situation when no dependency packages can be resolved, disable all nuget feeds or something like that
(for me it is happeneing since this is the state when i use latest tooling, there is some mismatch with packages at the moment)

- build after restore failed

## Expected  behavior

lots of build errors , since dependencies/references are missing

## Actual behavior

```
1>------ Build started: Project: App1, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1" --configuration Debug --no-dependencies --build-base-path "D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\artifacts"
1>  Compiling App1 for .NETCoreApp,Version=v1.0
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : **Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.ToolPathCalculator.GetLockFilePath(String packageId, NuGetVersion version, NuGetFramework framework)**
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFilePath(LibraryRange toolLibrary, String nugetPackagesRoot)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFile(LibraryRange toolLibrary, String nugetPackagesRoot)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(LibraryRange toolLibraryRange, String commandName, IEnumerable`1 args, ProjectContext projectContext)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, ProjectContext projectContext)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(String commandName, IEnumerable`1 args, String projectDirectory)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Tools.Compiler.Csc.CompileCscCommand.RunCsc(String[] cscArgs)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Tools.Compiler.Csc.CompileCscCommand.Run(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error :    at Microsoft.DotNet.Cli.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : C:\Program Files\dotnet\dotnet.exe compile-csc "@D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\artifacts\src\App1\obj\Debug\netcoreapp1.0\dotnet-compile.rsp" returned Exit Code -1073741819
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(8,58): error NU1001: The dependency Microsoft.AspNetCore.Diagnostics >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(9,50): error NU1001: The dependency Microsoft.AspNetCore.Mvc >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(10,61): error NU1001: The dependency Microsoft.AspNetCore.Mvc.TagHelpers >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(11,68): error NU1001: The dependency Microsoft.AspNetCore.Server.IISIntegration >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(12,61): error NU1001: The dependency Microsoft.AspNetCore.Server.Kestrel >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(13,58): error NU1001: The dependency Microsoft.AspNetCore.StaticFiles >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(14,75): error NU1001: The dependency Microsoft.Extensions.Configuration.FileExtensions >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(15,65): error NU1001: The dependency Microsoft.Extensions.Configuration.Json >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(16,54): error NU1001: The dependency Microsoft.Extensions.Logging >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(17,62): error NU1001: The dependency Microsoft.Extensions.Logging.Console >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(18,60): error NU1001: The dependency Microsoft.Extensions.Logging.Debug >= 1.0.0-rc2-20507 could not be resolved.
1>D:\dd\WTE\Release\TestResults\Deploy_asplab 2016-04-11 06_07_37\Out\App1\src\App1\project.json(23,72): error NU1001: The dependency Microsoft.VisualStudio.Web.BrowserLink.Loader >= 14.0.0-rc2-20507 could not be resolved.
1>  Compilation failed.
1>      0 Warning(s)
1>      12 Error(s)
1>  Time elapsed 00:00:01.3271302
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

## Environment data
`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-beta-002275)

Product Information:
 Version:     1.0.0-beta-002275
 Commit Sha:  4af7437aa6

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by piotrpMSFT** [comment]
@krwq can you take a look?

**Comment by krwq** [comment]
I was able to repro this with following when:
1. dotnet restore a project with a tool which exists but its version does not (i.e. change version from 1.0.0 to 1.0.1 in your project.json)
2. dotnet build

**Comment by abpiskunov** [comment]
oh cool, thanks @krwq!

**Comment by Petermarcu** [comment]
@abpiskunov can you comment on what is truly blocked if we don't get this for RC2?

**Comment by abpiskunov** [comment]
Well, looking at 2 repros , which are slightly different, it can repro when there are some unresolved packages or tools and user tries to build solution. Visible enough?

**Comment by piotrpMSFT** [comment]
The happy path works, and we need to work on fit-n-finish to improve the UX when missing/bad packages are referenced. Let's tackle this in rtm.

**Comment by piotrpMSFT** [comment]
@krwq this was discussed at shiproom and pulled in for RC2. Please priorotize fixing the nullref. If the nullref is in NuGet please open an issue in https://github.com/nuget/home.

**Comment by piotrpMSFT** [comment]
@krwq will have a fix tomorrow.
