### ISSUE TITLE
NRE when resolving a tool 

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2507]
## Steps to reproduce

The tool was restored into this location: `C:\Users\pawelka\.nuget\packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-rc2-20568\netstandardapp1.5\project.lock.json`

However the path calculator came up with this path: 
`C:\Users\pawelka\.nuget\packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-rc2-20568\netcoreapp1.0\project.lock.json`

(notice the difference in the name of the framework `netstandardapp1.5` vs. `netcoreapp1.0`). 

The tool is in the transition state an the older package that is public still have `netstandardapp1.5`. 
As a result [`GetToolLockFile`](https://github.com/dotnet/cli/blob/2956446864d668f0821ea89620566c32f15c0d38/src/Microsoft.DotNet.Cli.Utils/CommandResolution/ProjectToolsCommandResolver.cs#L138 ) returns null  which is not checked [here](https://github.com/dotnet/cli/blob/2956446864d668f0821ea89620566c32f15c0d38/src/Microsoft.DotNet.Cli.Utils/CommandResolution/ProjectToolsCommandResolver.cs#L107) hence the exception

This might seem like a corner case but I think the same will happen if someone puts a standalone app as a tool. 

## Expected  behavior
An error message. 

## Actual behavior

```
PS C:\Source\cli-samples\HelloMvc> ..\..\cli\artifacts\win10-x64\stage2\dotnet.exe publish-iis

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(LibraryRange toolLibraryRange, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(String commandName, IEnumerable`1 args, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

https://github.com/dotnet/cli/tree/2956446864d668f0821ea89620566c32f15c0d38

**Comment by brthor** [comment]
Seems like converting the tool to netcoreapp1.0 would be the ideal fix. 

This is a result of a breaking change in https://github.com/dotnet/cli/commit/2956446864d668f0821ea89620566c32f15c0d38 (cc @anurse )

Seeing as we won't support netstandardapp1.5 in the future, converting is probably the best fix.

**Comment by moozzyk** [comment]
Actually netstandardapp1.5 folder was created because I restored using the dotnet version that did not have this change https://github.com/NuGet/NuGet.Client/commit/9573f19ce94c84078e0d0e4f128bb24de7bfe140#diff-8c917f3b4e6bc57dc2667ae784dbb4b3R16

Once I restored using the latest I built myself netstandardapp1.5 is no longer created and things work. 

If you don't think there are any other scenarios where this can happen it's fine to close this.
