### ISSUE TITLE
Typo in TFM gives Microsoft.CSharp error

### ISSUE THREAD

**Issue by Ciantic** [dotnet/cli#2552]
Put this in the project.json:

```
{
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Microsoft.AspNetCore.Mvc.Core": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.DataAnnotations": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*"
    },
    "frameworks": {
        "net999": {}                                 <-- Offending Line
    },
    "runtimes": {
        "win81-x64": {}
    },
    "version": "1.0.0"
}
```

NuGet.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

Startup.cs
```C#
using System.Reflection;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace TestApp
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore();
        }
        
        public void Configure(IApplicationBuilder app)
        {
            app.UseMvcWithDefaultRoute();
        }
		
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                        .UseKestrel()
                        .UseDefaultHostingConfiguration(args)
                        .UseStartup<Startup>()
                        .Build();

            host.Run();
        }
    }
}
```

```
dotnet restore
dotnet run
An item with the same key has already been added. Key: Microsoft.CSharp
```

So if you use e.g. net462 without having it, dotnet gives the above non-descriptive error.

```
dotnet --version
1.0.0-rc2-002416
```

**Comment by Ciantic** [comment]
@piotrpMSFT this is not *just* "net999" it also requires that there is dependency: `"Microsoft.AspNetCore.Mvc.DataAnnotations": "1.0.0-*",` otherwise you get different error.

**Comment by davidfowl** [comment]
I can repro.

**Comment by davidfowl** [comment]
This isn't RTM, needs to be fixed in RC2

**Comment by davidfowl** [comment]
Here's the stack:

```
Davids-MacBook-Pro:basic-cli dfowler$ ../cli/artifacts/osx.10.11-x64/stage2/dotnet run
System.ArgumentException: An item with the same key has already been added. Key: Microsoft.CSharp
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Tools.Build.ProjectDependenciesFacade.GetProjectDependencies(ProjectContext projectContext, String configuration)
   at Microsoft.DotNet.Tools.Build.ProjectDependenciesFacade..ctor(ProjectContext rootProject, String configValue)
   at Microsoft.DotNet.Tools.Build.CompileContext..ctor(ProjectContext rootProject, BuilderCommandApp args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.<>c__DisplayClass1_0.<OnExecute>b__0(ProjectContext context)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Microsoft.DotNet.Tools.Build.BuildCommand.OnExecute(List`1 contexts, CompilerCommandApp args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.<>c__DisplayClass75_1.<Execute>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.Execute(OnExecute execute, String[] args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
```

**Comment by davidfowl** [comment]
Minimal repro:

```JSON
{
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Microsoft.CSharp": "4.0.1-rc2-24018"
    },
    "frameworks": {
        "net46": {}
    },
    "version": "1.0.0"
}
```

**Comment by piotrpMSFT** [comment]
@davidfowl does #2597 close this issue?

**Comment by davidfowl** [comment]
Yes
