### ISSUE TITLE
Duplicate keys (Microsoft.CSharp) cause ProjectModel server error.

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#2602]
## Steps to reproduce
1. Restore MusicStore (https://github.com/aspnet/musicstore)
2. Start project model server and try get dependencies information for it

## Expected  behavior
No error

## Actual behavior
```
fail: Microsoft.DotNet.ProjectModel.Server.ProjectManager[0]
      A unexpected exception occurred: System.ArgumentException: An item with the same key has already been added. Key: Microsoft.CSharp
         at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
         at Microsoft.DotNet.ProjectModel.Server.ProjectContextSnapshot.Create(ProjectContext context, String configuration, IEnumerable`1 currentSearchPaths)
         at Microsoft.DotNet.ProjectModel.Server.ProjectSnapshot.Create(String projectDirectory, String configuration, WorkspaceContext workspaceContext, IReadOnlyList`1 projectSearchPaths)
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.UpdateProject()
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.DoProcessLoop()
         at Microsoft.DotNet.ProjectModel.Server.ProjectManager.ProcessLoop()
Error => {
  "Message": "An item with the same key has already been added. Key: Microsoft.CSharp",
  "Path": null,
  "Line": 0,
  "Column": 0
}
```

## Environment data
`dotnet --info` output:

@BillHiebert ?

**Comment by troydai** [comment]
@piotrpMSFT this is partner block and rc2 issue.
@BillHiebert from WTE team reported this
@davidfowl has a PR related to this #2597

**Comment by troydai** [comment]
I file this issue for @BillHiebert. I can repo the issue with the lock file provided by @BillHiebert : https://github.com/dotnet/cli/tree/03eb1bb895c9194bd847fc8e5c57ddfb5927ad13/TestAssets/ProjectModelServer/MusicStoreError

However I can't recreate a similar lock file using latest dotnet to repo this issue.

**Comment by troydai** [comment]
@BillHiebert can you try this scenario on latest dotnet again? I'm not able to repo it now.

**Comment by troydai** [comment]
Close as not repo. @BillHiebert please feel free to reopen if you can repo this on newer packages.
