### ISSUE TITLE
Q:How to publish app/site to azure?

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#2627]
In IDE, I got the following error:
The project being published does not support the runtime 'dnx-clr-win-x86.1.0.0-rc2-20221'
   at Microsoft.DNX.Tasks.Dnu.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by piotrpMSFT** [comment]
@xatabhk it looks like you're using DNX tools. Tools for CLI are not available yet but will be soon.
