### ISSUE TITLE
Unix builds are failing to publish the new sharedfx+cli zip

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2698]
All the unix builds are failing to publish the new sharedfx+cli zip with the below exception

>
2016-04-26T18:38:56.107Z: Build failed: System.AggregateException: One or more errors occurred. (Could not find file '/opt/code/artifacts/ubuntu.14.04-x64/packages/dotnet-sharedframework-sdk-ubuntu-x64.1.0.0-rc2-002500.tar.gz'.) ---> System.IO.FileNotFoundException: Could not find file '/opt/code/artifacts/ubuntu.14.04-x64/packages/dotnet-sharedframework-sdk-ubuntu-x64.1.0.0-rc2-002500.tar.gz'.
2016-04-26T18:38:56.107Z:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2016-04-26T18:38:56.108Z: afeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
2016-04-26T18:38:56.108Z:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2016-04-26T18:38:56.108Z:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
2016-04-26T18:38:56.108Z:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
2016-04-26T18:38:56.108Z:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2016-04-26T18:38:56.108Z:    at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass23_0.<<UploadFromFileAsync>b__0>d.MoveNext()
2016-04-26T18:38:56.108Z:    --- End of inner exception stack trace ---
2016-04-26T18:38:56.108Z:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2016-04-26T18:38:56.108Z:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2016-04-26T18:38:56.108Z: sks.Task.Wait()
2016-04-26T18:38:56.108Z:    at Microsoft.DotNet.Cli.Build.AzurePublisher.PublishFile(String blob, String file)
2016-04-26T18:38:56.109Z:    at Microsoft.DotNet.Cli.Build.AzurePublisher.PublishArchiveAndLatest(String archiveFile, String channel, String version)
2016-04-26T18:38:56.109Z:    at Microsoft.DotNet.Cli.Build.PublishTargets.PublishCombinedFrameworkSDKArchiveToAzure(BuildTargetContext c)
2016-04-26T18:38:56.109Z:    at Microsoft.DotNet.Cli.Build.Framework.BuildContext.ExecTarget(BuildTarget target)
2016-04-26T18:38:56.109Z: ---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file '/opt/code/artifacts/ubuntu.14.04-x64/packages/dotnet-sharedframework-sdk-ubuntu-x64.1.0.0-rc2-002500.tar.gz'.
2016-04-26T18:38:56.109Z: File name: '/opt/code/artifacts/ubuntu.14.04-x64/packages/dotnet-sharedframework-sdk-ubuntu-x64.1.0.0-rc2-002500.tar.gz'
2016-04-26T18:38:56.109Z:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2016-04-26T18:38:56.109Z:    at Interop.CheckIoafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
2016-04-26T18:38:56.109Z:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2016-04-26T18:38:56.109Z:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
2016-04-26T18:38:56.109Z:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
2016-04-26T18:38:56.109Z:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2016-04-26T18:38:56.109Z:    at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass23_0.<<UploadFromFileAsync>b__0>d.MoveNext()<---

**Comment by ellismg** [comment]
Fixed via #2699
