### ISSUE TITLE
Getting System.TypeInitializationException on OSX

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#2741]
I don't know how to reproduce this. On my machine, using either stage0 or stage1/2 gives me the following exception:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. 
---> System.PlatformNotSupportedException: Error reading Darwin Kernel Version 
---> System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Darwin.sysctl(Int32* name, UInt32 namelen, Byte* oldp, UInt32* oldlenp, IntPtr newp, UInt32 newlen)
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   at Microsoft.Extensions.PlatformAbstractions.Native.PlatformApis.GetDarwinVersion()
   at Microsoft.Extensions.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.Extensions.PlatformAbstractions.DefaultRuntimeEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.DefaultPlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Default()
   at Microsoft.DotNet.Cli.Telemetry..ctor()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6
```

```
uname -a
Darwin miac 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

OSX 10.11.4

**Comment by piotrpMSFT** [comment]
@cdmihai we've tried to repro this on a few machines and it doesn't show. Can you provide a stable repro?

**Comment by cdmihai** [comment]
Looked a bit more into this. Apparently everything is fine if I call dotnet from inside a script:

```
./.dotnet_stage0/Darwin/dotnet build src/dotnet
The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception.
```

```
./run.sh
Project Microsoft.DotNet.InternalAbstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.DependencyModel (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.DotNet.ProjectModel (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.DotNet.Cli.Utils (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.DotNet.Files (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.DotNet.Compiler.Common (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Testing.Abstractions (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project dotnet (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
```

where run.sh is
```
#!/bin/sh 
./.dotnet_stage0/Darwin/dotnet build src/dotnet
```

**Comment by cdmihai** [comment]
Problem solved. ...

I had the following three items in my ~/.bash_profile file:
```
export CPATH=/usr/include
export LIBRARY_PATH=$CPATH
export DYLD_FALLBACK_LIBRARY_PATH=$CPATH
```

After commenting those out, stuff works. No idea what tool wrote those lines there, I'll see if anything else starts breaking all of the sudden :)

**Comment by ballance** [comment]
I have this issue also.  @cdmihai's fix did not apply for me.

**Comment by cdmihai** [comment]
@ballance Look into your `~/.bash_profile` for anything odd, maybe relating to C libraries. The nuclear option would be to back it up and try a vanilla one.
