### ISSUE TITLE
Poor error handling on json misformatting

### ISSUE THREAD

**Issue by dannyvv** [dotnet/cli#275]
Repro:
1: Enlist in CLI (I'm at 20f5ba4a5)
2: Modify test\TestApp\Project.json
    change
        "System.IO": "4.0.11-beta-23428",
    to: 
        "System.IO": { version: "4.0.11-beta-23428" },
3. run build.cmd

Expected:
Error message in IDE parsable format:
```
.....\test\TestApp\Project.json(9, 42): error DNX004: Unexpected character v expected "
```

Encountered:
```
Restoring packages for E:\src\dotnet\cli\test\TestApp\project.json
E:\src\dotnet\cli\test\TestApp\project.json(9,24): Error: Microsoft.Dnx.Runtime.FileFormatException: Illegal character 'v' (Unicode hexadecimal 0076). ---> Microsoft.Extensions.JsonParser.Sources.JsonDeserializerException: Illegal character 'v' (Unicode hexadecimal 0076).
   at Microsoft.Extensions.JsonParser.Sources.JsonBuffer.Read()
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
   at Microsoft.Extensions.JsonParser.Sources.JsonDeserializer.Deserialize(TextReader reader)
   at Microsoft.Dnx.Runtime.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   --- End of inner exception stack trace ---
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Illegal character 'v' (Unicode hexadecimal 0076).
```

**Comment by piotrpMSFT** [comment]
Thanks @dannyvv. We'll take a look at improving this experience once core functionality is stable.

**Comment by piotrpMSFT** [comment]
I just verified and this is now fixed with a nice error message.

````
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002700"
    },
    "Microsoft.D
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
````

produces

````
error: Error reading '/Users/piotrp/code/repro/deps/project.json' at line 13 column 4 : Invalid character after parsing property name. Expected ':' but got: f. Path 'dependencies.['Microsoft.NETCore.App']', line 13, position 4.
````
