### ISSUE TITLE
PerfTrace CaptureTiming Graph Collection NRE

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#2765]
## Steps to reproduce

Run `<root>\artifacts\win10-x64\stage1\dotnet.exe --debug "build" "--build-base-path" "<root>\artifacts\win10-x64\stage2compilation\forPackaging" "--configuration" "Debug" "<root>\src\Microsoft.DotNet.ProjectModel.Loader"``

Where `<root>` is your repo root
## Expected  behavior

Success!
## Actual behavior

NRE 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tools.Build.ProjectGraphCollector.<Collect>d__3.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Build.BuildCommand.OnExecute(IEnumerable`1 files, IEnumerable`1 frameworks, BuildCommandApp args)
   at Microsoft.DotNet.Tools.Compiler.BuildCommandApp.<>c__DisplayClass57_0.<Execute>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.BuildCommandApp.Execute(OnExecute execute, String[] args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args, WorkspaceContext workspace)
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0)

Product Information:
 Version:     1.0.0
 Commit Sha:  19ec330c20

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment]
related?
https://github.com/dotnet/cli/commit/cf6fdc6daca187d938da08bb9db3278963ef9561

**Comment by Petermarcu** [comment]
Do we need this for RC2 or can this be RTM?

**Comment by brthor** [comment]
@sokket Is this a failure in our build or in our product? If we have an NRE in a common code path on the product, we might consider this for RC2, otherwise I think we should do this for RTM.

**Comment by sokket** [comment]
This looks to be a common path problem, I've hit this on multiple machines now

**Comment by brthor** [comment]
Do you think we should consider taking this for RC2?

**Comment by sokket** [comment]
I hit this all the time but it seems like nobody else does...so I'm not really sure. It isn't telemetry based since I looked at a really old version and it still hit then

**Comment by piotrpMSFT** [comment]
Closing. This was a bug in the PJ-based build command which is now removed.
