### ISSUE TITLE
Publishing net451 project with P2P references does not work - NullRefException

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2938]
## Steps to reproduce
1. Create a project that has a P2P reference to a net451 (e.g. use this: https://github.com/aspnet/cli-samples/commit/42bde3dcb47586567a175e3a6c30014821197b16)
2. Restore
3. Publish

## Expected  behavior
Publishing succeeds

## Actual behavior

```
PS C:\Source\cli-samples\HelloMvc> dotnet -v publish -f net451
Telemetry is: Enabled
Publishing HelloMvc for .NETFramework,Version=v4.5.1/win7-x64
Object reference not set to an instance of an object.
Published 0/1 projects successfully
```

## Environment data
`dotnet --info` output:

```
PS C:\Source\cli-samples\HelloMvc> dotnet --info
.NET Command Line Tools (1.0.0-rc2-002670)

Product Information:
 Version:     1.0.0-rc2-002670
 Commit Sha:  f0018642a9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by moozzyk** [comment]
I also see this:
```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -f net451
Collection was modified; enumeration operation may not execute.
PS C:\Source\cli-samples\HelloMvc> dotnet -v publish -f net451
Telemetry is: Enabled
Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
```

**Comment by brthor** [comment]
@moozzyk I'm not sure what the issue is here but I suspect this may be caused by having a rid in the parent project and not in the P2P reference project (StringProvider) Could you please try adding one to the P2P project?

**Comment by moozzyk** [comment]
rid or tfm? If I don't have a tfm in the child project then I can't restore:
```
Errors in C:\Source\cli-samples\HelloMvc\project.json
    Project StringProvider is not compatible with net451 (.NETFramework,Version=v4.5.1). Project StringProvider supports: netstandard1.5 (.NETStandard,Version=v1.5)
    One or more projects are incompatible with .NETFramework,Version=v4.5.1.
```
and the error I get from publish is correct:

```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -f net451
Publishing HelloMvc for .NETFramework,Version=v4.5.1/win7-x64
Project HelloMvc (.NETFramework,Version=v4.5.1) will be compiled because Input items removed from last build
Compiling HelloMvc for .NETFramework,Version=v4.5.1
C:\Source\cli-samples\HelloMvc\project.json(20,32): error NU1001: The dependency StringProvider >= 1.0.0-* could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.0217451

Published 0/1 projects successfully
```

**Comment by brthor** [comment]
@moozzyk I think both should be consistent 😄

**Comment by brthor** [comment]
@moozzyk I checked out this branch, and I am not able to repro on win10.

**Comment by brthor** [comment]
I've tried a few different things here and I can't repro this. 
```
C:\Users\brthor\code\repro\2938\cli-samples\HelloMvc>dotnet publish -f net451
Publishing HelloMvc for .NETFramework,Version=v4.5.1/win7-x64
Project StringProvider (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project HelloMvc (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Configuring the following project for use with IIS: 'C:\Users\brthor\code\repro\2938\cli-samples\HelloMvc\bin\Debug\net451\win7-x64\publish'
Updating web.config at 'C:\Users\brthor\code\repro\2938\cli-samples\HelloMvc\bin\Debug\net451\win7-x64\publish\web.config'
Configuring project completed successfully
publish: Published to C:\Users\brthor\code\repro\2938\cli-samples\HelloMvc\bin\Debug\net451\win7-x64\publish
Published 1/1 projects successfully

C:\Users\brthor\code\repro\2938\cli-samples\HelloMvc>git status
On branch repro
nothing to commit, working directory clean
```

I'm on a latest build so it's possible @eerhardt 's latest PR fixed this. Try it out with latest I'd say.
Going to close out for now.
