### ISSUE TITLE
Incorrect message/behavior when publishing a project without restoring the project first 

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2942]
## Steps to reproduce
Try publishing a project without restoring it first

## Expected  behavior
An error saying that the project needs to be restored

## Actual behavior
```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -f netcoreapp1.0
Collection was modified; enumeration operation may not execute.
PS C:\Source\cli-samples\HelloMvc> dotnet -v publish -f netcoreapp1.0
Telemetry is: Enabled
Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
```

## Environment data
`dotnet --info` output:

```
PS C:\Source\cli-samples\HelloWeb> dotnet --info
.NET Command Line Tools (1.0.0-rc2-002670)

Product Information:
 Version:     1.0.0-rc2-002670
 Commit Sha:  f0018642a9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by eerhardt** [comment]
More or less the same problem #2692. Except this is for publish and that issue is for test.

I have been working on a fix and it will fix this for both commands.
