### ISSUE TITLE
Assembly.Load issue when using latest cli running a test.

### ISSUE THREAD

**Issue by multiarc** [dotnet/cli#3010]
Run a test from the following solution: https://github.com/multiarc/roslyn-issues
The issue reproducing only with dotnet cli (both 1.0.0-preview1-002700 and 1.0.0-preview1-002702) using any version of Microsoft.CodeAnalysis.CSharp (1.1.1, 1.2.1, 1.3.0-beta). Fails only on net451 and net461 targets, works good on netcoreapp1.0 (dnxcore50) target.
By the way there is no issue when using DNX rc1-update2 (any target).

```csharp
namespace Tests
{
        public static class TestClass
        {
            private static void Main(string[] args) { }

            public static bool Test(dynamic value)
            {
                return value.Count > 0;
            }
        }
}
```
Expect sample code be compiled and run correctly but got the exception while loading compiled assembly:

>System.BadImageFormatException : Could not load file or assembly '0 bytes loaded from SelfReference, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
>      ---- System.BadImageFormatException : Bad IL format.
>      Stack Trace:
>           at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
>           at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
        CompilerTests.cs(83,0): at SelfReference.CompilerTests.RoslynBadImageFormatDebug()

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

**Comment by multiarc** [comment]
I did checked some results from .Emit() and found actual issue, once referenced Microsoft.CSharp fx reference tests not failing. Closing this as not an issue. My bad.
