### ISSUE TITLE
NullReferenceException in dotnet build if project.json target framework was changed

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#3075]
But project was not re-restored.

## Steps to reproduce
1. dotnet new
2. change `netcoreapp1.5` to `net451`
3. dotnet build

## Expected  behavior
Error message saying that project need to be restored

## Actual behavior
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tools.Build.ProjectGraphCollector.<Collect>d__3.MoveNext() in d:\github\dotnet\cli\src\dotnet\commands\dotnet-build\ProjectGraphCollector.cs:line 30
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Build.BuildCommand.OnExecute(IEnumerable`1 files, IEnumerable`1 frameworks, BuildCommandApp args) in d:\github\dotnet\cli\src\dotnet\commands\dotnet-build\Program.cs:line 59
   at Microsoft.DotNet.Tools.Compiler.BuildCommandApp.<>c__DisplayClass57_0.<Execute>b__0() in d:\github\dotnet\cli\src\dotnet\commands\dotnet-build\BuildCommandApp.cs:line 121
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args) in d:\github\dotnet\cli\src\dotnet\CommandLine\CommandLineApplication.cs:line 279
   at Microsoft.DotNet.Tools.Compiler.BuildCommandApp.Execute(OnExecute execute, String[] args) in d:\github\dotnet\cli\src\dotnet\commands\dotnet-build\BuildCommandApp.cs:line 126
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args, BuildWorkspace workspace) in d:\github\dotnet\cli\src\dotnet\commands\dotnet-build\Program.cs:line 30
```

**Comment by NickCraver** [comment]
+1 - Hit this while porting `StackExchange.Redis` up from RC1. I have a saved zip of the directory to re-test any fix here.

**Comment by livarcocc** [comment]
This code is going away.
