### ISSUE TITLE
dotnet test -r without an argument causes a hard crash

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#3084]
## Steps to reproduce
`dotnet test -r` (no actual argument for runtime)

## Expected  behavior
An error/informational message at the console that the `runtime` argument is required, optimally with a list of runtimes.

## Actual behavior
Hard crash outside of the terminal, WER style.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by vcsjones** [comment]
Stack trace:

Unhandled Exception: Microsoft.DotNet.Cli.CommandLine.CommandParsingException: Missing value for option 'runtime'
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Test.DotnetTestParams.Parse(String[] args)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
   at Microsoft.DotNet.Tools.Test.TestCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
