### ISSUE TITLE
EntityFrameworkCore.Tools throws FileNotFoundException System Version 2.0.5.0

### ISSUE THREAD

**Issue by prochnowc** [dotnet/cli#3314]
Running "dotnet ef" commands throws FileNotFoundException:

`
System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
File name: 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.EntityFrameworkCore.Tools.DispatchCommand.<>c__DisplayClass2_0.<Create>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
`
## Steps to reproduce

project.json:

`
"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "IdentityServer4": "1.0.0-beta2-update1",
    "TwentyTwenty.IdentityServer4.EntityFrameworkCore": "0.9.10",
    "Microsoft.EntityFrameworkCore.Tools": {
      "type": "build",
      "version": "1.0.0-preview1-final"
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by natemcmaster** [comment]
@prochnowc this is caused by using the wrong "imports" for Ms.EF.Tools. You should only have "portable-net451+win8": 
```json
    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": {
            "imports": "portable-net451+win8",
            "version": "1.0.0-preview1-final"
        }
    },
``` 

Unfortunately, because of https://github.com/dotnet/cli/issues/2978, you will need to delete NuGet caches for changing imports to take effect. See https://github.com/aspnet/EntityFramework/issues/5458#issuecomment-221912806 for instructions on clearing this cache.

**Comment by prochnowc** [comment]
@natemcmaster Thank you very much!
The import for tools was ok. But i also had to add the imports to the "Microsoft.EntityFrameworkCore.Tools" package in the dependencies. 
Note: If i do not add "dnxcore50" to the imports it does not work. 
Finally clearing caches and restoring did work.
Initially i followed this: https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html 
So experience is:
Developer follows this guide. Restores, somewhere finds info in the net to include "dnxcore50" as well .. and then it wont work because he does not know the caching issue.
The rc1-rc2 document should be updated.

**Comment by ritcoder** [comment]
I was getting the same error as above. After doing, what is recommended, `dotnet ef` works. After adding a migration, I get an error when `dotnet ef database update`. The error is as below

````
u:\Work\Projects\Project1\src\Project1>dotnet ef database update
Project Project1 (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation.
Applying migration '20160602145656_Added priority to donation causes'.
System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "Project1.Model.DonationRequest" because it does not exist or you do not have permissions.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Execute(IEnumerable`1 relationalCommands)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
ClientConnectionId:f1eafbc8-721a-4280-a2f9-2d9c39759a1e
Error Number:4902,State:1,Class:16
Cannot find the object "Project1.Model.DonationRequest" because it does not exist or you do not have permissions.
````

Code compiles and runs just fine. What have I missed?

**Comment by blackdwarf** [comment]
I believe this should be moved to https://github.com/aspnet/EntityFramework/issues/ as it seems like an issue with the EF tooling.
