### ISSUE TITLE
`dotnet restore` does not work with relative pathes for local package sources

### ISSUE THREAD

**Issue by chaliy** [dotnet/cli#350]
I have nuget.config

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
        <add key="thirdparties" value="thirdparties" />
      </packageSources>
    </configuration>

When I use nuget.exe, it correctly resolve full path to relative to nuget.config file folder thirdparties. However, when I try to use `dnu restore` or `dotnet restore` or Visual Studio it actually fails with response:

    $ dotnet restore
    Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-15838
    
      CACHE https://www.nuget.org/api/v2/
      CACHE https://api.nuget.org/v3/index.json
    Restoring packages for C:\Users\Mike\Projects\A\src\Shared\project.json
      CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections'
      CACHE https://api.nuget.org/v3-flatcontainer/system.collections/index.json
    Error: FindPackagesById: System.Collections
      The local package source thirdparties doesn't exist
    ----------
    System.IO.FileNotFoundException: The local package source thirdparties doesn't exist
    File name: 'thirdparties'
       at Microsoft.Dnx.Tooling.Restore.NuGet.PackageFolder.FindPackagesByIdAsync(String id)
       at Microsoft.Dnx.Tooling.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibrary>d__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
    ----------
    Restore failed
    The local package source thirdparties doesn't exist
    
    NuGet Config files used:
       C:\Users\Mike\AppData\Roaming\NuGet\nuget.config
       C:\Users\Mike\Projects\A\nuget.config
    
    Feeds used:
       https://www.nuget.org/api/v2/
       https://api.nuget.org/v3-flatcontainer/
       thirdparties

**Comment by piotrpMSFT** [comment]
dotnet currently uses DNU as the backer for `dotnet restore` so we're seeing the same behavior. Once we move to nuget[.exe] this should be resolved.

**Comment by piotrpMSFT** [comment]
This needs to be addressed in #421
