### ISSUE TITLE
dotnet test shows exception if project.json file is wrong

### ISSUE THREAD

**Issue by maririos** [dotnet/cli#3513]
## Steps to reproduce
1. Use a project.json file that has an error in the structure (i.e. a missing comma)
2. dotnet test
## Expected  behavior

When running the other dotnet commands they all show the following error message:
`After parsing a value an unexpected character was encountered: ". Path 'frameworks', line 19, position 2.`
`dotnet test` should show the same message.
## Actual behavior

dotnet-test Error: 0 : C:\Users\mariari\bugbash\src\project.json(19,2): Error: Microsoft.DotNet.ProjectModel.FileFormatException: After parsing a value an unexpected character was encountered: ". Path 'frameworks', line 19, position 2. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'frameworks', line 19, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(String path, Project& project, ProjectReaderSettings settings)
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(String path, Project& project, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.Workspace.AddProjectEntry(String projectDirectory, FileModelEntry`1 currentEntry)
   at Microsoft.DotNet.ProjectModel.Workspace.<GetProjectCore>b__11_0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Microsoft.DotNet.ProjectModel.Workspace.GetProjectCore(String projectDirectory)
   at Microsoft.DotNet.ProjectModel.Workspace.AddProjectContextEntry(String projectDirectory, ProjectContextCollection currentEntry)
   at Microsoft.DotNet.ProjectModel.Workspace.<GetProjectContextCollection>b__8_0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Microsoft.DotNet.ProjectModel.Workspace.GetProjectContextCollection(String projectPath)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by pvlakshm** [comment]
Sorry, we have not been able to look into this. We're focusing on the [newer](https://blogs.msdn.microsoft.com/visualstudioalm/2016/11/29/evolving-the-test-platform-part-3-net-core-convergence-and-cross-plat/) (MSBuild/csproj) based unit test platform, and most of our energy is going there. Can you please consider migrating to this model?

**Comment by maririos** [comment]
Sure. If this is no longer "valid" go ahead and close the issue

**Comment by livarcocc** [comment]
In MSBuild world, we fail appropriately depending on what is malformed in your csproj. For instance, if it is missing the opening < in the Project node, it fails with

```
/test/test.csproj(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
```
