### ISSUE TITLE
DotNET first run fails with 'The process cannot access the file...'

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#3542]
## Steps to reproduce
Using a many core machine (eg, mine has 8)
Ensure Windows defender is running with real-time protection and will scan %TEMP%
Run dotnet new

## Expected  behavior
First run executes completely

## Actual behavior
Fails with 
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (The process cannot access the file 'C:\Users\ericstj\AppData\Local\Temp\en1lktap.wiz\System.Runtime\4.1.0-rc3-24210-10\ref\netstandard1.0\de\System.Runtime.xml' because it is being used by another process.)) (The process cannot access the file 'C:\Users\ericstj\AppData\Local\Temp\en1lktap.wiz\System.Runtime\4.1.0-rc3-24210-10\ref\netstandard1.0\de\System.Runtime.xml' because it is being used by another process.) ---> System.IO.IOException: The process cannot access the file 'C:\Users\ericstj\AppData\Local\Temp\en1lktap.wiz\System.Runtime\4.1.0-rc3-24210-10\ref\netstandard1.0\de\System.Runtime.xml' because it is being used by another process.
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Microsoft.DotNet.Archive.IndexedArchive.CopyOperation.Execute()
   at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
   at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
   at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003067)

Product Information:
 Version:            1.0.0-preview2-003067
 Commit SHA-1 hash:  9f2bb66198

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
@ericstj already has a fix for this.

**Comment by TravisEz13** [comment]
Is this fix already available in a build?

**Comment by livarcocc** [comment]
@TravisEz13 Yes.

**Comment by Indhukrishna** [comment]
What build?  We have a number of people using 1.0.0-preview2-003067 and hitting this.

**Comment by livarcocc** [comment]
The next build should have it. We were having issues with signing the windows binaries, which prevented new builds from coming out. We have builds running right now and the next one will have the fix.

**Comment by livarcocc** [comment]
1.0.0-preview2-003112.

**Comment by shahabganji** [comment]
@livarcocc can you help me with the above-mentioned problem?
