### ISSUE TITLE
dotnet build fails when working project.json is in a directory with unicode

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/cli#3553]
## Steps to reproduce
1. `mkdir unicōde`
2. dotnet new
3. dotnet restore
4. dotnet build
## Expected  behavior

The application should build.
## Actual behavior

```
C:\Users\joelv\Desktop\unicōde>dotnet build
Project unicode (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling unicode for .NETCoreApp,Version=v1.0
Unhandled Exception: System.IO.FileNotFoundException: C:\Program Files\dotnet\sdk\1.0.0-preview1-002702\Microsoft.CodeAnalysis.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CommonCompiler.GetAssemblyFileVersion()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Users\joelv\Desktop\unicode\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code -532462766

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3258445


C:\Users\joelv\Desktop\unicōde>cd ..

C:\Users\joelv\Desktop>dotnet build unicōde
Couldn't find 'project.json' in 'unicode'
```

**Notice that the error message says "unicode" not "unicōde".
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/issues/2486 fixed a flavor of this.

Something else is going on here, @joelverhagen. I just did a repro of this scenario and got:

```
Installed:
    4 package(s) to /Users/piotrp/code/repro/r3553/unicōde/project.json
➜  unicōde dotnet build
Project unicōde (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling unicōde for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.0464092
 

➜  unicōde dotnet run
Project unicōde (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hello World!
➜  unicōde 
```

Can you create a small repro?

**Comment by joelverhagen** [comment]
Could it be platform dependent? Looks like your were running on Mac OS X right?

**Comment by blackdwarf** [comment]
This is actually fixed in the latest tooling. Will close. If it repros, please reopen.

**Comment by emirhosseini** [comment]
@blackdwarf What tooling? Are you talking about the sdk version? If so what version?

**Comment by blackdwarf** [comment]
@emirhosseini the latest version of the CLI you can download from this repo.

**Comment by emirhosseini** [comment]
@blackdwarf So that would require me to move my project away from the xproject over to the new csproj format along with whatever other changes?  I see the preview 4 of the CLI says that's the case.

**Comment by piotrpMSFT** [comment]
@emirhosseini once you install the latest CLI [RC4 at the moment] you can go to the root of your xproj/project.json solution and just run `dotnet migrate`. Do install the latest build as we've been doing a lot of work on migration in the past few months.
