### ISSUE TITLE
Dotnet.exe fails every single time, on every command, race condition on populating cache

### ISSUE THREAD

**Issue by joshcomley** [dotnet/cli#3557]
## Steps to reproduce
Any command, like `dotnet new` or `dotnet --help`

## Expected  behavior
The "local package cache" is populated and some command can be run

## Actual behavior
There seems to be a race condition that I hit every single time, I have tried about fifteen times now. I get this (mostly at 11% although one time I got to 23%):

	Welcome to .NET Core!
	---------------------
	Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
	Telemetry
	--------------
	The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
	You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
	You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
	Configuring...
	-------------------
	A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
	Decompressing 100% 4297 ms
	Expanding 11%
	Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (The process cannot access the file 'C:\Users\Josh Comley\AppData\Local\Temp\djffcbcu.z25\System.Security.Principal.Windows\4.0.0-rc3-24210-10\dotnet_library_license.txt' because it is being used by another process.)) (The process cannot access the file 'C:\Users\Josh Comley\AppData\Local\Temp\djffcbcu.z25\System.Security.Principal.Windows\4.0.0-rc3-24210-10\dotnet_library_license.txt' because it is being used by another process.) ---> System.IO.IOException: The process cannot access the file 'C:\Users\Josh Comley\AppData\Local\Temp\djffcbcu.z25\System.Security.Principal.Windows\4.0.0-rc3-24210-10\dotnet_library_license.txt' because it is being used by another process.
	   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
	   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
	   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
	   at Microsoft.DotNet.Archive.IndexedArchive.CopyOperation.Execute()
	   at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
	   at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
	   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
	   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
	   at System.Linq.Parallel.SpoolingTaskBase.Work()
	   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
	   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
	   at System.Threading.Tasks.Task.Execute()
	   --- End of inner exception stack trace ---
	   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
	   at System.Linq.Parallel.MergeExecutor`1.Execute()
	   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
	   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
	   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
	   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
	   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
	   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
	   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
	   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
	   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
	   at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
	   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
	   at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
	   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
	   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse()
	   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

I can't run `dotnet --info`, when I do I get the exact same error above.

I have PCIe SSDs in my laptop, so perhaps this is causing the race condition, but right now I'm completely locked out of any usage of `dotnet.exe`

**Comment by dantraMSFT** [comment]
I am also able to repro this.  dotnet.exe is 1.0.1.4459.

I also see a potential race condition:

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (The process cannot access the file 'C:\Users\dantra\AppData\Local\Temp\55ke5qds.kkc\System.Net.Http\4.1.0-rc3-24210-10\dotnet_library_license.txt' because it is being used by another process.)) (The process cannot access the file 'C:\Users\dantra\AppData\Local\Temp\55ke5qds.kkc\System.Net.Http\4.1.0-rc3-24210-10\dotnet_library_license.txt' because it is being used by another process.) ---> System.IO.IOException: The process cannot access the file 'C:\Users\dantra\AppData\Local\Temp\55ke5qds.kkc\System.Net.Http\4.1.0-rc3-24210-10\dotnet_library_license.txt' because it is being used by another process.

I have a process dump if it is needed.

**Comment by ericstj** [comment]
Dup of https://github.com/dotnet/cli/issues/3542
