### ISSUE TITLE
dotnet pack?

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#356]
I was planning to do separate issues but something is seriously wrong here and needs to be fixed:
Dotnet compile help for dotnet pack
```
> E:\oss\cli\artifacts\win7-x64\stage2\bin\dotnet-pack.exe --help
.NET Compiler

Usage: dotnet compile [arguments] [options]
```

Help or some useful message expected, this found:
```
>dotnet-pack
System.IO.FileNotFoundException: Could not find file 'E:\oss\cli\project.json'.
File name: 'E:\oss\cli\project.json'
   at System.IO.Win32FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectFile, ICollection`1 diagnostics)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectFile)
   at Microsoft.DotNet.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__28.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Compiler.Program.BuildPackage(String path, String configuration, String outputValue, String intermediateOutputValue) in E:\oss\cli\src\Microsoft.DotNet.Tools.Pack\Program.cs:line 75
   at Microsoft.DotNet.Tools.Compiler.Program.<>c__DisplayClass0_0.<Main>b__0() in E:\oss\cli\src\Microsoft.DotNet.Tools.Pack\Program.cs:line 54
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args) in C:\Users\kwicher.REDMOND\.dnx\packages\Microsoft.Extensions.CommandLineUtils.Sources\1.0.0-rc2-16248\shared\CommandLineApplication.cs:line 263
   at Microsoft.DotNet.Tools.Compiler.Program.Main(String[] args) in E:\oss\cli\src\Microsoft.DotNet.Tools.Pack\Program.cs:line 59
```

We should probably write down some spec and implement it correctly

**Comment by anurse** [comment]
The error messages and help certainly need to be cleaned up, but in both cases these are expected behaviors. `--help` is printing (an obviously copied and not updated) help message and `dotnet-pack` is failing because there isn't a project.json in the working directory.

I'm not sure this needs quite the urgent all caps red label on it, but it should be a fairly simple fix.

**Comment by anurse** [comment]
It should also be noted that this command will likely move to `nuget` and mostly exists just to allow ASP.NET to begin dogfooding `dotnet`

**Comment by anurse** [comment]
Also, the error message in a release build is significantly less noisy:

```
ps1 # dotnet pack
Could not find file 'C:\Users\anurse\Code\dotnet\cli\project.json'.
```
