### ISSUE TITLE
dotnet restore aborts on Debian (testing)

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#3655]
## Steps to reproduce

```sh
$ ./tools/dotnet-install.sh --debug-symbols
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003119/dotnet-dev-debian-x64.1.0.0-preview2-003119.tar.gz
dotnet-install: Extracting zip
dotnet-install: Adding to current process PATH: /home/andrew/.dotnet. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfuly.
$ dotnet --verbose restore
```

## Expected  behavior

Restore to take place.

## Actual behavior

```sh
$ dotnet --verbose restore 

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 1992 ms
Expanding 8%
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.TimeSpan.Add(TimeSpan ts)
   at System.TimeZoneInfo.ConvertToFromUtc(DateTime dateTime, TimeSpan daylightDelta, TimeSpan baseUtcOffsetDelta, Boolean convertToUtc)
   at System.TimeZoneInfo.IsAdjustmentRuleValid(AdjustmentRule rule, AdjustmentRule previousRule, DateTime dateTime, DateTime dateOnly, Boolean dateTimeisUtc)
   at System.TimeZoneInfo.GetAdjustmentRuleForTime(DateTime dateTime, Boolean dateTimeisUtc)
   at System.TimeZoneInfo.GetUtcOffset(DateTime time, TimeZoneInfo zone, TimeZoneInfoOptions flags)
   at System.TimeZoneInfo.GetUtcOffset(DateTime dateTime, TimeZoneInfoOptions flags, CachedData cachedData)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.IO.Compression.ZipArchiveEntry..ctor(ZipArchive archive, ZipCentralDirectoryFileHeader cd)
   at System.IO.Compression.ZipArchive.ReadCentralDirectory()
   at System.IO.Compression.ZipArchive.GetEntry(String entryName)
   at Microsoft.DotNet.Archive.IndexedArchive.ExtractSource.CopyToStream(Stream destinationStream)
   at Microsoft.DotNet.Archive.IndexedArchive.CopyOperation.Execute()
   at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
   at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
   at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted
```

## Environment data
`dotnet --info` output:

```sh
$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003119)

Product Information:
 Version:            1.0.0-preview2-003119
 Commit SHA-1 hash:  0708fe095e

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

@brthor any ideas? I'm on Debian testing...

**Comment by andschwa** [comment]
I checked what got upgraded today, and it's probably `binutils` as that was the only package I couldn't easily downgrade and retest. Just going to downgrade to stable and see how that goes...

**Comment by livarcocc** [comment]
@andschwa Did you have a chance to downgrade the dependency and try again?

**Comment by brthor** [comment]
@andschwa This is interesting right here:
```
at System.TimeSpan.Add(TimeSpan ts)
   at System.TimeZoneInfo.ConvertToFromUtc(DateTime dateTime, TimeSpan daylightDelta, TimeSpan baseUtcOffsetDelta, Boolean convertToUtc)
   at System.TimeZoneInfo.IsAdjustmentRuleValid(AdjustmentRule rule, AdjustmentRule previousRule, DateTime dateTime, DateTime dateOnly, Boolean dateTimeisUtc)
   at System.TimeZoneInfo.GetAdjustmentRuleForTime(DateTime dateTime, Boolean dateTimeisUtc)
   at System.TimeZoneInfo.GetUtcOffset(DateTime time, TimeZoneInfo zone, TimeZoneInfoOptions flags)
   at System.TimeZoneInfo.GetUtcOffset(DateTime dateTime, TimeZoneInfoOptions flags, CachedData cachedData)
``` 

Dumb question but is date/timezone configured on the machine? I'm not sure what would cause that.

**Comment by andschwa** [comment]
@livarcocc Of the packages that upgraded that day, I downgraded GCC et al., gettext, and a few libraries, to no avail. It was going to be a major pain to downgrade binutils so I couldn't test it.

@brthor right? It's strange. FWIW the same version of `dotnet` was working just fine until ~30 packages upgraded, so it's definitely one of the upgrades... but *which* would cause that, I don't know.

It's my home dev box, I'll see if I can narrow it down tonight for the sake of curiosity.

**Comment by livarcocc** [comment]
cc @ericstj @ellismg Can you guys help narrow this down?

**Comment by brthor** [comment]
> . FWIW the same version of dotnet was working just fine until ~30 packages upgraded, so it's definitely one of the upgrades...

Can you post the 30 packages?

**Comment by ericstj** [comment]
/cc @tarekgh
Nothing special going on in the compression code, it's just trying to new up a DateTime offset based on the timestamp in the header.  I wouldn't expect this to fail since its purely computational.  Likely something in CoreCLR's date-time impl is failing.

**Comment by ellismg** [comment]
Just so I understand what's going on here.  This was hit on Strech, not Jessie, right or are you seeing this on Jessie as well?

Also, what timezone do you have set locally?  I assume `America/Los_Angeles`?

**Comment by tarekgh** [comment]
CC @eerhardt

**Comment by livarcocc** [comment]
@ericstj I figured that out. I was hoping you would have an idea on why the DateTime would be failing.

**Comment by ericstj** [comment]
I think the DateTime dependencies on OS APIs are fragile for linux.  We've already been broken in the past.  @ellismg would know better about this.

**Comment by ellismg** [comment]
The implementation works by parsing `/etc/localtime` and other tz-info data.  We don't call any OS APIs directly.

Eric and Jon Skeet did some extensive testing and knocked out a bunch of corner cases.  What would be really helpful would be if we understood how to reproduce this (hence my questions to @andschwa about exactly what environment the repro was in).

**Comment by andschwa** [comment]
The box is at home, I will post logs and date data when I get back after work 😉

**Comment by andschwa** [comment]
Information incoming!

Packages that upgraded:

```
2016-06-20 10:06:52 upgrade sysv-rc:all 2.88dsf-59.4 2.88dsf-59.6
2016-06-20 10:06:53 upgrade initscripts:amd64 2.88dsf-59.4 2.88dsf-59.6
2016-06-20 10:06:53 upgrade sysvinit-utils:amd64 2.88dsf-59.4 2.88dsf-59.6
2016-06-20 10:06:54 upgrade libapt-pkg5.0:amd64 1.2.12 1.2.13
2016-06-20 10:06:56 upgrade libapt-inst2.0:amd64 1.2.12 1.2.13
2016-06-20 10:06:57 upgrade apt:amd64 1.2.12 1.2.13
2016-06-20 10:06:59 upgrade apt-utils:amd64 1.2.12 1.2.13
2016-06-20 10:07:00 upgrade sgml-base:all 1.27 1.28
2016-06-20 10:07:01 upgrade metacity:amd64 1:3.18.4-3 1:3.20.0-1
2016-06-20 10:07:03 upgrade metacity-common:all 1:3.18.4-3 1:3.20.0-1
2016-06-20 10:07:06 upgrade libavutil55:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:06 upgrade libswresample2:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:07 upgrade libavcodec57:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:12 upgrade wget:amd64 1.17.1-2 1.18-1
2016-06-20 10:07:13 upgrade google-chrome-stable:amd64 51.0.2704.84-1 51.0.2704.103-1
2016-06-20 10:07:18 upgrade libpython2.7:amd64 2.7.11-11 2.7.12~rc1-2
2016-06-20 10:07:18 upgrade python2.7:amd64 2.7.11-11 2.7.12~rc1-2
2016-06-20 10:07:19 upgrade libpython2.7-stdlib:amd64 2.7.11-11 2.7.12~rc1-2
2016-06-20 10:07:20 upgrade python2.7-minimal:amd64 2.7.11-11 2.7.12~rc1-2
2016-06-20 10:07:20 upgrade libpython2.7-minimal:amd64 2.7.11-11 2.7.12~rc1-2
2016-06-20 10:07:21 upgrade libpython3.5:amd64 3.5.1-16 3.5.2~rc1-3
2016-06-20 10:07:21 upgrade python3.5:amd64 3.5.1-16 3.5.2~rc1-3
2016-06-20 10:07:23 upgrade libpython3.5-stdlib:amd64 3.5.1-16 3.5.2~rc1-3
2016-06-20 10:07:24 upgrade python3.5-minimal:amd64 3.5.1-16 3.5.2~rc1-3
2016-06-20 10:07:24 upgrade libpython3.5-minimal:amd64 3.5.1-16 3.5.2~rc1-3
2016-06-20 10:07:25 upgrade libmpx0:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:25 upgrade g++-5:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:30 upgrade gcc-5:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:32 upgrade cpp-5:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:37 upgrade binutils:amd64 2.26-10 2.26-11
2016-06-20 10:07:38 upgrade libasan2:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:39 upgrade libstdc++-5-dev:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:39 upgrade libgcc-5-dev:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:40 upgrade gcc-5-base:amd64 5.3.1-21 5.4.0-4
2016-06-20 10:07:41 upgrade gettext-base:amd64 0.19.7-2 0.19.8.1-1
2016-06-20 10:07:42 upgrade gettext:amd64 0.19.7-2 0.19.8.1-1
2016-06-20 10:07:42 upgrade autopoint:all 0.19.7-2 0.19.8.1-1
2016-06-20 10:07:43 upgrade geoip-database:all 20160504-1 20160613-1
2016-06-20 10:07:43 upgrade librsvg2-dev:amd64 2.40.15-1 2.40.16-1
2016-06-20 10:07:43 upgrade librsvg2-common:amd64 2.40.15-1 2.40.16-1
2016-06-20 10:07:44 upgrade librsvg2-2:amd64 2.40.15-1 2.40.16-1
2016-06-20 10:07:45 upgrade gir1.2-rsvg-2.0:amd64 2.40.15-1 2.40.16-1
2016-06-20 10:07:45 upgrade libupower-glib3:amd64 0.99.4-2 0.99.4-3
2016-06-20 10:07:46 upgrade gir1.2-upowerglib-1.0:amd64 0.99.4-2 0.99.4-3
2016-06-20 10:07:46 upgrade libavformat57:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:46 upgrade libavresample3:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:47 upgrade libpostproc54:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:47 upgrade libswscale4:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:47 upgrade libavfilter6:amd64 7:3.0.2-3 7:3.0.2-4
2016-06-20 10:07:48 upgrade libgraphviz-dev:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:48 upgrade libcgraph6:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:49 upgrade libpathplan4:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:49 upgrade libxdot4:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:50 upgrade libgvc6:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:50 upgrade libgvpr2:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:50 upgrade libgvc6-plugins-gtk:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:51 upgrade libcdt5:amd64 2.38.0-13 2.38.0-14
2016-06-20 10:07:51 upgrade libcupsfilters1:amd64 1.8.3-2+b2 1.9.0-1
2016-06-20 10:07:51 upgrade libgif-dev:amd64 5.1.4-0.2 5.1.4-0.3
2016-06-20 10:07:52 upgrade libgif7:amd64 5.1.4-0.2 5.1.4-0.3
2016-06-20 10:07:53 upgrade libkpathsea6:amd64 2016.20160513.41080-2+b1 2016.20160513.41080-3
2016-06-20 10:07:53 upgrade python-debian:all 0.1.27 0.1.28
2016-06-20 10:07:54 upgrade python3-debian:all 0.1.27 0.1.28
2016-06-20 10:07:54 upgrade rxvt-unicode-256color:amd64 9.21-1+b1 9.22-1
2016-06-20 10:07:55 upgrade upower:amd64 0.99.4-2 0.99.4-3
2016-06-20 10:07:56 upgrade usb-modeswitch:amd64 2.3.0+repack0-1 2.4.0+repack0-1
2016-06-20 10:07:56 upgrade usb-modeswitch-data:all 20160112-3 20160612-1
```

And here are the ones I downgraded:

```
2016-06-20 16:21:06 upgrade libcurl3:amd64 7.38.0-4+deb8u3 7.47.0-1
2016-06-20 16:54:59 upgrade libcurl3:amd64 7.47.0-1 7.38.0-4+deb8u3
2016-06-20 16:59:24 upgrade gettext:amd64 0.19.8.1-1 0.19.3-2
2016-06-20 17:00:49 upgrade g++:amd64 4:5.3.1-3 4:4.9.2-2
2016-06-20 17:04:44 upgrade gcc:amd64 4:5.3.1-3 4:4.9.2-2
2016-06-20 17:05:29 upgrade cpp:amd64 4:5.3.1-3 4:4.9.2-2
2016-06-20 17:08:45 upgrade gettext-base:amd64 0.19.8.1-1 0.19.3-2
```

`/etc/localtime` and `/etc/timezone` are set:

```sh
$ ls -l /etc/localtime 
lrwxrwxrwx 1 root root 39 Jun  1 12:59 /etc/localtime -> /usr/share/zoneinfo/America/Los_Angeles
$ strings /etc/localtime | tail -n 1
PST8PDT,M3.2.0,M11.1.0
$ cat /etc/timezone 
America/Los_Angeles
```

This is Debian Testing / Stretch, and the same version of `dotnet` worked fine (barring the need to downgrade `libcurl3`) previously.

**Comment by andschwa** [comment]
I am sad! I built out a new CentOS 7 VM today so that I could specifically run a stable OS and get back to work... and `dotnet restore` segfaults during its initial decompression.

**Comment by ellismg** [comment]
Thanks Andy, I'll get a stretch VM and start poking around.

**Comment by ellismg** [comment]
I was unable to reproduce this on my debian testing VM:

```
matell@matell-deb9:~/test$ uname -a
Linux matell-deb9 4.5.0-2-amd64 #1 SMP Debian 4.5.3-2 (2016-05-08) x86_64 GNU/Linux
```

This is stretch with the latest and greatest packages from `apt-get update && apt-get update`.  I used the same timezone as you.  One thing that's interesting is that when you hit this, the stack implies there a null reference exception in TimeSpan.Add(TimeSpan) which shouldn't be possible as TimeSpan is a struct (and the argument is a struct as well).

Are you on a different Kernel or something?  Would it be possible for you to capture some core dumps or something?

**Comment by andschwa** [comment]
Hey! I think this is indeed related to #3681. This Debian Testing VM is running:

```
Linux debian 4.6.0-1-amd64 #1 SMP Debian 4.6.1-1 (2016-06-06) x86_64 GNU/Linux
```

And the CentOS VM is running:

```
Linux localhost.localdomain 4.6.2-1.el7.elrepo.x86_64 #1 SMP Wed Jun 8 14:49:20 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

It didn't *seem* related because `dotnet restore` had been working, and the CentOS machine consistently did not yield a stacktrace of any sort (and the Debian machine did).

Updating packages and seeing if it still reproduces (I'm guessing yes due to the kernel).

**Comment by andschwa** [comment]
Yup, even with updated packages (figures).

```
[ 3961.508307] traps: dotnet[14744] general protection ip:7fc8632ccc50 sp:7fc84db72b18 error:0 in libc-2.22.so[7fc863248000+19b000]
```

Managed to get a coredump on Debian easily enough, who wants it?

**Comment by andschwa** [comment]
Closing in favor of #3681.
