### ISSUE TITLE
build -Targets Compile fails

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3763]
## Steps to reproduce

Run `build.cmd -Targets Compile` in Windows or `./build.sh --targets Compile` on Ubuntu on a clean repo (may require `git clean -xdf` to clean artifacts from previous builds).

## Expected  behavior

Builds successfully.

## Actual behavior

Build fails:

```
[TARGET     <] [FAIL] [00:00:02.625] Compile                                               (Microsoft.DotNet.Cli.Build.CompileTargets.Compile)
Build failed: System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Users\Svick\git\cli\artifacts\win10-x64\intermediate\sharedFrameworkPublish'.
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystemEnumerableFactory.CreateFileNameIterator(String path, String originalUserPath, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Win32FileSystem.EnumeratePaths(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.DotNet.Cli.Build.FS.CopyRecursive(String sourceDirectory, String destinationDirectory, Boolean overwrite) in E:\Users\Svick\git\cli\build_projects\shared-build-targets-utils\Utils\FS.cs:line 89
   at Microsoft.DotNet.Cli.Build.CompileTargets.CopySharedFramework(String sharedFrameworkPublish, String rootOutputDirectory) in E:\Users\Svick\git\cli\build_projects\dotnet-cli-build\CompileTargets.cs:line 375
   at Microsoft.DotNet.Cli.Build.CompileTargets.CompileCliSdk(BuildTargetContext c, DotNetCli dotnet, String rootOutputDirectory, Boolean generateNugetPackagesArchive) in E:\Users\Svick\git\cli\build_projects\dotnet-cli-build\CompileTargets.cs:line 172
   at Microsoft.DotNet.Cli.Build.CompileTargets.CompileStage1(BuildTargetContext c) in E:\Users\Svick\git\cli\build_projects\dotnet-cli-build\CompileTargets.cs:line 85
   at Microsoft.DotNet.Cli.Build.Framework.BuildContext.ExecTarget(BuildTarget target) in E:\Users\Svick\git\cli\build_projects\Microsoft.DotNet.Cli.Build.Framework\BuildContext.cs:line 144
Build failed
At E:\Users\Svick\git\cli\build_projects\dotnet-cli-build\build.ps1:104 char:27
+ if($LASTEXITCODE -ne 0) { throw "Build failed" }
+                           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed
```

The reason why this matters is that [the developer guide](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/developer-guide.md#buildingrunning) suggests running these commands (which was added by me in https://github.com/dotnet/cli/pull/3435).

Building with targets `Prepare,Compile` instead of just `Compile` works.

**Comment by svick** [comment]
I can see few ways to fix this:

* Fix the dependencies (probably by making `Compile` depend on `Prepare`)
* Fix the developer guide:
 * Either by using `Prepare,Compile`.
 * Or by removing that suggestion altogether.

**Comment by eerhardt** [comment]
We are doing the exact same thing in the re-write of the build to MSBuild.  However, the advantage we get in MSBuild is that we can do incremental builds, where the stuff in "Prepare" that doesn't need to run over and over, doesn't get run.

Using the existing Cli.Build.Framework, we don't get incremental builds.

The reason Compile just depends on Init is because once you've run Prepare one time on an enlistment, it doesn't need to be run again.  So if you do a full build, and then say `build -Targets Compile`, the rest of "Prepare" doesn't run again.  The most time consuming piece is the restore.

I think I would vote for updating the developer guide here to explain that you need Prepare,Compile if you have a clean repo.  (Also, all of this is going away with the move to MSBuild.)

/cc @livarcocc @piotrpMSFT

**Comment by livarcocc** [comment]
Given that we are pretty advanced in the MSBuild work. I would vote for the developer guide update as well.
