### ISSUE TITLE
net40 application using MS.Bcl.Async fails with VerificationException because of binding redirects

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3853]
## Steps to reproduce
1. Create a `net40` application that references `Microsoft.Bcl.Async` and uses `await`:
   
   project.json:
   
   ``` json
   {
     "buildOptions": { "emitEntryPoint": true },
     "dependencies": { "Microsoft.Bcl.Async": "1.0.168" },
     "frameworks": { "net40": { } }
   }
   ```
   
   Program.cs:
   
   ``` c#
   using System.Threading.Tasks;
   
   class Program
   {
       static void Main() => F().Wait();
       static async Task F() => await TaskEx.Delay(100);
   }
   ```
2. `dotnet restore`
3. `dotnet run` or `dotnet publish` and then run from `publish` directory
## Expected  behavior

Application runs fine.
## Actual behavior

Application fails with:

```
Unhandled Exception: System.Security.VerificationException: Method System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AwaitUnsafeOnCompleted: type argument 'Microsoft.Runtime.CompilerServices.TaskAwaiter' violates the constraint of type parameter 'TAwaiter'.
   at Program.<F>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Program.F()
   at Program.Main() in C:\code\tmp\rtmapp\Program.cs:line 5
```

If I run `dotnet publish`, the `publish` directory contains this `.config` file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.5.11.0" newVersion="2.6.8.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.5.11.0" newVersion="2.6.8.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

If I delete it, the application starts working fine.

When I do the same in VS with csproj+packages.config, the application works fine and no `.config` is generated.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@svick no repro after migrating to preview3. Give it a shot and re-open if you see issues.

**Comment by liujun04** [comment]
@svick I met the same problem. Can you tell me how to solve it ? Thank you.
