### ISSUE TITLE
Unhandled exception on wrong command

### ISSUE THREAD

**Issue by 1sn0s** [dotnet/cli#4034]
## Steps to reproduce

Type dotnet restor (typo)
## Expected  behavior

Shouldn't it notify wrong command or something similar?
## Actual behavior

Unhandled exception : Directory not found. For AspNetCore.Razor.Tools

**Comment by jasonwilliams200OK** [comment]
It doesn't happen with:

```cmd
mkdir test1
dotnet new     :: (default) console app template
dotnet restor  :: non-existing command

:: error:
No executable found matching command "dotnet-restor"
```

but does happen with:

```cmd
mkdir test2
dotnet new -t web :: website template
dotnet restor     :: non-existing command

:: exception:
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Peter\.nuget\packages\.tools\Microsoft.EntityFrameworkCore.Tools'.
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystemEnumerableFactory.CreateFileNameIterator(String path, String originalUserPath, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Win32FileSystem.EnumeratePaths(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.DotNet.Cli.Utils.ToolPathCalculator.GetAvailableToolVersions(String packageId)
   at Microsoft.DotNet.Cli.Utils.ToolPathCalculator.GetBestLockFilePath(String packageId, VersionRange versionRange, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFilePath(LibraryRange toolLibrary, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFile(LibraryRange toolLibrary, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(LibraryRange toolLibraryRange, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(String commandName, IEnumerable`1 args, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

however, if we restore the packages before issuing any invalid command, then it does the right thing:

```cmd
mkdir test2
dotnet new -t web :: website template
dotnet restore    :: valid restore command
dotnet restor     :: non-existing command

:: error:
No executable found matching command "dotnet-restor"
```

@eerhardt, should the `TryResolveCommandSpec` method first identify first if the `dotnet restore` ran prior to resolve the commands?

**Comment by eerhardt** [comment]
> should the TryResolveCommandSpec method first identify whether the dotnet restore had ran prior to resolve the commands?

I agree. We put some effort in to the `build`, `publish` and `pack` commands to ensure the project was restored first, and give a good error message. It looks like here is a place we missed.

/cc @piotrpMSFT @brthor

**Comment by piotrpMSFT** [comment]
This problem exists in preview3 and is a bit worse... due to the work done to avoid conflicting with nuget, there is a 30s timeout waiting on a lock to open [via file system mutex] which first hangs and then fails with an exception. Need to fix this.
