### ISSUE TITLE
Error: No executable found matching command "dotnet-test-xunit"

### ISSUE THREAD

**Issue by tom-corwin** [dotnet/cli#4046]
## Steps to reproduce

1. Download the source of the NBitcoin project from [my fork](http://github.com/tom-corwin/NBitcoin).
2. Open the root project folder in the Command Prompt and run the following commands:
  * `cd NBitcoin.NETCore.Tests`
  * `dotnet restore --infer-runtimes`
  * `dotnet test`

## Expected  behavior

Unit tests (using the xUnit runner) should be executed.

## Actual behavior

After running the above commands, the following error occurs *after* running `dotnet test` (with the `-v` argument):
```
C:\Users\tacorwin\Documents\GitHub\NBitcoin\NBitcoin.NETCore.Tests>dotnet -v test
Telemetry is: Enabled
projectdependenciescommandresolver: C:\Users\tacorwin\Documents\GitHub\NBitcoin\NBitcoin.NETCore.Tests\bin\Debug\netcoreapp1.0\NBitcoin.NETCore.Tests.deps.json does not exist
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
   at Microsoft.DotNet.Tools.Test.TestCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by tom-corwin** [comment]
This issue was fixed in the referenced issue above. Sorry for the bother!
