### ISSUE TITLE
Unable to load DLL 'System.Security.Cryptography.Native'

### ISSUE THREAD

**Issue by stanislavromanov** [dotnet/cli#4149]
I've checked this issue and it seems that the problem is relying in OpenSSL, however I have tried with different versions of OpenSSL and still no success.

## Steps to reproduce

`dotnet new #Error`
`dotnet restore #Error`
`dotnet build #Error`

## Expected  behavior

Creates project, restores project, builds project

## Actual behavior

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
>  (Exception from HRESULT: 0x8007007E)
>    at Interop.CryptoInitializer.EnsureOpenSslInitialized()
>    at Interop.CryptoInitializer..cctor()
>    --- End of inner exception stack trace ---
>    at Interop.Crypto..cctor()
>    --- End of inner exception stack trace ---
>    at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
>    at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
>    at System.IO.Path.GetRandomFileName()
>    at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
>    at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
>    at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
>    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)
> [1]    32132 abort      dotnet new

## Environment data
`dotnet --info` output:

```
➜  test dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
➜  test openssl version
OpenSSL 1.0.2h  3 May 2016
➜  test which openssl
/usr/local/bin/openssl

```

**Comment by stanislavromanov** [comment]
# Resolved

For some reason mac installation instructions were modified and now we need to do this.
```
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```
