### ISSUE TITLE
dotnet-cli aborts with exception on OSX El Capitan

### ISSUE THREAD

**Issue by facadev** [dotnet/cli#4160]
I have openssl installed via brew and dotnet via the official installer. As the instruction goes, I run "dotnet new" and here is the output from the console:

`Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6
`

Any clue on what's going wrong and any fix for that?

**Comment by blackdwarf** [comment]
@facadev you need to have the needed OpenSSL binaries in the loader path. There are instructions on how to do that on https://dot.net/core for macOS.

**Comment by facadev** [comment]
@blackdwarf Actually yes, I did install OpenSSL and create two symbol links, as the instructions for macOS say.

**Comment by blackdwarf** [comment]
@facadev then this should not happen. @bartonjs do you have any idea what is happening here?

**Comment by bartonjs** [comment]
@blackdwarf Nope, the only thing that can cause it that I know of is fixed by our instructions.
@facadev Just to double check that there weren't typos during the command, and that everything's as expected, can you try

```
otool -L /usr/local/lib/libcrypto.1.0.0.dylib
otool -L /usr/local/lib/libssl.1.0.0.dylib
```

(If it says "No such file or directory" for either then the symlinks didn't get properly created)

**Comment by facadev** [comment]
@bartonjs @blackdwarf Eventually, I figured it out. It was because the dylibs were located in /Applications/homebrew/lib/ for me. Thank you so much! :)
