### ISSUE TITLE
Fix Ubuntu 'unknown command' experience

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#420]
Same versions as #407 

```sh
$ dotnet -v build

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted (core dumped)
```

Clearly there is an error in the build, and when it attempts to report it, it crashes.

**Comment by davidfowl** [comment]
There is no build command

**Comment by brthor** [comment]
This error shows up when the driver tries to call something that's not on the path. We should probably catch this beforehand.

**Comment by krwq** [comment]
that dll it is searching for it is windows specific

**Comment by andschwa** [comment]
@davidfowl Ah, no there is not. I forgot now it's `dotnet compile`, thank you.

But this error reporting has to be fixed, that was impossible to deduce from the given stacktrace.

**Comment by davidfowl** [comment]
Yea, that bug was filed a while ago
