### ISSUE TITLE
Microsoft.CSharp not found in web projects built on SDK 1.0.0-preview3-003708

### ISSUE THREAD

**Issue by tillig** [dotnet/cli#4278]
## Steps to reproduce
1. If not installed, install .NET Core SDK 1.0.0-preview3-003708 so Visual Studio can find it.
2. Create new .NET Core MVC project (File -> New Project)
3. Update `global.json` to specify running with SDK version 1.0.0-preview3-3708
4. Build and run project.

[Here is a small repro project: ReferenceNotFoundRepro.zip](https://github.com/dotnet/cli/files/501387/ReferenceNotFoundRepro.zip)
## Expected  behavior

I expect the home page to load and display.
## Actual behavior

Exception in view engine execution because `Microsoft.CSharp` can't be found.

```
System.InvalidOperationException: Can not find compilation library location for package 'microsoft.csharp'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003708)

Product Information:
 Version:            1.0.0-preview3-003708
 Commit SHA-1 hash:  30e5ab7112

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```
## Additional notes

While it appears similar to [this issue on the MVC repo](https://github.com/aspnet/Mvc/issues/4972), switching back to SDK 1.0.0-preview3-003546 removes the issue and things work as expected. Also, that noted issue on the MVC repo mentions you should see a "refs" folder when `dotnet publish` is called which includes Microsoft.CSharp and that should fix it. Running a `dotnet publish` does, in fact, create that folder - it just seems to be ignored in this latest version of the SDK.

It does not seem to matter whether the project targets `net452` or `net46` (I discovered the issue targeting `net46` but the repro I've attached is `net452`). I did not try pure .NET Core targets.

**Comment by tillig** [comment]
Issue still persists on 1.0.0-preview3-003716.

**Comment by xatabhk** [comment]
Same issue here.

**Comment by darkurse** [comment]
Same issue for me :(

**Comment by pealmeid** [comment]
Same issue for me on `1.0.0-preview3-003842`.

Also, this only happens if I run the project on the full `.NET Framework 4.6`. If I choose `.NETCoreApp` the project runs without any issues. I'm using Visual Studio with the latest updates.

**Comment by piotrpMSFT** [comment]
We recently completely removed project.json support from the preview3 CLI altogether. I believe build 3933 was the first to carry the change. If working with project.json please continue to use preview2 at the moment. Once the end-to-end migration scenario lights up you'll be able to use preview3 again.
