### ISSUE TITLE
System.Net.WebException: The remote server returned an error: (302) Found.

### ISSUE THREAD

**Issue by EncoderPtd** [dotnet/cli#4372]
## Steps to reproduce
  I was using `HttpWebRequest` to access a website. The server returned a redirection, then the `HttpWebResponse` threw an exception said:

> System.AggregateException: One or more errors occurred. (The remote server returned an error: (302) Found.) ---> System.Net.WebException: The remote server returned an error: (302) Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at NSHttpCommon.HttpAccess.GetResponse(Uri url, Boolean autoRedir, Stream stm, Dictionary`2 headers) in D:\User\CoreProjects\CommonUtilities\src\HttpCommon\__Source\Http\HttpAcc\HttpAccess.cs:line 169
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (302) Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

It's all ok when using .netframework. And also i tried manually using `Socket` or `TcpClient`. 
This is what server returned:

> HTTP/1.1 302 Found
Server: nginx/1.9.10
Date: Tue, 11 Oct 2016 06:50:39 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://xxx
P3P: CP="CAO PSA OUR"
Set-Cookie: xxx; EXPIRES=Fri, 02-Jan-2020 00:00:00 GMT; PATH=/; DOMAIN=yyy;
Set-Cookie: xxx; PATH=/; DOMAIN=yyy;
Set-Cookie: xxx; PATH=/; DOMAIN=yyy;
Set-Cookie: xxx; PATH=/; DOMAIN=yyy;
Set-Cookie: xxx; PATH=/; DOMAIN=yyy;

## Expected  behavior
Analyze correctly.

## Actual behavior
Threw exception.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003713)

Product Information:
 Version:            1.0.0-preview3-003713
 Commit SHA-1 hash:  98231a6628

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
I don't think this is the right repo for this bug. Maybe move it to the corefx repo? https://github.com/dotnet/corefx.

**Comment by EncoderPtd** [comment]
@livarcocc Thanks for reminding
