### ISSUE TITLE
dotnet restore Abort TRAP 6

### ISSUE THREAD

**Issue by SpiraMira** [dotnet/cli#4409]
## Steps to reproduce

On macOS Sierra build (16B2548a)
mac pro 3,1

Step 1: brew install openssl (add to $path and fix rpath etc...)
Step 2: install .NET Core using [https://www.microsoft.com/net/core#macos]
Step 3: **any dotnet** command results in ...

`Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment' threw an exception. ---> System.PlatformNotSupportedException: Error reading Darwin Kernel Version ---> System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.sysctl(Int32* name, UInt32 namelen, Byte* oldp, UInt32* oldlenp, IntPtr newp, UInt32 newlen)
   at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   at Microsoft.DotNet.InternalAbstractions.Native.PlatformApis.GetDarwinVersion()
   at Microsoft.DotNet.InternalAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6`

IMPORTANT NOTE: I am running Sierra on an unsupported mac pro 3,1. So the error, while unexpected, is not totally surprising. Just two things:

1 - Sierra runs smooth as silk on my old beast. Better than El Cap and never crashed throughout the entire beta cycle.  So I have no doubt that .NET Core CLI + Studio Code (which runs great) are ok. Is there any valid reason to run this check?  Can it be bypassed? If so, can someone point me in the right direction, so I can rebuild my custom solution?

2 - The environment check should bug out with a little more style.  A Trap 6 isn't nice... ;-)

Thx again.

BTW, hard-core mac guy here, thrilled to be able to do some native .NET Core development.  Keep up the good work! 

## Environment data
`dotnet --info` output: crashes!

**Comment by SpiraMira** [comment]
Ok - It seems like the issue may be a little trickier than I postulated above.  This doesn't have anything to do with my machine cpu featureset...And may be a more critical bug.

The exception is thrown here **GetKernelRelease() in  core-setup->NativeMethods.Darwin.cs** 

```
	            public unsafe static string GetKernelRelease()
	            {
	                const uint BUFFER_LENGTH = 32;
	

	                var name = stackalloc int[2];
	                name[0] = CTL_KERN;
	                name[1] = KERN_OSRELEASE;
	

	                var buf = stackalloc byte[(int)BUFFER_LENGTH];
	                var len = stackalloc uint[1];
	                *len = BUFFER_LENGTH;
	

	                try
	                {
	                    // If the buffer isn't big enough, it seems sysctl still returns 0 and just sets len to the
	                    // necessary buffer size. This appears to be contrary to the man page, but it's easy to detect
	                    // by simply checking len against the buffer length.
	                    if (sysctl(name, 2, buf, len, IntPtr.Zero, 0) == 0 && *len < BUFFER_LENGTH)
	                    {
	                        return Marshal.PtrToStringAnsi((IntPtr)buf, (int)*len);
	                    }
	                }
	                catch (Exception ex)
	                {
	                    throw new PlatformNotSupportedException("Error reading Darwin Kernel Version", ex);
	                }
	                throw new PlatformNotSupportedException("Unknown error reading Darwin Kernel Version");
	            }
	

	            [DllImport("libc")]

```

My equivalent test 

```
#include <sys/param.h>
#include <sys/sysctl.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

int main()
{
    int mib[] = {CTL_KERN, KERN_OSRELEASE};
    size_t len;
    sysctl(mib, sizeof mib / sizeof(int), NULL, &len, NULL, 0);

    char* kernelVersion = malloc(len);
    sysctl(mib, sizeof mib / sizeof(int), kernelVersion, &len, NULL, 0);

    printf("Kernel version is %s\n", kernelVersion);
    free(kernelVersion);
}
```

which returns

```
Kernel version is 16.1.0
Program ended with exit code: 0
```

**Comment by SpiraMira** [comment]
Should I move this issue to core-setup?

**Comment by SpiraMira** [comment]
Moved this issue to core-setup.
