### ISSUE TITLE
Build fails on macOS Sierra

### ISSUE THREAD

**Issue by SpiraMira** [dotnet/cli#4413]
## Steps to reproduce

1. clone cli project
2. build per instructions
3. build fails RELATED TO : #4409 core-setup #445

As noted in related issues, dotnet exception is thrown in 

Microsoft.DotNet.PlatformAbstractions.dll 
core-setup/src/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs
GetKernelRelease()

I'm kinda stuck here. A Show Stopper. Can this priority be elevated?
I'm new to this project, what is the proper way to attempt to fix and rebuild Microsoft.DotNet.PlatformAbstractions.dll while waiting for an official fix?

In my build, a GetKernelRelease() is referenced in...

```

find . -type f -exec grep -ils GetKernelRelease {} +;
./.dotnet_stage0/x64/sdk/1.0.0-preview3-003842/Microsoft.DotNet.PlatformAbstractions.dll
./.dotnet_stage0/x64/sdk/1.0.0-preview3-003842/NuGet.CommandLine.XPlat.dll
./.nuget/packages/microsoft.dotnet.platformabstractions/1.0.1-beta-000933/lib/net451/Microsoft.DotNet.PlatformAbstractions.dll
./.nuget/packages/microsoft.dotnet.platformabstractions/1.0.1-beta-000933/lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll
./.nuget/packages/nuget.commandline.xplat/3.6.0-rc-1979/lib/net46/NuGet.CommandLine.XPlat.exe
./.nuget/packages/nuget.commandline.xplat/3.6.0-rc-1979/lib/netcoreapp1.0/NuGet.CommandLine.XPlat.dll
./artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveFolder/microsoft.net.sdk/1.0.0-alpha-20161012-3/tools/net46/Microsoft.DotNet.PlatformAbstractions.dll
./artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveFolder/microsoft.net.sdk/1.0.0-alpha-20161012-3/tools/netcoreapp1.0/Microsoft.DotNet.PlatformAbstractions.dll
./artifacts/osx.10.12-x64/stage1/sdk/1.0.0-preview3-003845/Microsoft.DotNet.PlatformAbstractions.dll
./artifacts/osx.10.12-x64/stage1/sdk/1.0.0-preview3-003845/NuGet.CommandLine.XPlat.dll
./artifacts/osx.10.12-x64/stage1symbols/sdk/1.0.0-preview3-003845/Microsoft.DotNet.PlatformAbstractions.dll
./artifacts/osx.10.12-x64/stage1symbols/sdk/1.0.0-preview3-003845/NuGet.CommandLine.XPlat.dll
./artifacts/osx.10.12-x64/stage2/sdk/1.0.0-preview3-003845/Microsoft.DotNet.PlatformAbstractions.dll
./artifacts/osx.10.12-x64/stage2/sdk/1.0.0-preview3-003845/NuGet.CommandLine.XPlat.dll
./artifacts/osx.10.12-x64/stage2symbols/sdk/1.0.0-preview3-003845/Microsoft.DotNet.PlatformAbstractions.dll
./artifacts/osx.10.12-x64/stage2symbols/sdk/1.0.0-preview3-003845/NuGet.CommandLine.XPlat.dll
./build_projects/dotnet-cli-build/bin/Microsoft.DotNet.PlatformAbstractions.dll
./build_projects/dotnet-cli-build/bin/NuGet.CommandLine.XPlat.dll
./build_tools/dotnetcli/sdk/1.0.0-preview2-002733/Microsoft.DotNet.InternalAbstractions.dll
./build_tools/dotnetcli/sdk/1.0.0-preview2-002733/Microsoft.Extensions.PlatformAbstractions.dll

```
Thanks in advance.

Patrice Kouame

## Actual behavior

Error returned:
```

           Installing System.Security.Principal.Windows 4.0.0.
           Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
           Committing restore...
           Writing lock file to disk. Path: /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveProject/obj/project.assets.json
           Generating MSBuild file /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveProject/obj/NuGetPackagesArchiveProject.csproj.nuget.g.targets.
           Generating MSBuild file /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveProject/obj/NuGetPackagesArchiveProject.csproj.nuget.g.props.
           Restore completed in 25282ms for /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveProject/NuGetPackagesArchiveProject.csproj.

           NuGet Config files used:
               /Users/me/Dev/dotnet/cli/NuGet.Config
               /Users/me/.nuget/NuGet/NuGet.Config

           Feeds used:
               https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
               https://dotnet.myget.org/F/cli-deps/api/v3/index.json
               https://www.myget.org/F/xunit/api/v3/index.json
               https://api.nuget.org/v3/index.json

           Installed:
               112 package(s) to /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveProject/NuGetPackagesArchiveProject.csproj
         Done Building Project "/Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/intermediate/NuGetPackagesArchiveProject/NuGetPackagesArchiveProject.csproj" (Restore target(s)).

         Build succeeded.
             0 Warning(s)
             0 Error(s)

         Time Elapsed 00:00:26.04
         Publishing Archiver
         /Users/me/Dev/dotnet/cli/tools/Archiver> /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/stage2/dotnet publish  --configuration Debug    --output /Users/me/Dev/dotnet/cli/artifacts/osx.10.12-x64/tools
         Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.12-x64'. Possible causes:
         1. The project has not been restored or restore failed - run `dotnet restore`
         2. The project does not list one of 'osx.10.12-x64' in the 'runtimes' section.
         3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
     1>/Users/me/Dev/dotnet/cli/build/compile/Microsoft.DotNet.Cli.LzmaArchive.targets(28,7): error MSB6006: "dotnet" exited with code 1. [/Users/me/Dev/dotnet/cli/build.proj]
     1>Done Building Project "/Users/me/Dev/dotnet/cli/build.proj" (default targets) -- FAILED.

Build FAILED.

       "/Users/me/Dev/dotnet/cli/build.proj" (default target) (1) ->
       (GenerateNuGetPackagesArchive target) ->
         /Users/me/Dev/dotnet/cli/build/compile/Microsoft.DotNet.Cli.LzmaArchive.targets(28,7): error MSB6006: "dotnet" exited with code 1. [/Users/me/Dev/dotnet/cli/build.proj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:06:37.32
```
## Environment data
`dotnet --info` output: **crashes**!

**Comment by dasMulli** [comment]
I'm working around it by setting `DOTNET_RUNTIME_ID` to a supported version.
A simple `export DOTNET_RUNTIME_ID=osx.10.11-x64` before everything i do unblocks me.

**Comment by SpiraMira** [comment]
Cool.  Thx for the tip! 

- Do you know which 'runtimes' section it suggests osx.10.12-x64 should be listed in? (output from stage2/dotnet publish)

Let me try a rebuild...

**Comment by SpiraMira** [comment]
Ok - exporting DOTNET_RUNTIME_ID to "fool" the build let's it complete. Great.

But dotnet still aborts the same way...

```
[15:59:05] [me@Patrices-Pro /Users/me/Dev/dotnet/cli]$ ./artifacts/osx.10.11-x64/stage2/dotnet --info

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception. ---> System.PlatformNotSupportedException: Error reading Darwin Kernel Version ---> System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Darwin.sysctl(Int32* name, UInt32 namelen, Byte* oldp, UInt32* oldlenp, IntPtr newp, UInt32 newlen)
   at Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetDarwinVersion()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.get_MulticoreJitProfilePath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

```

I still suspect the problem lies in 

Microsoft.DotNet.PlatformAbstractions.dll 
core-setup/src/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs
GetKernelRelease()

as mentioned above.  

Are you up and running on Sierra?

**Comment by SpiraMira** [comment]
Well it looks like my DYLD_FALLBACK_LIBRARY_PATH was preventing the libc.dylib load in GetKernelRelease().  

./artifacts/osx.10.11-x64/stage2/dotnet --info now returns

```
.NET Command Line Tools (1.0.0-preview3-003852)

Product Information:
 Version:            1.0.0-preview3-003852
 Commit SHA-1 hash:  a97d44eded

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

```

Fact remains that **we shouldn't have to reset our DOTNET_RUNTIME_ID to El Cap**.  So I'll keep this open since I'm not really sure what the downstream consequences of running a 10.11-x64 dotnet toolchain on Sierra are. @dasMulli do you?

BTW, I am running my builds with :

`./build.sh /t:Compile /p:SkipInvalidConfigurations=true`

Dunno what /p:SkipInvalidConfigurations=true really does either...

Thanks again to all.
