### ISSUE TITLE
ConsoleApplication.E2ETest.TestDotnetPublish [FAIL]

### ISSUE THREAD

**Issue by devigned** [dotnet/cli#447]
Running ./build.sh from a fresh clone of master results in  on OS X 10.11 "ConsoleApplication.E2ETest.TestDotnetPublish [FAIL]" (cmake version 3.4.1).

### build output

```bash
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: E2E
Discovered:  E2E
Starting:    E2E
Created new project in /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest.
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

Restoring packages for /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.json
Installing System.IO.4.0.11-beta-23516
Writing lock file /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.lock.json
Restore complete, 3134ms elapsed
Compiling hellotest for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.9247817

   ConsoleApplication.E2ETest.TestDotnetCompile [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: Hello World!\n
      Actual:
                ↑ (pos 0)
      Stack Trace:
            at ConsoleApplication.E2ETest.TestOutputExecutable(String outputDir)
            at ConsoleApplication.E2ETest.TestDotnetCompile()
Created new project in /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest.
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

Restoring packages for /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.json
Writing lock file /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.lock.json
Restore complete, 2320ms elapsed
Compiling hellotest for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3039002

Input Assembly: /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/testbin/hellotest.dll
Created new project in /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest.
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

Restoring packages for /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.json
Writing lock file /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.lock.json
Restore complete, 1994ms elapsed

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   ConsoleApplication.E2ETest.TestDotnetRun [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   134
      Stack Trace:
            at ConsoleApplication.E2ETest.TestRunCommand(String command, String args)
            at ConsoleApplication.E2ETest.TestDotnetRun()
Skipping Test for reason: https://github.com/dotnet/cli/issues/246
Created new project in /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest.
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

Restoring packages for /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.json
Writing lock file /Users/david/devigned/cli/artifacts/osx.10.10-x64/e2etest/hellotest/project.lock.json
Restore complete, 2238ms elapsed
'' cannot be published for 'dnxcore50' 'osx.10.10-x64'
   ConsoleApplication.E2ETest.TestDotnetPublish [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
            at ConsoleApplication.E2ETest.TestRunCommand(String command, String args)
            at ConsoleApplication.E2ETest.TestDotnetPublish()
Finished:    E2E

=== TEST EXECUTION SUMMARY ===
   E2E  Total: 5, Errors: 0, Failed: 3, Skipped: 0, Time: 28.629s
```

**Comment by piotrpMSFT** [comment]
we need to get 10.11 added to CI to ferret out these issues. Looks like the RID for 10.11 isn't being mapped yet...

**Comment by krwq** [comment]
should we actually have separate RIDs for each version and subversion?

**Comment by davidfowl** [comment]
I see this too.

**Comment by brthor** [comment]
Related #439

**Comment by piotrpMSFT** [comment]
@MichaelSimons can you take a first crack at getting our RIDs in order for OS X?

**Comment by piotrpMSFT** [comment]
Tracking in #498
