### ISSUE TITLE
Invalid input 'global.json' using dotnet restore

### ISSUE THREAD

**Issue by Robula** [dotnet/cli#4489]
## Steps to reproduce

1:  Define a `global.json` file:
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}
```
2:  Run `dotnet restore global.json --verbosity Debug`

## Expected  behavior
The restore to complete.

## Actual behavior
`Invalid input 'global.json'. Valid file names are 'project.json' or '*.project.json'.`
```
trace: NuGet Command Line Version: 3.5.0.0
trace: Running restore with 12 concurrent jobs.
error: Invalid input 'global.json'. Valid file names are 'project.json' or '*.project.json'.
trace: System.AggregateException: One or more errors occurred. (Invalid input 'global.json'. Valid file names are 'project.json' or '*.project.json'.) ---> System.InvalidOperationException: Invalid input 'global.json'. Valid file names are 'project.json' or '*.project.json'.
trace:    at NuGet.Commands.RestoreRunner.<CreateRequests>d__3.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
trace:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.<>c__DisplayClass68_0.<OnExecute>b__0()
trace:    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
trace: ---> (Inner Exception #0) System.InvalidOperationException: Invalid input 'global.json'. Valid file names are 'project.json' or '*.project.json'.
trace:    at NuGet.Commands.RestoreRunner.<CreateRequests>d__3.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
trace:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()<---
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
The global.json has configurations for the restore and it will get picked up automatically. It is not a valid input for restore.

**Comment by Robula** [comment]
That's misleading as both the `--help` and the [docs](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-restore) pages states otherwise.

`dotnet restore --help`

Usage: nuget3 restore [arguments] [options]

Arguments:
  [root]  List of projects and project folders to restore. **Each value can be: a path to a project.json or _global.json_ file**, or a folder to recursively search for project.json files.

Thanks, I didn't realise it was automatic.
