### ISSUE TITLE
Migrate: Improve error message on failure

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#4570]
Project is not expected to migrate but some actionable error is expected.

## Steps to reproduce
dotnet migrate

project.json
```
{
    "dependencies": {
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools" : {
            "version": "1.0.0-preview2-final",
            "type": "build"
        }
    }
}
```

## Expected  behavior
Actionable error message

## Actual behavior
If you have symbols:
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.ProjectJsonMigration.MigrationRuleInputs.get_DefaultProjectContext()
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass27_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
Migration failed.
```
if you don't:
```
Sequence contains no elements
Migration failed.
```

## Environment data
`dotnet --info` output:
 Version:            1.0.0-preview3-003975
 Commit SHA-1 hash:  f53c51fc07

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

**Comment by blackdwarf** [comment]
@krwq good catch. We should never show exceptions to the users.

**Comment by krwq** [comment]
@blackdwarf, the stack is only when you have symbols (which is good), if you don't then you get really not helpful error "Sequence contains no elements"

**Comment by MattGertz** [comment]
@livarcocc @piotrpMSFT Another one like #4370 where it's now or never due to impending loc freeze.

**Comment by blackdwarf** [comment]
@krwq for localization purposes, what is the actual source of the error (why are we throwing)?

**Comment by livarcocc** [comment]
The problem is that this PJ does not specify any target frameworks. This is the message that I will use. Hopefully.
