### ISSUE TITLE
Flaky tests in CLI

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4660]
- [x] Microsoft.DotNet.Migration.Tests.GivenThatAnAppWasMigrated.
When_migration_succeeds_Then_project_json_artifacts_get_moved_to_backup(
testProjectName: \"TestAppWithLibrary\")
- [x] Microsoft.DotNet.Cli.Utils.Tests.GivenAProjectDependencyCommandResolver.
ItSetsDepsfileToOutputInCommandspecForMSBuild
- [x] Microsoft.DotNet.Cli.Utils.Tests.GivenAProjectDependencyCommandResolver.
ItPassesDepsfileArgToHostWhenReturningACommandSpecForMSBuildProject
- [x] Microsoft.DotNet.Cli.Utils.Tests.GivenAProjectDependencyCommandResolver.
ItReturnsACommandSpecWhenToolIsInAProjectRef
- [ ] see below from @livarcocc 
- [x] see below from @piotrpmsft

**Comment by livarcocc** [comment]
It seems we still have some flaky tests left, but with different causes now:

```
21:38:50 DOTNETTEST : error Message:  [/mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/build/test/RunTest.proj]
21:38:50    The command output did not contain expected result: Hello Portable World!
21:38:50   
21:38:50   
21:38:50   File Name: /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/artifacts/centos.7-x64/stage2/dotnet
21:38:50   Arguments: portable 
21:38:50   WorkingDir:: /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/test/dotnet.Tests/bin/Debug/netcoreapp1.0/TestProjectToolIsAvailableThroughDriver/AppWithToolDependency
21:38:50   Exit Code: 139
21:38:50   StdOut:
21:38:50   
21:38:50   StdErr:
21:38:50 A JSON parsing exception occurred in [/mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/.nuget/packages/.tools/dotnet-portable/1.0.0/netcoreapp1.0/dotnet-portable.deps.json] : * Line 1, Column 2 Syntax error : Malformed literal [/mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/build/test/RunTest.proj]
21:38:50   Error initializing the dependency resolver: An error occurred while parsing /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/.nuget/packages/.tools/dotnet-portable/1.0.0/netcoreapp1.0/dotnet-portable.deps.json
```

**Comment by piotrpMSFT** [comment]
One more:
```
DOTNETTEST : error Message:  [/mnt/j/workspace/dotnet_cli/rel_1.0.0/debug_ubuntu16.04_x64_prtest/build/test/RunTest.proj]
   System.AggregateException : One or more errors occurred. (The collection has been disposed.
  Object name: 'BlockingCollection'.)
  ---- System.ObjectDisposedException : The collection has been disposed.
  Object name: 'BlockingCollection'.
  Stack Trace:
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
     at Microsoft.DotNet.Tools.Test.Utilities.TestCommand.RunProcess(String executable, String args, StreamForwarder stdOut, StreamForwarder stdErr) in /mnt/j/workspace/dotnet_cli/rel_1.0.0/debug_ubuntu16.04_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs:line 137
  Failed   Microsoft.DotNet.Migration.Tests.GivenThatAnAppWasMigrated.When_skipbackup_specified_Then_project_json_artifacts_do_not_get_moved_to_backup(testProjectName: "PJTestAppSimple")
```

**Comment by livarcocc** [comment]
@piotrpMSFT Assigning to you since you have been chasing these guys down.
