### ISSUE TITLE
dotnet <non-existing-string> exits with NRE in some cases

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#4732]
## Steps to reproduce
In the root of cli repo type `dotnet asdfasdf`
In some other folders we actually get nice exceptions - I haven't investigated how those folders are different.

## Expected  behavior
Graceful exception

## Actual behavior
```
d:\cli>dotnet dfsdfds
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.MSBuildProject.GetLockFilePathFromIntermediateBaseOutputPath() in D:\cli\src\Microsoft.DotNet.Cli.Utils\CommandResolution\MSBuildProject.cs:line 143
   at Microsoft.DotNet.Cli.Utils.MSBuildProject.GetLockFile() in D:\cli\src\Microsoft.DotNet.Cli.Utils\CommandResolution\MSBuildProject.cs:line 124
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments) in D:\cli\src\Microsoft.DotNet.Cli.Utils\CommandResolution\ProjectToolsCommandResolver.cs:line 75
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments) in D:\cli\src\Microsoft.DotNet.Cli.Utils\CommandResolution\ProjectToolsCommandResolver.cs:line 52
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments) in D:\cli\src\Microsoft.DotNet.Cli.Utils\CommandResolution\CompositeCommandResolver.cs:line 31
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName) in D:\cli\src\Microsoft.DotNet.Cli.Utils\CommandResolver.cs:line 49
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName) in D:\cli\src\Microsoft.DotNet.Cli.Utils\Command.cs:line 94
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName) in D:\cli\src\Microsoft.DotNet.Cli.Utils\Command.cs:line 75
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient) in D:\cli\src\dotnet\Program.cs:line 184
   at Microsoft.DotNet.Cli.Program.Main(String[] args) in D:\cli\src\dotnet\Program.cs:line 69
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004088)

Product Information:
 Version:            1.0.0-preview4-004088
 Commit SHA-1 hash:  7c8eeb42ab

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by krwq** [comment]
I think this is not reproing anymore. Possibly one of my tools changes could've fixed that
