### ISSUE TITLE
Takes long time to fail in in- dotnet command before genrating lockfiles

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/cli#4775]
## Steps to reproduce

1. generate dotnet project ``dotnet new``
2. execute non-existence command e.g. ``dotnet aaa``

This should be exected before ``dotnet restore`` (generating lock file). When already restore, please remove ``obj/project.assets.json`` then you can reproduce this error again.

## Expected  behavior
Show the error ``No executable found matching command "dotnet-aaa"`` soon.

## Actual behavior
It took 35 seconds to show error.

```
$ date; /opt/dotnet/dotnet aaa; date
Fri Nov 18 16:15:34 JST 2016
One or more errors occurred. (Could not access assets file.)
Fri Nov 18 16:16:09 JST 2016
```

The result with verbose option.
```
$ date; /opt/dotnet/dotnet -v aaa -v; date
Fri Nov 18 16:16:35 JST 2016
Telemetry is: Disabled
projetfactory: MSBUILD_EXE_PATH = /opt/dotnet/sdk/1.0.0-preview4-004079/MSBuild.dll
projetfactory: MSBuild project path = /home/tanaka733/Documents/demo2/test/test.csproj
System.AggregateException: One or more errors occurred. (Could not access assets file.) ---> System.InvalidOperationException: Could not access assets file.
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.<RetryOnFileAccessFailure>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DotNet.Cli.Utils.LockFileFormatExtensions.<ReadWithLock>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.DotNet.Cli.Utils.MSBuildProject.GetLockFile()
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
---> (Inner Exception #0) System.InvalidOperationException: Could not access assets file.
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.<RetryOnFileAccessFailure>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DotNet.Cli.Utils.LockFileFormatExtensions.<ReadWithLock>d__2.MoveNext()<---

Fri Nov 18 16:17:11 JST 2016
```

To look into ``Microsoft.DotNet.Cli.Utils.MSBuildProject.GetLockFile`` method, it looks like it doesn't check file existence then waiting for async method due to fail to read non-existence file.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolution/MSBuildProject.cs#L122-L130
https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/Extensions/LockFileFormatExtensions.cs#L20-L31

If it only has to check file existence in GetLockFile method, I can make PR soon.

## Environment data
`dotnet --info` output:
```
$ /opt/dotnet/dotnet --info
.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.3
 OS Platform: Linux
 RID:         rhel.7.2-x64
```

**Comment by piotrpMSFT** [comment]
I think the async method's exception handler needs to be beefed up here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/FileAccessRetryer.cs#L43. The intent of this code is to loop while the file is in use, but the current `catch` is accepting any IO Exception, including the file not existing.

I don't want to explicitly check for the file existing as the name, etc. of the file is a NuGet concern and can change with time.

**Comment by tanaka-takayoshi** [comment]
@piotrpMSFT Thank you so much for such a quick fix. I confirmed the issue is fixed the latest daily build. I'm closing the case.
