### ISSUE TITLE
dotnet migrate fails with 'The given key was not present in the dictionary.'

### ISSUE THREAD

**Issue by der-andy** [dotnet/cli#4835]
I have a solution with multiple projects. The "main" web project is an ASP.NET Core 1.1 project using .NET Framework 4.6.2. It references another project which is a "classic" Desktop class library (.csproj) which itself also references another "classic" class library. The web project is the only .xproj file in the solution.

In VS2015, everything worked fine. But I wanted to unify the project types. Instead of converting all projects to .xproj, I decided to use VS2017RC and the new .csproj files. But when I tried to load the solution in VS2017RC, the migration process failed. When VS tries to migrate the solution, I get an error that "`dotnet migrate [...]` exited with error code 1". When I try to call `dotnet migrate` from the command line myself, it says 'The given key was not present in the dictionary.'

I manually changed my `global.json` to use preview 3 since preview 2 doesn't know `dotnet-migrate`.

Unfortunately, I'm not allowed to share the code with you, but I'll try to give you any information you need.

The classic library is referenced by the web project as follows:

### project.json
```
[...]
"frameworks": {
  "net462": {
    "dependencies": {
      "FooBar.Common": {
        "target": "project"
      }
    }
  }
},
[...]
```

### FooBar.Web.xproj
```
[...]
<ProjectReference Include="..\FooBar.Common\FooBar.Common.csproj" />
[...]
```

## Steps to reproduce

* Call `dotnet migrate` in the solution folder.

I wanted to create a minimal example for my problem, but I'm not able to create a new ASP.NET Core project in VS2015 anymore. When it comes to package restore, there is an error in the output window: `MSBUILD : error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1. [C:\Users\[...]\.vs\restore.dg]` (worth another issue?)

## Expected  behavior

Solution/project gets migrated.

## Actual behavior

Migration fails with the following output:
```
The given key was not present in the dictionary.
Migration failed.
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by alecrt** [comment]
Same issue here:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

In the zip attached project.json and xproj files
[project_files.zip](https://github.com/dotnet/cli/files/611572/project_files.zip)

**Comment by dasMulli** [comment]
So the script migration seems to have an issue when using an unsupported script hook [here](https://github.com/dotnet/cli/blob/eb8e0cfa409d2ef89091f2058487be0e48e8a32e/src/Microsoft.DotNet.ProjectJsonMigration/Rules/MigrateScriptsRule.cs#L90).

If i delete the `postbuild` script from the repro provided by @alecrt, the migration succeeds.

Log from my debug build (preview4-004124):
```
DefaultMigrationRuleSet: Executing migration rule MigrateScriptsRule
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateScriptsRule.CreateTarget(ProjectRootElement csproj, String scriptSetName)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateScriptsRule.MigrateScriptSet(ProjectRootElement csproj, ProjectPropertyGroupElement propertyGroup, IEnumerable`1 scriptCommands, String scriptSetName)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateScriptsRule.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs)
   at Microsoft.DotNet.ProjectJsonMigration.DefaultMigrationRuleSet.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.MigrateProject(MigrationSettings migrationSettings)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass27_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
Migration failed.
```
