### ISSUE TITLE
Flacky test GivenThatAnAppWasMigrated.When_skipbackup_specified_Then_project_json_artifacts_do_not_get_moved_to_backup

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4839]
## Steps to reproduce

Run ci test suite

## Expected  behavior

Pass

## Actual behavior

Intermittentlye (expecially on Ubuntu x64 Release Build), the build fails with a test error (ref [test report](https://ci.dot.net/job/dotnet_cli/job/rel_1.0.0/job/release_ubuntu_x64_prtest/130/testReport/(root)/(empty)/Microsoft_DotNet_Migration_Tests_GivenThatAnAppWasMigrated_When_skipbackup_specified_Then_project_json_artifacts_do_not_get_moved_to_backup_testProjectName___PJTestAppSimple__/) )

Test: .Microsoft.DotNet.Migration.Tests.GivenThatAnAppWasMigrated.When_skipbackup_specified_Then_project_json_artifacts_do_not_get_moved_to_backup(testProjectName: "PJTestAppSimple") (from MSTestSuite)

```
Stacktrace

                                        MESSAGE:
                                        System.AggregateException : One or more errors occurred. (The collection has been disposed.
Object name: 'BlockingCollection'.)
---- System.ObjectDisposedException : The collection has been disposed.
Object name: 'BlockingCollection'.
                                        +++++++++++++++++++
                                        STACK TRACE:
                                           at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DotNet.Tools.Test.Utilities.TestCommand.RunProcess(String executable, String args, StreamForwarder stdOut, StreamForwarder stdErr) in /opt/code/test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs:line 137
   at Microsoft.DotNet.Tools.Test.Utilities.TestCommand.Execute(String args) in /opt/code/test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs:line 53
   at Microsoft.DotNet.Migration.Tests.GivenThatAnAppWasMigrated.When_skipbackup_specified_Then_project_json_artifacts_do_not_get_moved_to_backup(String testProjectName) in /opt/code/test/dotnet-migrate.Tests/GivenThatAnAppWasMigrated.cs:line 73
----- Inner Stack Trace -----
   at System.Collections.Concurrent.BlockingCollection`1.CheckDisposed()
   at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.Utils.BlockingMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count) in /opt/code/src/Microsoft.DotNet.Cli.Utils/BlockingMemoryStream.cs:line 24
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.SyncTextWriter.Write(String value)
   at Microsoft.DotNet.Cli.Utils.AnsiConsole.Write(String message) in /opt/code/src/Microsoft.DotNet.Cli.Utils/AnsiConsole.cs:line 143
   at Microsoft.DotNet.Cli.Utils.AnsiConsole.WriteLine(String message) in /opt/code/src/Microsoft.DotNet.Cli.Utils/AnsiConsole.cs:line 59
   at Microsoft.DotNet.Cli.Utils.Reporter.WriteLine(String message) in /opt/code/src/Microsoft.DotNet.Cli.Utils/Reporter.cs:line 55
   at Microsoft.DotNet.Tools.Test.Utilities.TestCommand.WriteLine(String line) in /opt/code/test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs:line 207
   at Microsoft.DotNet.Cli.Utils.StreamForwarder.WriteBuilder() in /opt/code/src/Microsoft.DotNet.Cli.Utils/StreamForwarder.cs:line 93
   at Microsoft.DotNet.Cli.Utils.StreamForwarder.Read(TextReader reader) in /opt/code/src/Microsoft.DotNet.Cli.Utils/StreamForwarder.cs:line 72
   at System.Threading.Tasks.Task.Execute()
```

## Environment data

Built from commit https://github.com/dotnet/cli/commit/eb8e0cfa409d2ef89091f2058487be0e48e8a32e

**Comment by livarcocc** [comment]
I believe we have gotten rid of this flakiness. We are still hitting two others: deps.json for tool missing and some .tam file issues. But this one is taken care of.
