### ISSUE TITLE
publish-iis command errors when migrating: 1.0.1 with project.json to 1.1 with csproj

### ISSUE THREAD

**Issue by mdmoura** [dotnet/cli#4855]
## Steps to reproduce
I migrated an ASP.NET Core 1.0.1 with project.json to ASP.NET Core 1.1 with .csproj and got:

    <Target Name="PostpublishScript" AfterTargets="Publish" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
      <Exec Command="dotnet publish-iis --publish-folder $(TargetDir) --framework $(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)" />
    </Target>

## Actual behavior

When I publish the application I get the following errors:

      Configuring the following project for use with IIS: 'C:\...\MvcProj\bin\Debug\netcoreapp1.1\'
      No web.config found. 
      Could not find file 'C:\...\MvcProj\project.json'.
      System.IO.FileNotFoundException: Could not find file 'C:\...\MvcProj\project.json'.
      File name: 'C:\...\MvcProj\project.json'
         at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
         at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream pare
nt)
         at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
         at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.GetProjectContext(String applicationBasePath, String framework)
         at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
         at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
         at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
         at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

    .NET Command Line Tools (1.0.0-preview4-004124)

    Product Information:
     Version:            1.0.0-preview4-004124
     Commit SHA-1 hash:  eb8e0cfa40

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.10586
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004124

What am I missing?

**Comment by GuardRex** [comment]
Tools don't work with csproj yet. More important tho for this particular case, `Microsoft.NET.Sdk.Web` takes over for `publish iis` ... it's gone now ... so you can remove it from your project.

Check out the comments in https://github.com/aspnet/IISIntegration/pull/299

**Comment by livarcocc** [comment]
Yep, publish-iis does not exist in CSProj.

We have a bug tracking removing the post publish script action for it. We are no longer migrating the package.
