### ISSUE TITLE
VSTestXunitDesktopAndNetCore.csproj locked to old Microsoft.Net.Sdk

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4892]
@Faizan2304 FYI, perhaps you can fix?

We are trying to move CLI repo to a common Microsoft.Net.Sdk version. VSTestXunitDesktopAndNetCore.csproj is currently at version 1.0.0-alpha-20161026-2. Moving it forward to 1.0.0-alpha-20161104-2 causes a failure:

```
  Failed   Microsoft.DotNet.Cli.Test.Tests.GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.XunitMultiTFM
  
DOTNETTEST : error Message:  [D:\j\workspace\debug_windows---54dcb9ec\build\test\RunTest.proj]
   Expected string "Build started, please wait...\r\nD:\j\workspace\debug_windows---54dcb9ec\.nuget\packages\microsoft.net.sdk\1.0.0-alpha-20161104-2\build\Microsoft.NET.RuntimeIdentifierInference.targets(45,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [D:\j\workspace\debug_windows---54dcb9ec\test\dotnet-test.Tests\bin\Debug\netcoreapp1.0\XunitMultiTFM\VSTestXunitDesktopAndNetCore\VSTestXunitDesktopAndNetCore.csproj]\r\n" to contain "Total tests: 3. Passed: 2. Failed: 1. Skipped: 0.".
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in D:\Workspaces\FluentAssertions\Src\Shared\Execution\LateBoundTestFramework.cs:line 23
     at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in D:\Workspaces\FluentAssertions\Src\FluentAssertions.Dotnet\Execution\TestFrameworkProvider.cs:line 38
     at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in D:\Workspaces\FluentAssertions\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
     at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in D:\Workspaces\FluentAssertions\Src\Core\Execution\AssertionScope.cs:line 197
     at FluentAssertions.Primitives.StringAssertions.Contain(String expected, String because, Object[] reasonArgs) in D:\Workspaces\FluentAssertions\Src\Core\Primitives\StringAssertions.cs:line 620
```

The test asset or test should be updated to pass when the Microsoft.Net.Sdk version is set to $(CLI_NETSDK_Version)

**Comment by pvlakshm** [comment]
@Faizan2304, @codito can you take a look please? It looks like a bug.
