### ISSUE TITLE
dotnet pack uses wrong path for obj artifact and fails on Preview5

### ISSUE THREAD

**Issue by Antaris** [dotnet/cli#4965]
Executing `dotnet pack` in a project directory with a P2P dependency tries to pack using an incorrect artifact path:

```
error MSB4018: The "PackTask" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: File not found: 'C:\bitbucket\fx\Fx-Core\src\Fx.Core\obj\Debug\Fx.Core.dll'.
error MSB4018:    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
error MSB4018:    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
error MSB4018:    at NuGet.Commands.MSBuildProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage()
error MSB4018:    at NuGet.Build.Tasks.Pack.PackTask.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() 
```

My project file is as such:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <Import Project="..\..\SharedProperties.props" />
  <PropertyGroup Label="Configuration">
    <RootNamespace>Fx</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <Description>Core library</Description>
    <Copyright>Fresh Egg Limited</Copyright>
    <AssemblyTitle>FX: Core</AssemblyTitle>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyName>Fx.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <Compile Include="..\..\SharedVersionInfo.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authorization">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyModel">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Composite">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="NETStandard.Library">
      <Version>1.6.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fx.Common\Fx.Common.csproj" />
    <ProjectReference Include="..\Fx.Core.Abstractions\Fx.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Fx.Data.Abstractions\Fx.Data.Abstractions.csproj" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

The generated spec file is as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Fx.Core</id>
    <version>1.0.0</version>
    <authors>Fx.Core</authors>
    <owners>Fx.Core</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Core library</description>
    <copyright>Fresh Egg Limited</copyright>
    <dependencies>
      <group targetFramework=".NETStandard1.6">
        <dependency id="Fx.Common" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="Fx.Core.Abstractions" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="Fx.Data.Abstractions" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Authentication" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Authorization" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Diagnostics" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Mvc" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.StaticFiles" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.EntityFrameworkCore" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Configuration.Binder" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Configuration.Json" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.DependencyModel" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.FileProviders.Composite" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.FileProviders.Embedded" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.PlatformAbstractions" version="1.1.0" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="C:\bitbucket\fx\Fx-Core\src\Fx.Core\obj\Debug\netstandard1.6\Fx.Core.dll" target="lib\netstandard1.6\Fx.Core.dll" />
    <file src="C:\bitbucket\fx\Fx-Core\src\Fx.Core\obj\Debug\Fx.Core.dll" target="lib\Fx.Core.dll" />
  </files>
</package>
```

Observations:

1. If I attempt to `dotnet pack` my `Fx.Common` project which has no P2P dependencies, it packs fine.
2. If I attempt to pack any of my other projects which have P2P dependencies, the pack fails.
3. The `pack` command looks to be looking for `/obj/{Configuration}/{OutputFilename}.dll` instead of `/obj/{Configuration}/{Framework}/{OutputFilename}.dll`.
4. There are two references to `Fx.Core.dll` in the spec file, is this correct?

## Environment data

```
.NET Command Line Tools (1.0.0-preview5-004226)

Product Information:
 Version:            1.0.0-preview5-004226
 Commit SHA-1 hash:  7b109e4b53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004226
```

**Comment by livarcocc** [comment]
@joelverhagen Can you take a look?

**Comment by piotrpMSFT** [comment]
@rohit21agrawal ?

**Comment by rohit21agrawal** [comment]
This looks like a msbuild issue because nuget just gets the DLL paths from the BuiltProjectGroupt output msbuild target,  but I'll confirm this tomorrow or by Monday , and take the appropriate action.

**Comment by piotrpMSFT** [comment]
thanks!

**Comment by rohit21agrawal** [comment]
@piotrpMSFT @Antaris  I tried to build a similar repro project with the latest version of dotnet pack, and i didn't see any issues. I have attached my project here:

[Fx.Core.zip](https://github.com/dotnet/cli/files/646922/Fx.Core.zip)

**Comment by Antaris** [comment]
@rohit21agrawal 

When I try and pack your test `Fx.Core` project, I get this:

```
error MSB4057: The target "pack" does not exist in the project.
```

**Comment by rohit21agrawal** [comment]
@antaris did you restore first?

**Comment by Antaris** [comment]
Ha, no I didn't, but on attempting to do so yields this:

```
error : Unable to resolve 'NuGet.Build.Tasks.Pack (>= 4.0.0-zlocal)' for '.NETStandard,Version=v1.6'. [C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\Fx.Core.csproj]
  Generating MSBuild file C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Common\obj\Fx.Common.csproj.nuget.g.targets.
  Generating MSBuild file C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Common\obj\Fx.Common.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Common\obj\project.assets.json
  Restore completed in 872.4526ms for C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Common\Fx.Common.csproj.
  Generating MSBuild file C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\obj\Fx.Core.csproj.nuget.g.targets.
  Generating MSBuild file C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\obj\Fx.Core.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\obj\project.assets.json
  Restore failed in 1290.8101ms for C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\Fx.Core.csproj.

  Errors in C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\Fx.Core.csproj
      Unable to resolve 'NuGet.Build.Tasks.Pack (>= 4.0.0-zlocal)' for '.NETStandard,Version=v1.6'.

  NuGet Config files used:
      C:\Users\abbottm\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by rohit21agrawal** [comment]
@antaris yes, one that was built out of dev branch.  You can just remove the package reference from the csproj file and use the latest sdk and dotnet.exe instead

**Comment by piotrpMSFT** [comment]
@Antaris did @rohit21agrawal's suggestion fix this issue for you? Can we close?

**Comment by Antaris** [comment]
@rohit21agrawal @piotrpMSFT 

Sorry for the late reply on this. I've installed the `1.0.0-preview5-004274` and this still does not work:

```
warning MSB4011: "C:\Users\abbottm\.nuget\packages\nuget.build.tasks.pack\4.0.0-rc-2048\build\NuGet.Build.Tasks.Pack.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\1.0.0-preview5-004275\Microsoft.Common.CurrentVersion.targets (5646,3)". This is most likely a build authoring error. This subsequent import will be ignored.
error MSB4018: The "PackTask" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: File not found: 'C:\Users\abbottm\Downloads\Github\Fx.Core\Fx.Core\Fx.Core\obj\x64\Debug\Fx.Core.dll'.
error MSB4018:    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
error MSB4018:    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
error MSB4018:    at NuGet.Commands.MSBuildProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage()
error MSB4018:    at NuGet.Build.Tasks.Pack.PackTask.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

The only modification I have made, is to remove the local `NuGet.Build.Tasks.Pack (>= 4.0.0-zlocal)` package from the project file.

**Comment by piotrpMSFT** [comment]
@rohit21agrawal ?

**Comment by piotrpMSFT** [comment]
@Antaris if this seems blocked, it will likely get much better traction in the nuget/home repo. CLI is just a delivery mechanism and having the issue open here is likely reducing visibility from the nuget folks...

**Comment by Antaris** [comment]
@piotrpMSFT This problem seems to have disappeared now I am using `1.0.0-preview5-004275`, closing.

**Comment by Jose-CF** [comment]
Experiencing same issue... 2.0.0-preview1-005977
