### ISSUE TITLE
dotnet-publish forgets System.Native.so on Ubuntu 14.04

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#505]
Clone https://github.com/andschwa/System.Native.so

Build with `./build.sh` on an Ubuntu 14.04 system.

While `dotnet-run` works, `dotnet-publish` forgets to include `System.Native.so`, and thus fails.

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'System.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Sys.Stat(String path, FileStatus& output)
   at System.IO.UnixFileSystem.DirectoryExists(String fullPath)
   at System.IO.Directory.Exists(String path)
   at Program.Main()
Aborted (core dumped)
```

**Comment by andschwa** [comment]
@piotrpMSFT @anurse Any clue on this? It's quite annoying to have to manually deploy (yet another) patch to my publish folder. Or is there an alternative to `dotnet-publish` that will give me a flat list of all my dependencies?

**Comment by andschwa** [comment]
The package [`runtime.ubuntu.14.04-x64.runtime.native.system`](https://www.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.14.04-x64.runtime.native.System) pulls in the `System.Native.so` that I need to use, but I can't find the correct package to depend on that would depend on this in a platform-agnostic way. `Microsoft.NETCore.Runtime.Native` didn't do it.

For what it's worth, by directly depending on `runtime.ubuntu.14.04-x64.runtime.native.system`, the `System.Native.so` gets published.

/cc @brthor

**Comment by andschwa** [comment]
Thanks @brthor: this is better solved by depending on `"NETStandard.Library": "1.0.0-rc2-23616"` (which should pull in, but doesn't: `"Microsoft.NETCore.Platforms": "1.0.1-rc2-23616"`).
