### ISSUE TITLE
dotnet build fails to build desktop targeting projects with satellite resx files

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#5171]
## Steps to reproduce
1. Create a new project and change it to target `net451`
2. Add a culture specific resx file (for instance Test.fr-FR.resx):
<details>
<summary>Sample resx file content</summary><p>

```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="Hello" xml:space="preserve">
    <value>Bonjour from Test in root folder</value>
  </data>
</root>
```
</p>
</details>

3. Restore and build the project

## Expected  behavior
Project builds

## Actual behavior
Build fails:
```
error MSB4018: The "GenerateSatelliteAssemblies" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not find file 'D:\temp\resx-test\resx-test\System'.
error MSB4018: File name: 'D:\temp\resx-test\resx-test\System'
error MSB4018:    at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
error MSB4018:    at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
error MSB4018:    at System.IO.File.OpenRead(String path)
error MSB4018:    at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
error MSB4018:    at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateSatelliteAssemblies.<>c.<ExecuteCore>b__16_1(String reference)
error MSB4018:    at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
error MSB4018:    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
error MSB4018:    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
error MSB4018:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
error MSB4018:    at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
error MSB4018:    at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
error MSB4018:    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission)
error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateSatelliteAssemblies.ExecuteCore()
error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
@srivatsn @nguerrera @dsplaisted I remember seeing something related to this in the SDK repo already.

**Comment by pranavkm** [comment]
Looks like it's a dup of https://github.com/dotnet/sdk/issues/518.

**Comment by nguerrera** [comment]
@pranavkm Yes. Closing as such.

**Comment by nguerrera** [comment]
This was fixed by https://github.com/dotnet/sdk#507 but the CLI is not up to date with that. This needs an SDK update in order to be resolved for CLI users.

@livarcocc @piotrpMSFT @srivatsn

**Comment by pranavkm** [comment]
Thanks! It would be great if we could get a build of the CLI + SDK that also addresses https://github.com/dotnet/cli/issues/5172.

**Comment by livarcocc** [comment]
I am updating the SDK version in the CLI. The PR will be out soon. Just testing it out locally.

**Comment by livarcocc** [comment]
https://github.com/dotnet/cli/pull/5193

**Comment by Faizan2304** [comment]
I am seeing this issue repro on latest dotnet 
.NET Command Line Tools (1.0.0-preview5-004478)

Product Information:
 Version:            1.0.0-preview5-004478
 Commit SHA-1 hash:  4d3e2872fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\faahmad\Desktop\dotnet-dev-win-x64.latest\sdk\1.0.0-preview5-004478

**Comment by Faizan2304** [comment]
Ignore last comment: My bad. Things are working fine. I was using old Microsoft.Net.sdk
