### ISSUE TITLE
Invalid character in path running dotnet ef

### ISSUE THREAD

**Issue by divega** [dotnet/cli#5317]
_From @veb128 on January 3, 2017 2:14_

After installing Visual Studio 2017 RC running the command 'dotnet ef' results in an error of:

Illegal characters in path.
Parameter name: path

I don't know what path it is referring to or how to correct it.

_Copied from original issue: aspnet/EntityFramework#7339_

**Comment by divega** [comment]
_From @bricelam on January 3, 2017 17:48_

Does specifying `--verbose` provide any additional context?

**Comment by divega** [comment]
_From @veb128 on January 3, 2017 21:26_

Well, that got me some more information but I'm still not clear as to what path it is referring to as having an illegal character.

Telemetry is: Enabled
projetfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\1.0.0-preview4-004
233\MSBuild.dll
projetfactory: MSBuild project path = C:\Users\vbrown\Documents\Visual Studio 20
15\Projects\dotnetcore\ORCCore.SQLite\Core2ORCC.csproj
projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
projecttoolscommandresolver: failed to resolve commandspec from library.
System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.<>c__DisplayClass7_0.<GetCo
mmandPath>b__2(String p, String s)
   at System.Linq.Enumerable.<JoinIterator>d__78`4.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String comma
ndName, String[] extensions)
   at Microsoft.DotNet.Cli.Utils.PathCommandResolver.ResolveCommandPath(CommandR
esolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.AbstractPathBasedCommandResolver.Resolve(Comman
dResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolve
rArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandR
esolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuG
etFramework framework, String configuration, String outputPath, String applicati
onName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandRe
solverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework,
String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`
1 args, NuGetFramework framework, String configuration, String outputPath, Strin
g applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemet
ryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by divega** [comment]
_From @bricelam on January 4, 2017 17:3_

From the stack trace, this looks like a bug for the [dotnet/cli](https://github.com/dotnet/cli) repo. Could you  [submit a new issue](https://github.com/dotnet/cli/issues/new) there so they can follow up?

**Comment by livarcocc** [comment]
@divega What is your environment like? Can you share that? Like, path to dotnet, path to your csproj and version of the CLI that you are using?

**Comment by divega** [comment]
@livarcocc you want to ask @veb128. I just copied the issue from the EF Core repo.

**Comment by wddot** [comment]
@divega have you looked at your actual Path environmental variable.  I was working through this same issue and discovered one of my entries in my Path statement had two issues

1. Quotation marks in one of the entries
2. Same entry was pointing to an invalid directory

I deleted the entry and was able to move on.

**Comment by divega** [comment]
@wddot you want to ask @livarcocc who is the actual customer who reported the issue. I only moved from another repo.

**Comment by milleniumbug** [comment]
I had the same issue. One of the entries in `%PATH%` for Octave had a carriage return. Since it wasn't visible, the issue wasn't immediately obvious.

**Comment by livarcocc** [comment]
I am not sure what else we can do in this case. In the past, this has always been the case: some invisible character in the PATH or path causing issues. However, unfortunately the APIs available do not tell us what character is the culprit.

**Comment by dvdobrovolskiy** [comment]
Having same issue. Checked Path many times - all normal

c:\Users\dima\source\repos\TNPK\TNPK>dotnet script --version --verbose
System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.<>c__DisplayClass7_0.<GetCommandPath>b__2(String p, String s)
   at System.Linq.Enumerable.<JoinIterator>d__81`4.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String commandName, String[] extensions)
   at Microsoft.DotNet.Cli.Utils.PathCommandResolver.ResolveCommandPath(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.AbstractPathBasedCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
