### ISSUE TITLE
VS 2017 migration fails if projects aren't in optimal order in the solution file

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5363]
## Steps to reproduce
1. Download and unzip [test-project-migrate.zip](https://github.com/dotnet/cli/files/712110/test-project-migrate.zip).
2. Open `test-project-migrate\test-project.sln` in VS 2017 RC.

## Expected  behavior
Project migrates successfully

## Actual behavior
Project migration fails with the following problem:

```
src\test-project\test-project.xproj: Migration failed.

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\DustinCa\Documents\Visual Studio 2015\Projects\test-project-migrate\src\test-library\project.json'.

at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.ReadProject(String projectPath, ProjectReaderSettings settings)
at Microsoft.DotNet.Internal.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
at Microsoft.DotNet.ProjectJsonMigration.ProjectDependencyFinder.<ResolveProjectDependencies>d__0.MoveNext()
at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.ResolveTransitiveClosureProjectDependencies(String rootProject, String xprojFile, SlnFile solutionFile)
at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass28_0.<Run>b__0()
at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

If you open the .sln file and swap `test-library` and `test-project`, migration will succeed.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004527)

Product Information:
 Version:            1.0.0-rc4-004527
 Commit SHA-1 hash:  49c2a4b6b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15007
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004527
```

**Comment by livarcocc** [comment]
This has been fixed in RC3 yesterday by https://github.com/dotnet/cli/pull/5352.

**Comment by DustinCampbell** [comment]
woo-hoo! Awesome!

**Comment by flieks** [comment]
i'm having the same error
```
Migration failed.

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\gebruiker\Documents\projects\QDV TRUNK\Dispatcher\project.json'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.ReadProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at Microsoft.DotNet.ProjectJsonMigration.ProjectDependencyFinder.<ResolveProjectDependencies>d__0.MoveNext()
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.ResolveTransitiveClosureProjectDependencies(String rootProject, String xprojFile, SlnFile solutionFile)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass35_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

C:\Users\gebruiker\Documents\projects\QDV TRUNK>dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```
