### ISSUE TITLE
Missing option value is causing donet build to crash

### ISSUE THREAD

**Issue by velyo** [dotnet/cli#5454]
## Steps to reproduce
- open dotnet CLI
- run `dotnet build -v`  (without value for verbosity option)

## Expected  behavior
- to apply a default value or show usage info

## Actual behavior
- it crashes with error dialog "dotnet has stopped working"

## Stack Trace
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.ParseOption(Boolean isLongOption, CommandLineApplication command, String[] args, Int32& index, CommandOption& option)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004578)

Product Information:
 Version:            1.0.0-rc4-004578
 Commit SHA-1 hash:  93a94e652b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004578
```

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/5295.
