### ISSUE TITLE
Running dotnet new in a folder with inaccessible folders causes CLI to crash. 

### ISSUE THREAD

**Issue by vsccarl** [dotnet/cli#5523]
## Steps to reproduce
1. Install d15prerel\26130.0 with no workloads
2. Install dotnet cli 
3. Open command prompt, navigate to the documents folder,
4. run dotnet new

## Expected  behavior
Creates a new project without crashing dotnet

## Actual behavior
```
C:\Users\v-sccarl\Documents>dotnet new

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 5436 ms
Expanding 100% 40643 ms

Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\v-sccarl\Documents\My Music' is denied.
   at System.IO.Win32FileSystemEnumerableIterator`1.HandleError(Int32 errorCode, String path)
   at System.IO.Win32FileSystemEnumerableIterator`1.AddSearchableDirsToList(PathPair localSearchData)
   at System.IO.Win32FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.DotNet.Tools.New.NewCommand.ReplaceFileTemplateNames(String projectDirectory)
   at Microsoft.DotNet.Tools.New.NewCommand.CreateEmptyProject(String languageName, String templateName)
   at Microsoft.DotNet.Tools.New.NewCommand.<>c__DisplayClass2_0.<Run>b__4()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.New.NewCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004707)

Product Information:
 Version:            1.0.0-rc4-004707
 Commit SHA-1 hash:  5aded80a7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004707
```

**Comment by piotrpMSFT** [comment]
@vsccarl can you try this with `dotnet new3`? we're about to replace the `dotnet new` implementation with `new3`.

@mlorbetske FYI

**Comment by vsccarl** [comment]
@piotrpMSFT It does not repro when using `dotnet new3`

**Comment by piotrpMSFT** [comment]
#5430 replaced new with new3, so this has been resolved :)
