### ISSUE TITLE
dotnet run after project migration crashes dotnet

### ISSUE THREAD

**Issue by vsccarl** [dotnet/cli#5524]
## Steps to reproduce
1. Install d15prerel\26130.0 with no workloads
2. Install dotnet cli 
3. Download and extract [Bala's test repo](https://github.com/balaTest/ProjectKTestProjects)
4. In a prompt navigate to `\ProjectKTestProjects-master\Dev14_K101\Tooling202\ConsoleAppOnCore_1`
5. dotnet migrate
6. dotnet restore - dotnet build - dotnet run

## Expected  behavior
The project starts running

## Actual behavior
dotnet crashes 

```
C:\Users\v-sccarl\Documents\ProjectKTestProjects-master\Dev14_K101\Tooling202\AspNetCoreWeb_IndAuth_WithAI_1>dotnet run

Unhandled Exception: System.InvalidOperationException: Couldn't find a project to run. Ensure a project exists in  C:\Users\v-sccarl\Documents\ProjectKTestProjects-master\Dev14_K101\Tooling202\AspNetCoreWeb_IndAuth_WithAI_1.
Or pass the path to the project using --project
   at Microsoft.DotNet.Tools.Run.RunCommand.Initialize()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004707)

Product Information:
 Version:            1.0.0-rc4-004707
 Commit SHA-1 hash:  5aded80a7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004707
```

**Comment by piotrpMSFT** [comment]
@jonsequitur  can you address this while fixing #5422?

**Comment by jonsequitur** [comment]
![image](https://cloud.githubusercontent.com/assets/547415/22450349/c962425c-e71a-11e6-86f4-efeb2266b5e3.png)

@piotrpMSFT The change I made fixes this as well.

**Comment by irowbin** [comment]
From visual studio 2017 in debug/release mode running but after publishing the project, these errors are occurring. Can anyone help me here please?
![capture](https://cloud.githubusercontent.com/assets/13050078/24965306/5fe3819c-1fc3-11e7-846c-2c3fb717cb87.PNG)

**Comment by livarcocc** [comment]
To run a published app you don't use dotnet run. Dotnet run is a development tool and you need to use it by specifying a csproj or by running it from a folder containing a csproj.

For published apps, if it is a portable app, you run it by doing dotnet <path_to_your_app_dll>. Or, if it is a self-contained app, you simply invoke <your_app>.[exe].

**Comment by katebutenko** [comment]
@livarcocc  thanks for explanation, saved me from banging my head against the wall too much. 

Just in case someone comes across this thread looking for an answer how to make it run on Azure App (and have limited ability to test publish before production publish). Correct me if I'm wrong, cause I kinda figured this out.

When you publish to Azure, you don't need to run anything, if you have this line in web.config:

<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>

Upon publish, this line gets replaced with:

<aspNetCore processPath="dotnet" arguments=".\NameOfYourMainDLL.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />

And in this way Azure webserver knows what to run when you request the website. Basically it becomes equivalent to running "dotnet NameOfYourMainDLL.dll" in console when you test publish locally.

**Comment by irowbin** [comment]
That works for me @livarcocc  Thanks.
