### ISSUE TITLE
dotnet ef throws exception System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by DennisBaekgaard** [dotnet/cli#5606]
## Steps to reproduce
run dotnet ef in the command line. I suspect it *might* have something to do with a previous attempt at upgrading to VS2017, but then reverting back to VS2015.

## Expected  behavior
Being able to work with any of the dotnet ef commands (migrations etc.)

## Actual behavior
Throws the following exception no matter what:
```
Unhandled Exception: System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.<>c__DisplayClass7_0.<GetCommandPath>b__2(String p, String s)
   at System.Linq.Enumerable.<JoinIterator>d__80`4.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String commandName, String[] extensions)
   at Microsoft.DotNet.Cli.Utils.PathCommandResolver.ResolveCommandPath(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.AbstractPathBasedCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64


```

I have tried reinstalling my .NET Core SDK / CLI tools and cleaning the old lingering versions out. I have tried reinstalling the VS tools as well to no avail. The exception happens both through Visual Studio and the command line.  Enabling --verbose yields nothing additional from the exception above.

**Comment by mudasar** [comment]
I have the same issue installed VS 2017 and VS is working fine but this exception out of no where making me mad :( . 

`
Unhandled Exception: System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.<>c__DisplayClass7_0.<GetCommandPath>b__2(String p, String s)
   at System.Linq.Enumerable.<JoinIterator>d__80`4.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String commandName, String[] extensions)
   at Microsoft.DotNet.Cli.Utils.PathCommandResolver.ResolveCommandPath(CommandResolverArguments commandResolverArgument
s)
   at Microsoft.DotNet.Cli.Utils.AbstractPathBasedCommandResolver.Resolve(CommandResolverArguments commandResolverArgume
nts)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, Str
ing commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicati
onName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnume
rable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String
 configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)`


`Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771`

**Comment by piotrpMSFT** [comment]
@bricelam are you familiar with this issue?

**Comment by bricelam** [comment]
Looks like #5317. Never got to the bottom of it. No EF in the stack...

**Comment by DennisBaekgaard** [comment]
Has anyone heard of a work around? It's kind of a bitch to deal with unfortunately. I tried reinstalling to no avail, and I removed VS2017. Any ideas as to how to fix it / help with debugging and I will try it out. 

I'll keep trying to figure out if I can dig up more information for you.

**Comment by livarcocc** [comment]
@DennisBaekgaard Any chance you can share what your filesystem looks like when you are trying to execute the failing command?

**Comment by DennisBaekgaard** [comment]
Sure. My structure is as follows. My root dir (and solution dir) contains a few projects, the API (containing controllers) and Domain (containing models, view models, queries / commands and my **scheme files**).  My migrations (the ones created before it broke) are in the API project. Beside this there exists some other projects like my tests and a few disjoint helper projects.

The directory hierarchy looks like this:

Root
   - API
       - Controllers
           * _Controller1.cs_
           * _Controller2.cs_
           _...._
        - Migrations
           * _20161026125103_Initial.cs_
           * _20161026125103_Initial.Designer.cs_
           * _InsightsContextModelSnapshot.cs_
        - Properties
        - Service References
        * _Program.cs_
        * _project.json_
        * _Startup.cs_
        * _web.config_
   - Domain
      - Queries 
        * _All my queries to the database_ 
      - Commands 
        * _All my commands to the database_ 
      - Models
        - JoinTables (models to describe Many To Many relations)  
            * _mtm_model1.cs..._
        * _model1.cs_
        * _model2.cs_
        _..._
      - View Models
        - _All view models_
      - Schemas
        * _All my schema cs files which describes the database_
        
If you want more images let me know.

![API](https://cloud.githubusercontent.com/assets/1562331/22921502/4dad4fe0-f29a-11e6-8905-56245fabca28.png)

![Domain](https://cloud.githubusercontent.com/assets/1562331/22921512/58788d04-f29a-11e6-88cf-503c3b928d36.png)

**Comment by DennisBaekgaard** [comment]
@livarcocc So I managed to find a solution to this, but I'm not sure how I got there. I've managed to install VS2017 RC, then I uninstalled dotnet CLI and reinstalled it. Now it gives me the above error in the root if the solution, but if I navigate to the API project it will work. So I guess it looks for some files/folders relative to the dir the command is run, and it only finds them in the project which actually contains them. 

I am *pretty* sure that I got the illegal path error in the API dir as well before, but I've had so many attempts at fixing this I don't recall for sure anymore. 

Anywho, to anyone who experience this:
**1.** Make sure that you are in the correct directory when you run `dotnet ef`
**2.** If it doesn't work, uninstall the CLI.
**3.** Installl VS2017 RC
**4.** Install the CLI again

**Comment by streamtree** [comment]
I'm also experiencing this issue with the latest version of VS2017 and dotnet 1.0.4. Same stack trace as OP. 

.NET Command Line Tools (1.0.4)

```
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by ivnext** [comment]
I hit this issue and chased it down to having otherwise "invalid path" characters supplied to the migration name (-Name) parameter of the Add-Migration command. For example, if in the migration name I supplied a comment such as: "Added a DBSet<>...", I would see this error. After removing the '<>', the error goes away. This was with EF Core 1.1.2, and I was using the Package Manager Console. 

I have not had time to dig much deeper, but perhaps someone on the EF team would know where there are path or psuedo path related operations related to the string supplied to the -Name parameter.

**Comment by livarcocc** [comment]
@dvdobrovolskiy Could you share the contents of your PATH environment variable? In the past, when we saw this, it was usually because of some garbage present in that env variable.

**Comment by bharathkumarkolathur** [comment]
@livarcocc  I see the same issue  and  here is contents of PATH environment variable

C:\Program Files\Git\cmd;C:\Users\kumar1\.dnx\bin;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8;C:\Users\kumar1\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Users\kumar1\.dotnet\tools



[6/14/2018 2:36:13 PM Informational] ------ Run test started ------
[6/14/2018 2:36:13 PM Error] System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.TryGetExecutablePath(String executableBaseName, String& executablePath)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.GetDotnetPath()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[6/14/2018 2:36:13 PM Error] System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.TryGetExecutablePath(String executableBaseName, String& executablePath)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.GetDotnetPath()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[6/14/2018 2:36:13 PM Informational] ========== Run test finished: 0 run (0:00:00.094729) ==========

**Comment by oofpez** [comment]
I have this problem too.

My PATH variable is

C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft Solver Foundation\3.0.2.10889\Plugins;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\ProgramData\chocolatey\bin;C:\tools\python2;C:\Program Files\nodejs\;C:\Users\JanSchoeman\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Users\JanSchoeman\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin;C:\Program Files\Microsoft DNX\Dnvm\;D:\Program Files\Microsoft SQL Server\130\Tools\Binn\;%Mongo%;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;D:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd

I tried removing the %Mongo% but that didn't help.  Perhaps it isn't the path variable?

**Comment by Heneman** [comment]
How has this been sitting around for 2 1/2 years? @livarcocc Any update on this?
