### ISSUE TITLE
Multiple versions added to DotNetCliToolReference Version attribute during migration

### ISSUE THREAD

**Issue by dtivel** [dotnet/cli#5632]
## Steps to reproduce
Please contact me (dtivel) privately for a repro solution.

## Actual behavior
**VS 2017 RC3**
![image](https://cloud.githubusercontent.com/assets/12734758/22757740/e6216f52-ee00-11e6-8f92-ff159ab7f511.png)

In the .csproj file is the following element:

    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.1.0-preview4-final;1.0.0-msbuild3-final" />

Error occurred while restoring NuGet packages: The operation failed as details for project JGUDirectory.DataAccess.Commands.Tests could not be loaded.

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: '1.1.0-preview4-final;1.0.0-msbuild3-final' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.GetVersionRange(IVsReferenceItem item)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToToolPackageSpec(ProjectNames projectNames, IVsReferenceItem item)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.<>c__DisplayClass14_0.<ToDependencyGraphSpec>b__0(IVsReferenceItem r)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToDependencyGraphSpec(ProjectNames projectNames, IVsProjectRestoreInfo projectRestoreInfo)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.NominateProjectAsync(String projectUniqueName, IVsProjectRestoreInfo projectRestoreInfo, CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.NuGetRestorer.<>c__DisplayClass17_0.<<ProjectPropertyChangedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: '1.1.0-preview4-final;1.0.0-msbuild3-final' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.GetVersionRange(IVsReferenceItem item)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToToolPackageSpec(ProjectNames projectNames, IVsReferenceItem item)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.<>c__DisplayClass14_0.<ToDependencyGraphSpec>b__0(IVsReferenceItem r)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToDependencyGraphSpec(ProjectNames projectNames, IVsProjectRestoreInfo projectRestoreInfo)
   at NuGet.SolutionRestoreManager.VsSolutionRestoreService.NominateProjectAsync(String projectUniqueName, IVsProjectRestoreInfo projectRestoreInfo, CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.NuGet.NuGetRestorer.<>c__DisplayClass17_0.<<ProjectPropertyChangedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---
```

## Environment data
`dotnet --info` output: 
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by livarcocc** [comment]
This is happening because you have both `Microsoft.EntityFrameworkCore.Tools.DotNet` and `Microsoft.EntityFrameworkCore.Tools` in your tools node in your PJ.

Migration moves Microsoft.EntityFrameworkCore.Tools to Microsoft.EntityFrameworkCore.Tools.DotNet, version 1.0.0-msbuild3-final, because Microsoft.EntityFrameworkCore.Tools is not a valid tool in the MSBuild world.

However, in this case, you also Microsoft.EntityFrameworkCore.Tools.DotNet with a different version and migration is not moving it to the right version, so you end up with the same tool specified twice with different version, which gets merged with the semicolon separation that you are seeing.

The fix here is for migration to also Microsoft.EntityFrameworkCore.Tools.DotNet to the correct version when it encounters it.

**Comment by livarcocc** [comment]
I preview2, there was no `Microsoft.EntityFrameworkCore.Tools.DotNet`, however for preview2-1, the EF tool package was split in two, so, anyone who is referencing EF tools packages higher than preview2 may get themselves in this situation.

**Comment by livarcocc** [comment]
We will update the version when we change migration to use the final packages versions.

**Comment by livarcocc** [comment]
Closing this as a dup of https://github.com/dotnet/cli/issues/5414 for now. It will get addressed.
