### ISSUE TITLE
latest build of dotnet cli crashes on new command

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/cli#5644]
```
D:\temp\dotnet-new>D:\nuget\NuGet.Client\cli_test\dotnet.exe new classlib
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Cli.New3Command.ParseTemplateArgs(ITemplateInfo templateInfo)
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterSingularTemplateManipulationFlowAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()
```

version of cli used : 1.0.0-rc4-4777

**Comment by livarcocc** [comment]
cc @mlorbetske 

I suspect you have to do a dotnet new --debug:reinit. Though, don't do that just yet, because mike may want to have a look.

**Comment by mlorbetske** [comment]
Yep, --debug:reinit is what you want, this will happen in cases where two different builds of the CLI have the same build number. We're working to make this more durable

**Comment by livarcocc** [comment]
@mlorbetske Do we have a bug at dotnet/templating that we can use to close this one against?

**Comment by mlorbetske** [comment]
Moved here: https://github.com/dotnet/templating/issues/294

**Comment by rohit21agrawal** [comment]
so what leads to  two different builds of CLI having the same build number?
