### ISSUE TITLE
ArgumentNullException thrown attempting to add auto-wrapped references to new Portable Class libraries

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#568]
_From @MattGal on July 23, 2015 1:35_

I may be among the first people trying to do this.  When I add project-to-project references with PCLs, I consistently see this in the package manager output window:

Wrapping project 'ProjectName' for '.NETPortable,Version=v5.0'
  Source c:\Users\mattgal\Documents\Visual Studio 2015\Projects\ReferenceKPCLWithDifferentName\SameName\SameName.csproj
  Target c:\Users\mattgal\Documents\Visual Studio 2015\Projects\ReferenceKPCLWithDifferentName\SameName\project.json
System.ArgumentNullException: Value cannot be null.
Parameter name: profileValue
   at NuGet.NetPortableProfile.Parse(String profileValue)
   at NuGet.VersionUtility.GetShortFrameworkName(FrameworkName frameworkName)
   at Microsoft.Framework.PackageManager.WrapCommand.GetShortFrameworkName(FrameworkName targetFramework)
   at Microsoft.Framework.PackageManager.WrapCommand.AddWrappedProjectPath(JObject projectJson, String relativeCsProjectPath, FrameworkName targetFramework)
   at Microsoft.Framework.PackageManager.WrapCommand.EmitProjectWrapper(XElement projectElement)
   at Microsoft.Framework.PackageManager.WrapCommand.WrapCsProject()
   at Microsoft.Framework.PackageManager.WrapCommand.ExecuteCommand()
   at Microsoft.Framework.PackageManager.WrapConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

_Copied from original issue: aspnet/dnx#2317_

**Comment by muratg** [comment]
_From @anurse on July 23, 2015 3:8_

It's definitely expected that this combination (`dnu wrap` and `dotnet`) would be a little broken. Thanks for the report though!

**Comment by muratg** [comment]
_From @davidfowl on July 23, 2015 3:32_

Net portable 5.0 is what's broken. We read the tfm from he project file.

**Comment by muratg** [comment]
_From @MattGal on July 23, 2015 17:1_

OK, will discuss with them.   There are quite a few challenges with trying to make this work currently.

**Comment by muratg** [comment]
_From @davkean on July 23, 2015 17:12_

This is by design; we no longer have profiles in the "dotnet" world.

**Comment by muratg** [comment]
Closing per @davkean's comment.

**Comment by muratg** [comment]
_From @davkean on December 15, 2015 21:37_

No, it's by design that portable doesn't have profiles - it's not by design that you crash when you encounter that.

**Comment by muratg** [comment]
Reopening per @davkean's comment.  :smile: 

@piotrpmsft I'll move this one as well.
