### ISSUE TITLE
ASP .NET Core Project Built in Windows , Published and Run in Docker throws System.BadImageFormatException

### ISSUE THREAD

**Issue by ckalan** [dotnet/cli#5843]
## Steps to reproduce
Create a new mvc app in windows (in a folder named WebApplication2) , build and publish in release mode

dotnet new mvc --platform netcoreapp1.1
dotnet restore
dotnet publish -c Release

CD to the publish directory and run the app:
dotnet WebApplication2.dll 

Build docker (linux) image from the published files using this Dockerfile:

FROM microsoft/dotnet:latest
ENV ASPNET_URLS "https://*:5000"
WORKDIR /webapp
COPY * ./
EXPOSE 5000
ENTRYPOINT ["dotnet", "WebApplication2.dll"]

Put the docker file in the publish director, CD to the publish directory and first run:
docker build -t myapp .

Run the docker image
docker run -it myapp

## Expected  behavior
When you run first time in windows, web app runs and it is accessible from http://localhost:5000
The docker scripts above generates a docker image named "myapp" and docker run command creates a container with .net1.1 runtime. Web application runs and you get the same result as it is when you run in windows. You can access the web app via http://localhost:5000

## Actual behavior
In windows, the behavior is just as it is expected.
But when you run the docker container, you get the following error:

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.MvcJsonMvcOptionsSetup.<>c__DisplayClass0_0.<.ctor>b__0(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.<>c.<AddMvcCoreServices>b__5_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication2.Program.Main(String[] args)

## Environment data
In windows:

.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

In linux, I couldn't try "dotnet --info" because the container dies immediately. But it must have the default value of the microsoft/dotnet:latest image.

**Comment by ckalan** [comment]
Most probable cause is the dynamic loading of assemblies by the ASP .NET Core MVC engine. What is strange is that, System.Runtime.Serialization.Primitives.dll file in the [publish root] folder is not the same file in the [publish root]/refs folder. I guess wrong version of the file is being loaded by the MVC from the refs folder.

**Comment by ckalan** [comment]
BTW, if you just create a clean container from the microsoft/dotnet:latest docker image and execute all the restore/publish steps within this container ( rather than executing them in Windows), then this error does not occur and the application runs as expected.

**Comment by piotrpMSFT** [comment]
@mlorbetske can you take a look?

**Comment by mlorbetske** [comment]
@ckalan to verify, in the working configuration, building/restoring/publishing the same project (same as the one that failed when trying from outside the container) from inside the container worked?

@glennc

**Comment by ckalan** [comment]
@mlorbetske Yes, as I mentioned in my comment. All process works as expected if executed in the docker container.

**Comment by livarcocc** [comment]
@ckalan Is this still reproing for you?

**Comment by livarcocc** [comment]
Closing this for now since we haven't heard back in over 2 months. Please, re-activate if this is still happening with the latest CLI.
