### ISSUE TITLE
`dotnet msbuild` commands hang with some command-line redirections

### ISSUE THREAD

**Issue by dougbu** [dotnet/cli#5849]
## Steps to reproduce
1. clone the [MVC repo](https://github.com/aspnet/Mvc) (https://github.com/aspnet/Mvc.git)
2. checkout the `dougbu/does.it.hang.yes.it.does` branch
3. initialize the build and restore everything: `.\build.cmd initialize`
4. either use `build.cmd` to compile (this involves wrapper / waiting `sake.exe` and `dotnet` processes) or run inner MsBuild command with stderr redirected. I.e. execute one of
  - `.\build.cmd build-compile`
  - `dotnet msbuild /nologo "C:\dd\dnx\Universe\Mvc\.build/makefile.proj" "/p:LifecycleType=Standard;Configuration=Debug" /t:Compile 2>build.err`

Have similar issues with `2>&1 |tee build.log`, `|tee build.log` or `2>&1` in the second case. The unadorned second command and that with `2>build.err >build.log` usually work fine.

## Expected  behavior
Build completes and exits cleanly.

Errors and warnings during the build are expected as well, especially MSB3277 due to .Microsoft/vstest#393 or perhaps because Mvc.Core project depends on Microsoft.Extensions.DependencyModel version `1.2.0-*` while the xUnit runner uses version `1.1.0`.

## Actual behavior
Commands hang consistently. (Hang may take some work in Task Manager due to dotnet/cli#4856.)

It's not predictable what project is last mentioned in `build.log`. But, hangs seem to occur when the build is near its end.

There's never just one `dotnet` process when hangs occur. Usually see the original command, the `dotnet exec` command (to invoke the latest copy of `dotnet.exe`), and at least one of the worker processes.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004883)

Product Information:
 Version:            1.0.0-rc4-004883
 Commit SHA-1 hash:  fa2c9e025c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004883
```

## Additional information
I have process dumps captured in Visual Studio and Task Manager. If they will help, contact me at my Microsoft email (same alias as here) and I'll share.

Problems appear specific to this branch. Command-line builds complete reliably in the `dougbu/migration` branch for example. I cleaned up some `dotnet migrate` artifacts in the `dougbu/migration` branch and the `*.sln` files are different. But, largest change is probably a fix that's only in the `dougbu/migration` branch to build just `Mvc.sln` and not all three solutions.

**Comment by dougbu** [comment]
FYI @Eilon this is the hang we discussed a couple of days back.

**Comment by dougbu** [comment]
Behaviour more consistent after I rebased `dougbu/does.it.hang.yes.it.does` to include latest from the Mvc `dev` branch. Problems now sometimes reproduce without redirects. Likely the redirects just change timings slightly and previously made races occur more often.

> But, largest change is probably a fix that's only in the `dougbu/migration` branch to build just Mvc.sln and not all three solutions.

I tested in the `dougbu/migration` branch after backing out that fix. No hangs.

**Comment by dougbu** [comment]
Just saw a message about `MSBuild_*.failure.txt` files written into `$env:temp`. These messages aren't normally output. But, I've got files for all or most hangs I've experienced this morning. Contents include
```
UNHANDLED EXCEPTIONS FROM PROCESS 16096:
=====================
2/27/2017 09:27:51
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.BackEnd.NodePacketTranslator.SerializedException.ToException(SerializedException serializedException)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.TranslateException(Exception& value)
   at Microsoft.Build.Execution.BuildResult.Microsoft.Build.BackEnd.INodePacketTranslatable.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.Translate[T](T& value)
   at Microsoft.Build.BackEnd.BuildRequestUnblocker.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.BuildRequestUnblocker.FactoryForDeserialization(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.Execution.OutOfProcNode.Microsoft.Build.BackEnd.INodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, Queue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```
and / or (or is much more common)
```
UNHANDLED EXCEPTIONS FROM PROCESS 16360:
=====================
2/27/2017 09:37:13
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target CoreBuild.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
===================
```

Of course, these failures should not result in hangs.

**Comment by dougbu** [comment]
This issue was moved to Microsoft/msbuild#1808
