### ISSUE TITLE
dotnet migrate hits an NRE when migrating a project with star dependency

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#5890]
## Steps to reproduce
1. git clone https://github.com/jaymedavis/stripe.net
2. dotnet migrate

## Expected  behavior
Migration works.

## Actual behavior
We hit a NRE in the migration code. The workaround for this issue is to replace the * versions with a version with at least a portion of it fixed.

```
at NuGet.Versioning.VersionRangeBase.Satisfies(NuGetVersion version, IVersionComparer comparer)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.<>c__DisplayClass11_0.<ToPackageDependencyInfo>b__2(VersionRange p) in /Users/livarcocc/Documents/git/cli/src/Microsoft.DotNet.ProjectJsonMigration/Rules/MigratePackageDependenciesAndToolsRule.cs:line 303
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.ToPackageDependencyInfo(ProjectLibraryDependency dependency, IDictionary`2 dependencyToVersionMap) in /Users/livarcocc/Documents/git/cli/src/Microsoft.DotNet.ProjectJsonMigration/Rules/MigratePackageDependenciesAndToolsRule.cs:line 303
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.MigrateDependencies(Project project, MigrationRuleInputs migrationRuleInputs, NuGetFramework framework, IEnumerable`1 dependencies, SlnFile solutionFile, ProjectItemGroupElement itemGroup) in /Users/livarcocc/Documents/git/cli/src/Microsoft.DotNet.ProjectJsonMigration/Rules/MigratePackageDependenciesAndToolsRule.cs:line 257
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs) in /Users/livarcocc/Documents/git/cli/src/Microsoft.DotNet.ProjectJsonMigration/Rules/MigratePackageDependenciesAndToolsRule.cs:line 54
   at Microsoft.DotNet.ProjectJsonMigration.Tests.TemporaryProjectFileRuleRunner.RunMigrationRulesOnGeneratedProject(IEnumerable`1 rules, IEnumerable`1 projectContexts, String testDirectory, ProjectRootElement xproj) in /Users/livarcocc/Documents/git/cli/test/Microsoft.DotNet.ProjectJsonMigration.Tests/TemporaryProjectFileRuleRunner.cs:line 77
   at Microsoft.DotNet.ProjectJsonMigration.Tests.TemporaryProjectFileRuleRunner.RunRules(IEnumerable`1 rules, String projectJson, String testDirectory, ProjectRootElement xproj) in /Users/livarcocc/Documents/git/cli/test/Microsoft.DotNet.ProjectJsonMigration.Tests/TemporaryProjectFileRuleRunner.cs:line 21
   at Microsoft.DotNet.ProjectJsonMigration.Tests.PackageDependenciesTestBase.RunPackageDependenciesRuleOnPj(String s, String testDirectory) in /Users/livarcocc/Documents/git/cli/test/Microsoft.DotNet.ProjectJsonMigration.Tests/Rules/PackageDependenciesTestBase.cs:line 57
   at Microsoft.DotNet.ProjectJsonMigration.Tests.GivenThatIWantToMigratePackagesToTheirLTSAndFTSVersions.ValidatePackageMigration(String sourcePackageName, String sourceVersion, String targetPackageName, String targetVersion) in /Users/livarcocc/Documents/git/cli/test/Microsoft.DotNet.ProjectJsonMigration.Tests/Rules/GivenThatIWantToMigratePackagesToTheirLTSAndFTSVersions.cs:line 287
   at 
```

## Environment data
`dotnet --info` output:

**Comment by MattGertz** [comment]
Let's have it handy, but unless we see that a lot of people are hitting this, we won't take it yet.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#20
