### ISSUE TITLE
Unhandled exception in `dotnet sln add` when argument isn't MSBuild-format

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/cli#5900]
When the argument given to `dotnet sln add` is not a valid MSBuild project, the CLI crashes with an unhandled exception originating from MSBuild.

## Steps to reproduce
`dotnet sln add <file that isn't a .csproj>`

## Expected  behavior
An error message explaining the problem and a failure exit code.

## Actual behavior
Unhandled exception with application-crash dialog (on Windows).

```
s:\work\dotnet-sln-add>dotnet new sln
Content generation time: 31.223 ms
The template "Solution File" created successfully.

s:\work\dotnet-sln-add>dotnet sln add dotnet-sln-add.sln

Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.  s:\work\dotnet-sln-add\dotnet-sln-add.sln ---> System.Xml.XmlException: Data at the root level is invalid. Line 2, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Microsoft.Build.Internal.XmlReaderExtension.GetXmlReader(StreamReader input, Encoding& encoding)
   at Microsoft.Build.Internal.XmlReaderExtension..ctor(String file)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.ThrowInvalidProjectFile(BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.<>c__DisplayClass199_0.<OpenProjectOrSolution>b__0(String path, ProjectRootElementCache cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile)
   at Microsoft.DotNet.Tools.Common.SlnFileExtensions.AddProject(SlnFile slnFile, String fullProjectPath)
   at Microsoft.DotNet.Tools.Sln.Add.AddProjectToSolutionCommand.Run(String fileOrDirectory)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.<>c__DisplayClass10_1.<RunCommand>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Sln.SlnCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
s:\work\dotnet-sln-add>dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by livarcocc** [comment]
@jonsequitur this seems to be along your alley.

**Comment by livarcocc** [comment]
Actually, maybe not, the stack is coming from MSBuild.

@rainersigwald What is your suggestion here? That we swallow this exception and display an appropriate message?

**Comment by rainersigwald** [comment]
Yeah, I think so. It seems reasonable to me for MSBuild to communicate this error back through an exception. But it's not too unusual from the CLI perspective to have user error pointing to a different type of file (my error was because I assumed the command line was `dotnet sln add solution-to-manipulate.sln project-to-add.csproj`).

**Comment by dyardyGIT** [comment]
What was the solution?
