### ISSUE TITLE
`dotnet cache` with no arguments crashes with Watson dialog

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#5956]
## Steps to reproduce
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.exe
Make a simple cache .csproj file
`dotnet cache`

## Expected  behavior
Not to get an Unhandled Exception and a Watson dialog.

## Actual behavior

```
Unhandled Exception: System.InvalidOperationException: Specify at least one entry with --entries.
   at Microsoft.DotNet.Tools.Cache.CacheCommand.<>c__DisplayClass1_0.<FromArgs>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Cache.CacheCommand.FromArgs(String[] args, String msbuildPath)
   at Microsoft.DotNet.Tools.Cache.CacheCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

![image](https://cloud.githubusercontent.com/assets/8291187/23716800/21a70dc8-03f7-11e7-8a82-d444639df6a6.png)

## Environment data
`dotnet --info` output:
```
F:\DotNetTest\CacheStuff>dotnet --info
.NET Command Line Tools (2.0.0-preview1-005383)

Product Information:
 Version:            2.0.0-preview1-005383
 Commit SHA-1 hash:  22816d7958

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\dotnet\sdk\2.0.0-preview1-005383\
```

**Comment by ramarag** [comment]
i believe this is the correct behavior, and it also displays the reason for the failure,. i.e

```Unhandled Exception: System.InvalidOperationException: Specify at least one entry with --entries.```

some thing similar happens if you invoke ```dotnet run``` without any project
```
Unhandled Exception: System.InvalidOperationException: Couldn't find a project to run. Ensure a project exists in  C:\Users\ramarag, or pass the path to the project using --project
   at Microsoft.DotNet.Tools.Run.RunCommand.Initialize()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

cc @livarcocc

**Comment by eerhardt** [comment]
> i believe this is the correct behavior

It is 100% not the correct behavior to display a Watson crash dialog.

**Comment by eerhardt** [comment]
Looks like someone broke `dotnet run`.  On `1.0.0`, we display a good error:

```
F:\DotNetTest>dotnet run
Couldn't find a project to run. Ensure a project exists in  F:\DotNetTest.
Or pass the path to the project using --project
```

But on `2.0.0-*` I get the Watson dialog.  This is because https://github.com/dotnet/cli/pull/5525 didn't make it's way up to master.  I'll log a separate issue for this.

**Comment by ramarag** [comment]
fixed by https://github.com/dotnet/cli/pull/5966
