### ISSUE TITLE
Invalid csproj causes dotnet sln to crash

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#6005]
## Steps to reproduce

1. Create a solution using `dotnet new sln`, and a project using `dotnet new classlib`.
1. In the csproj, add an `<Import />` statement pointing to a nonexistent targets file.
1. Try to add the project to the solution using `dotnet sln add`.

## Expected behavior

An error message should be emitted, or (better yet) the error is silently ignored and the project added to the solution anyways, as this is what .NET CLI used to do (before I updated to the version listed below).

## Actual behavior

An unhandled exception is thrown and .NET CLI hard-crashes (OS crash dialog appears)

## Environment data
```
.NET Command Line Tools (2.0.0-preview1-005390)

Product Information:
 Version:            2.0.0-preview1-005390
 Commit SHA-1 hash:  5cc689d07b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005390/
```

**Comment by blackdwarf** [comment]
@wjk this is interesting. Can you share the exception?

**Comment by wjk** [comment]
```
Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "/Volumes/Sources/Sunburst.WindowsShellAPI/src/TestProject/does.not.exist.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /Volumes/Sources/Sunburst.WindowsShellAPI/src/TestProject/TestProject.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile)
   at Microsoft.DotNet.Tools.Common.SlnFileExtensions.AddProject(SlnFile slnFile, String fullProjectPath)
   at Microsoft.DotNet.Tools.Sln.Add.AddProjectToSolutionCommand.Run(String fileOrDirectory)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.<>c__DisplayClass10_1.<RunCommand>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Sln.SlnCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/5900.
