### ISSUE TITLE
ArgumentNullException in ResolvePackagesPath

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#6099]
Hit in a CI job in CoreClr. Do'nt have repro steps but I see it's CLI code.
https://github.com/dotnet/coreclr/pull/10323#issuecomment-288142586

```
14:52:47 Installing dotnet cli...
14:53:10 Restoring BuildTools version 1.0.27-prerelease-01413-01...
14:53:10
14:53:10 Unhandled Exception: System.ArgumentNullException: Value cannot be null.
14:53:10 Parameter name: path1
14:53:10 at System.IO.Path.Combine(String path1, String path2, String path3)
14:53:10 at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider.ResolvePackagesPath(String rootDirectory, GlobalSettings settings)
14:53:10 at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
14:53:10 at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
14:53:10 at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.ShouldPrimeNugetCache()
14:53:10 at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
14:53:10 at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
14:53:10 at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
14:53:10 at Microsoft.DotNet.Cli.Program.Main(String[] args)
14:53:10 /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/tests/../init-tools.sh: line 164: 1325 Abort trap: 6 $__DOTNET_CMD restore "$__PROJECT_JSON_FILE" --no-cache --packages $__PACKAGES_DIR --source $__BUILDTOOLS_SOURCE >> $__init_tools_log
14:53:10
ERROR: Could not restore build tools correctly. See '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/init-tools.log' for more details.1
14:53:10 Initializing BuildTools...
```

**Comment by livarcocc** [comment]
This happens when $HOME is not set in the box.

This is a requirement by NuGet and this is simply the first time we try to find the cache. Even if you had not hit this, when doing restore you would hit something similar. Can you try setting $HOME in your script and seeing if that goes away?

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4871
