### ISSUE TITLE
BadImageFormatException when using Moq and System.Memory's Span type

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#6129]
We were trying to convert https://github.com/aspnet/kestrelhttpserver to run the tests on netcoreapp2.0 and ran into couple of exceptions:
```
Microsoft.AspNetCore.Server.KestrelTests.HttpParserTests.ParseHeadersConsumesBytesCorrectlyAtEnd [FAIL]
[xUnit.net 00:00:26.3407669]       System.InvalidProgramException : Common Language Runtime detected an invalid program.
[xUnit.net 00:00:26.3407816]       Stack Trace:
[xUnit.net 00:00:26.3407998]            at Castle.Proxies.ObjectProxy_4.OnHeader(Span`1 name, Span`1 value)
[xUnit.net 00:00:26.3408224]         C:\github\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Http\KestrelHttpParser.cs(394,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.KestrelHttpParser.TakeSingleHeader[T](Byte* headerLine, Int32 length, T handler)
[xUnit.net 00:00:26.3408523]         C:\github\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Http\KestrelHttpParser.cs(266,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.KestrelHttpParser.ParseHeaders[T](T handler, ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined, Int32& consumedBytes)
[xUnit.net 00:00:26.3408834]         C:\github\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\HttpParserTests.cs(311,0): at Microsoft.AspNetCore.Server.KestrelTests.HttpParserTests.ParseHeadersConsumesBytesCorrectlyAtEnd()

-------------------------------

[xUnit.net 00:00:26.2287480]     Microsoft.AspNetCore.Server.KestrelTests.HttpParserTests.ParseHeadersCanParseEmptyHeaderValues(rawHeaders: "Connection: close\r\nCookie: \r\n\r\n", expectedHeaderName1: "Connection", expectedHeaderValue1: "close", expectedHeaderName2: "Cookie", expectedHeaderValue2: "") [FAIL]
[xUnit.net 00:00:26.2287946]       System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
[xUnit.net 00:00:26.2288509]       Stack Trace:
[xUnit.net 00:00:26.2288867]            at Microsoft.AspNetCore.Server.KestrelTests.HttpParserTests.VerifyRawHeaders(String rawHeaders, IEnumerable`1 expectedHeaderNames, IEnumerable`1 expectedHeaderValues)
[xUnit.net 00:00:26.2289665]         C:\github\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\HttpParserTests.cs(256,0): at Microsoft.AspNetCore.Server.KestrelTests.HttpParserTests.ParseHeadersCanParseEmptyHeaderValues(String rawHeaders, String expectedHeaderName1, String expectedHeaderValue1, String expectedHeaderName2, String expectedHeaderValue2)
```

## Steps to reproduce
- Clone the repo https://github.com/kichalla/BadImageFormatExceptionRepro
- dotnet restore
- dotnet run
- Press any key to cause the JIT compilation to be invoked for the Test() method.
- You should see the BadImageFormatException

## Expected  behavior
No exception

## Actual behavior
BadImageFormatException

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005418)

Product Information:
 Version:            2.0.0-preview1-005418
 Commit SHA-1 hash:  82c928e1ec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005418\
```

cc @pranavkm @davidfowl @Eilon @gkhanna79

**Comment by gkhanna79** [comment]
@kouvel Can you please take an initial stab at this?

**Comment by livarcocc** [comment]
Maybe we should move the issue to core-setup or corefx?

**Comment by gkhanna79** [comment]
This could be a CoreCLR or CoreFX issue, not Core-Setup. That said, I would like to hear findings from @kouvel to get it to the right place once and for all.

**Comment by davidfowl** [comment]
This isn't a bug, it's by design.

**Comment by Eilon** [comment]
@davidfowl details?

**Comment by Eilon** [comment]
@davidfowl ping?

**Comment by davidfowl** [comment]
It's already fixed, has nothing to do with Moq, was just improper Span usage. Span can't be placed in generic arguments, that's why it was blowing up. Fixed here https://github.com/aspnet/KestrelHttpServer/commit/0f28c49c5ec7d52ff1439bff3665814b8183eada

**Comment by Eilon** [comment]
Ok so not by design really, but rather by unfortunate consequences 😄 Thanks!
