### ISSUE TITLE
installation fails on debian stretch

### ISSUE THREAD

**Issue by harindu95** [dotnet/cli#6153]
## Steps to reproduce
I tried the following method from official site.
    
     sudo apt-get install curl libunwind8 gettext
     curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=843453
     sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
     sudo ln -s /opt/dotnet/dotnet /usr/local/bin
     dotnet new console -o hwapp   

## Expected  behavior
    Creating a new project

## Actual behavior

Crashed with the following error

     Error reading JObject from JsonReader. Path '', line 0, position 0.
     at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
     at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
     at Newtonsoft.Json.Linq.JObject.Parse(String json)
     at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureLoaded()
     at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.GetTemplates(HashSet`1 templates)
     at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.List(Boolean exactMatchesOnly, Func`3[] filters)
     at Microsoft.TemplateEngine.Cli.New3Command.PerformCoreTemplateQueryAsync()
     at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__65.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
     at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext(\'

## Environment data
dotnet --info output:

    .NET Command Line Tools (1.0.1)

    Product Information:
    Version:            1.0.1
    Commit SHA-1 hash:  005db40cd1

    Runtime Environment:
    OS Name:     debian
    OS Version:  9
    OS Platform: Linux
    RID:         debian.8-x64
    Base Path:   /opt/dotnet/sdk/1.0.1

find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'

  	liblldb-3.6.so => not found
	liblldb-3.6.so => not found

**Comment by ofmendez** [comment]
Same here, exact result :(

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#589
