### ISSUE TITLE
Latest CLI throws exception - System.DllNotFoundException : Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#6248]
## Steps to reproduce
- Clone the repo http://github.com/aspnet/kestrelhttpserver
- Set the environment variable `KOREBUILD_DOTNET_VERSION` to `2.0.0-preview1-005685` (this tells the build to use this CLI version)
- Run `build.cmd`

## Expected  behavior
Build runs successfully

## Actual behavior
Build fails with error:
```
System.AggregateException : One or more errors occurred.
---- System.DllNotFoundException : Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Testing.TestServer..ctor(RequestDelegate app, TestServiceContext context, ListenOptions listenOptions, IHttpContextFactory httpContextFactory) in C:\github\kestrelhttpserver\test\shared\TestServer.cs:line 58
   at Microsoft.AspNetCore.Testing.TestServer..ctor(RequestDelegate app, TestServiceContext context, ListenOptions listenOptions) in C:\github\kestrelhttpserver\test\shared\TestServer.cs:line 38
   at Microsoft.AspNetCore.Server.KestrelTests.EngineTests.<ThrowingInOnStartingResultsInFailedWritesAnd500Response>d__24.MoveNext() in C:\github\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\EngineTests.cs:line 868
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.Init(LibuvFunctions uv)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAsync>d__20.MoveNext()
[xUnit.net 00:00:38.8783866]   Finished:    Microsoft.AspNetCore.Server.KestrelTests
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005685)

Product Information:
 Version:            2.0.0-preview1-005685
 Commit SHA-1 hash:  1f8b86d268

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005685\
```

@davidfowl

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#1961
