### ISSUE TITLE
dotnet <external cmd> stack dumps if run in a dir with multiple csproj files

### ISSUE THREAD

**Issue by seancpeters** [dotnet/cli#6267]
## Steps to reproduce
In a console session, go to a directory containing multiple .csproj files.
Run 'dotnet foo' (foo can be replaced by any command name not built in to dotnet)

## Expected  behavior
The program should fail gracefully, emitting a proper error message.

## Actual behavior
This stack dump is sent to the console:
```
Unhandled Exception: System.InvalidOperationException: Specify which project file to use because this 'c:\temp\Creation\scratch\TestAddRef\MyApp' contains more than one project file.
   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProjPath(String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProj(String projectDirectory, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004842)

Product Information:
 Version:            1.0.0-rc4-004842
 Commit SHA-1 hash:  7238b3efa2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004842

**Comment by anjdreas** [comment]
Can I specify the project in order to have multiple projects in the same dir?
I have a dir with two test projects (to test same source with two different conditional compilation symbols).

Something like this:
`dotnet xunit TestProject.NetCore.csproj`
`dotnet xunit TestProject.WindowRuntimeComponent.csproj`
