### ISSUE TITLE
libcoreclr shim out of date?

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#629]
```
Davids-MacBook-Pro:HelloMvc dfowler$ dotnet run
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'SetConsoleCtrlHandler' in DLL 'libcoreclr'.
   at Interop.libcoreclr.SetConsoleCtrlHandler(ConsoleCtrlHandlerRoutine handler, Boolean addOrRemove)
   at System.ConsolePal.ControlCHandlerRegistrar.RegisterOrUnregister(Boolean register)
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.AspNet.Hosting.WebApplicationExtensions.Run(IWebApplication application)
   at HelloMvc.Program.Main(String[] args)
```

I know dependencies are wrong somewhere but I'm not sure where. So here are a few questions:

- Should this still be in libcoreclr? I thought the only thing left was semaphores... (Didn't this move to **System.Native**)?
- If it did move, why would it still be loading? Is it my version of System.Console? I'm using **System.Console 4.0.0-rc2-23616**

/cc @anurse @stephentoub @ericstj

**Comment by davidfowl** [comment]
Adding `"NETStandard.Library": "1.0.0-rc2-23616"` worked...
