### ISSUE TITLE
dotnet migrate fails with ArgumentException

### ISSUE THREAD

**Issue by DannyvanderKraan** [dotnet/cli#6299]
## Steps to reproduce
- On the command prompt type "dotnet migrate" in the directory containing the project.json and xproj file of the 'old' ASP.NET Core project

## Expected  behavior
A migrated project to the new csproj file and no project.json, so I can use it in Visual Studio 2017.

## Actual behavior
It fails with:

"Migration failed.

Unhandled Exception: System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.DotNet.Internal.ProjectModel.Files.IncludeFilesResolver.<>c__DisplayClass1_0.<GetIncludeFiles>b__1(String file)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Internal.ProjectModel.Files.IncludeFilesResolver.GetIncludeFiles(IncludeContext context, String targetBasePath, IList`1 diagnostics, Boolean flatten)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateAssemblyInfoRule.GetCompilationSources(ProjectContext project, CommonCompilerOptions compilerOptions)
   at Microsoft.DotNet.ProjectJsonMigration.Rules.MigrateAssemblyInfoRule.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs)
   at Microsoft.DotNet.ProjectJsonMigration.DefaultMigrationRuleSet.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.MigrateProject(MigrationSettings migrationSettings)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass35_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)"

## Environment data
**`dotnet --info` output:**

.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**project.json:**

```
{
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": true
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
  "dependencies": {
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc1-177",
    "Microsoft.AspNetCore.Authentication": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Http.Extensions": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.WindowsAzure.ConfigurationManager": "2.0.3",
    "NServiceBus": "5.2.14",
    "NServiceBus.Autofac": "5.0.0",
    "NServiceBus.Azure": "6.2.3",
    "NServiceBus.Azure.Transports.WindowsAzureServiceBus": "6.4.0",
    "Sod.Gearbox.MessageInventory.InternalMessages": "1.0.2",
    "WindowsAzure.ServiceBus": "2.7.6",
    "WindowsAzure.Storage": "4.3.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "IdentityServer3.AccessTokenValidation.Integration.AspNetCore": "1.0.0",
    "Sod.Gearbox.MessageInventory.ServiceHub": "1.0.4-alpha005",
    "Sod.IdentityServer.Claims": "1.0.0-alpha2",
    "Swashbuckle": "6.0.0-beta902"
  },
  "compileExclude": [
    "wwwroot",
    "node_modules"
  ],
  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Configuration": "4.0.0.0"
      }
    }
  },
  "publishOptions": {
    "exclude": [
      "**.user",
      "**.vspscc"
    ]
  },
  "version": "1.0.0-*"
}
```

**xproj:**

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" Condition="'$(VSToolsPath)' != ''" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>72efad51-fd5e-4418-b510-2f804a5ef2da</ProjectGuid>
    <RootNamespace>Sod.Gearbox.Api</RootNamespace>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">.\bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
    <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.targets" Condition="'$(VSToolsPath)' != ''" />
</Project>
```

**Comment by we4sz** [comment]
Get the same with:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.targets" Condition="'$(VSToolsPath)' != ''" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>8b19fa3d-0624-485f-9078-bf8ef192ab9b</ProjectGuid>
    <RootNamespace>Test.Application</RootNamespace>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">.\bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
  </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DotNet.Web\Microsoft.DotNet.Web.targets" Condition="'$(VSToolsPath)' != ''" />
</Project>
```


```
{
  "userSecretsId": "AspNetCore5-Application-dea8cf95-82e7-464b-9176-c96b643494d1",
  "version": "1.0.2-*",


  "buildOptions": {
    "warningsAsErrors": false,
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "compile": {
      "exclude": [ "wwwroot", "node_modules" ] // Now here, instead of ".:exclude"
    },
    "embed": "\"Views",
    "nowarn": [ "CS1998", "CS4014", "CS0169" ]
  },
  "runtimeOptions": {
    "gcServer": true,
    "gcConcurrent": true 
  },
  
  "dependencies": {
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "IdentityModel": "2.0.0-beta3",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Session": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview2-final",
    "System.IdentityModel.Tokens.Jwt": "5.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.AspNetCore.ResponseCompression": "1.0.0",
    "Microsoft.Extensions.DependencyInjection": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  },

  "frameworks": {
    "net451": {
    }
  },
  "publishOptions": {
    "exclude": [
      "wwwroot/app",
      "wwwroot/jspm_packages/npm/*@*/*",
      "wwwroot/jspm_packages/github/*@*/*",
      "wwwroot/test",
      "wwwroot/lib"
    ],
    "include": [
      "wwwroot",
      "wwwroot/jspm_packages/npm/*.json",
      "wwwroot/jspm_packages/github/*.json",
      "Views",
      "appsettings.json",
      "appsettings.*.json",
      "web.config"
    ]
  }
}
```

**Comment by livarcocc** [comment]
Do these projects work in preview2 CLI?

**Comment by we4sz** [comment]
@livarcocc 
Yeah i run it everyday on 1.0.0-preview2-003133

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#14
