### ISSUE TITLE
Setup .NET Core 1.1 failed on CentOS 7 follow official instruction

### ISSUE THREAD

**Issue by hchungi** [dotnet/cli#6307]
## Steps to reproduce
1. Follow the official instruction to setup dotnet core on new CentOS 7 machine
[https://www.microsoft.com/net/core#linuxcentos](https://www.microsoft.com/net/core#linuxcentos)

2. run **dotnet new console -o hwapp**

An exception occurred.

## Expected  behavior
Initialize a sample Hello World application successfully.

## Actual behavior

A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 6077 ms
Expanding 0%
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Structure needs cleaning)) (Structure needs cleaning) ---> System.IO.IOException: Structure needs cleaning
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
   at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
   at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /opt/dotnet/sdk/1.0.1

`df` output:
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda1      15716368 2803272  12913096  18% /
devtmpfs          489152       0    489152   0% /dev
tmpfs             507736       0    507736   0% /dev/shm
tmpfs             507736   12988    494748   3% /run
tmpfs             507736       0    507736   0% /sys/fs/cgroup
tmpfs             101548       0    101548   0% /run/user/1000
tmpfs             101548       0    101548   0% /run/user/0

**Comment by livarcocc** [comment]
I am not sure, because this isn't something that I know a lot about, but I believe this error usually indicated a corruption in the file system. Do you have another box available where you can try this?

@stephentoub Have you seen this error before? Can you help us understand why it happens and how to get around it? Is there something that we should be doing int he CLI to get around it?

**Comment by stephentoub** [comment]
That "Structure needs cleaning" error is coming from the OS and has little to do with dotnet.  I've never hit it myself, but searches suggest that folks hit it when they've somehow got a corrupted file system, as @livarcocc says.  The same searches also highlight potential workarounds / fixes:
https://www.bing.com/search?q=centos+7+structure+needs+cleaning

**Comment by hchungi** [comment]
I would like to say thanks at first.
After I check again and again, this is my OS image issue.
Thanks for help, anyway!
