### ISSUE TITLE
dotnet run doesn't print stacktrace on app crash (netcoreapp2.0)

### ISSUE THREAD

**Issue by codito** [dotnet/cli#6535]
## Steps to reproduce
1. Create a new console app with following csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;netcoreapp1.1;netcoreapp2.0</TargetFrameworks>
  </PropertyGroup>

</Project>
```

2. Add following code to Program.cs
```
using System;

namespace trial
{
    class Program
    {
        static void Main(string[] args)
        {
            System.Diagnostics.Debug.Assert(false, "fail");
            Console.WriteLine("Hello World!");
        }
    }
}
```

3. Run these commands
```
> dotnet run --framework netcoreapp2.0
```

## Expected  behavior
Console output should be following:
```
fail

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at trial.Program.Main(String[] args) in /tmp/trial/Program.cs:line 9
Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: fail

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at trial.Program.Main(String[] args) in /tmp/trial/Program.cs:line 9
   at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at trial.Program.Main(String[] args) in /tmp/trial/Program.cs:line 9
```

`dotnet run --framework netcoreapp1.1` shows this output.

## Actual behavior
No output.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/armahapa/src/vstest/tools/dotnet/sdk/2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1

**Comment by nguerrera** [comment]
This was fixed in coreclr. The symptom occurs for runtime versions that have https://github.com/dotnet/coreclr/pull/10652, but not https://github.com/dotnet/coreclr/pull/11397

Verified fixed in
```
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /home/nicholg/qqq/sdk/2.0.0-preview2-006127/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d
```
