### ISSUE TITLE
Deepin15.2    dotnet restore failure

### ISSUE THREAD

**Issue by Hareis** [dotnet/cli#6564]
## Steps to reproduce
按照官方的教程安装的

## Environment data
`dotnet --info` output:

areis@hareis-pc:/media/hareis/娱乐/CSharpSolution/myBlog$ dotnet restore
段错误
hareis@hareis-pc:/media/hareis/娱乐/CSharpSolution/myBlog$   Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.common/myBlog.common.csproj...
  Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.dataAccess/myBlog.dataAccess.csproj...
  Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.model/myBlog.model.csproj...
  Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.service/myBlog.service.csproj...

hareis@hareis-pc:/media/hareis/娱乐/CSharpSolution/myBlog$

dotnet new console -o hwapp
Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureLoaded()
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.GetTemplates(HashSet`1 templates)
   at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.List(Boolean exactMatchesOnly, Func`3[] filters)
   at Microsoft.TemplateEngine.Cli.New3Command.PerformCoreTemplateQueryAsync()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#776
