### ISSUE TITLE
new web mvc project with v 2.0.0-preview1-final doesn't run (Invalid request line: '\x16\x03\x01\x00...)

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/cli#6608]
Hi, 
## Steps to reproduce
```
Open command shell
dotnet publish -c debug
bin\Debug\netcoreapp2.0\publish
dotnet xxx.dll

```
## Expected  behavior
Running and managing requests

## Actual behavior
```
Connection id "0HL4S9N91O8I3" bad request data: "Invalid request line: '\x16\x03\x01\x00\xAE\x01\x00\x00\xAA\x03\x03\x8C\xDB|\x0D9\x12p\xC0;BJ\x93\x8DQ\x81\xC3\x7F\x12g\xC20\xF0f\x0D\xEC\xF1\xE5P\x1E\x03\x88\xF6\x00\x00\x1C\x8A\x8A\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00\x0A'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: '\x16\x03\x01\x00\xAE\x01\x00\x00\xAA\x03\x03\x8C\xDB|\x0D9\x12p\xC0;BJ\x93\x8DQ\x81\xC3\x7F\x12g\xC20\xF0f\x0D\xEC\xF1\xE5P\x1E\x03\x88\xF6\x00\x00\x1C\x8A\x8A\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00\x0A'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethod(Byte* data, Int32 length, Int32& methodLength)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ParseRequest(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
Application is shutting down...
```

## Environment data
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

txs
-Vince

**Comment by livarcocc** [comment]
@Eilon @muratg is this something that you guys have seen before?

**Comment by muratg** [comment]
@halter73 could you attempt a repro?

**Comment by halter73** [comment]
This error is caused by a client trying to establish an HTTPS connection to an HTTP endpoint.

We had [considered](https://github.com/aspnet/KestrelHttpServer/issues/1116) logging this more clearly with a message like "An invalid SSL/TLS handshake was attempted on an HTTP endpoint." based on whether the first byte was 0x16, but we decided to got with a more generic "Invalid request line: ..." message which is more [inline with other servers](https://www.google.com/search?q=Invalid+request+line%3A+%5Cx16%5Cx03%5Cx01).

**Comment by vRITHNER** [comment]
My bad, I uncheck the` "Enable SSL"` in project's settings ; I was trying to remove the https stuff..

Bye the way, I would love to know the way to do it ? Looks like some settings in a lot of places to make work but wo success for now...
txs
-v
