### ISSUE TITLE
Cannot execute the dotnet core library/app using dotnet command

### ISSUE THREAD

**Issue by huanwu** [dotnet/cli#6612]
Need a way to run following tool app using CLI
https://github.com/dotnet/corefx/blob/master/src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj

Tried the following two ways but all fail.
Compile this project to dll
When run dotnet Microsoft.XmlSerializer.Generator.dll, it will gives the following error.
_A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\dd\corefx\bin\AnyOS.AnyCPU.Debug\Microsoft.XmlSerializer.Generator\netstandard\'._

If compile it to exe by adding the following to the project
`<OutputType>Exe</OutputType>`

When run Microsoft.XmlSerializer.Generator.exe, it will throw the following error.
_Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()_

**Comment by ellismg** [comment]
/cc @weshaggard @mellinoe 

CoreFX has a great deal of customization around how the build projects.  I don't believe they use the SDK tooling directly, so it's possible the application is not produced in a form the CLI understands.  Wes or Eric might have a better understanding of how to do what you want.

**Comment by livarcocc** [comment]
I can't access the link above, so I can't really confirm what you are doing.

But, if you want produce a runnable app using the SDK, you should target netcoreappX.X as your TFM and you should have OutputType as Exe for it to work.

**Comment by huanwu** [comment]
@livarcocc Here is the link. Could you help take a look? I cannot make it work now. It will be great if you can help. https://github.com/dotnet/corefx/blob/master/src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj

**Comment by livarcocc** [comment]
This is not a SDK based project and therefore it is not something that the CLI handles today. The CLI only works with new style csproj. If you want to build that project, you need to use msbuild.

**Comment by mellinoe** [comment]
@huanwu Please file an issue for us in corefx. We should be able to figure out how to configure the project correctly over there. Like @ellismg said, we do a lot of build customization which is different from regular SDK projects.

**Comment by huanwu** [comment]
@mellinoe Filed an issue https://github.com/dotnet/corefx/issues/19930. Thanks
