### ISSUE TITLE
Invalid command options cause dotnet to crash

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#693]
For example, `dotnet /?` throws 
```
Unhandled Exception: System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.DotNet.Cli.Utils.Command.ResolveExecutableFromPath(String executable, String& args, CommandResolutionStrategy& resolutionStrategy)
   at Microsoft.DotNet.Cli.Utils.Command.ResolveExecutablePath(String& executable, String& args, CommandResolutionStrategy& resolutionStrategy, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

It would be better to handle invalid options, and print help message.

**Comment by blackdwarf** [comment]
This was fixed in #697.
