### ISSUE TITLE
`dotnet new console` and `dotnet restore` throw `System.IO.DirectoryNotFoundException`

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/cli#6998]
Summary
----------
This happens to the latest 2.0.0-preview3 dotnet CLI `2.0.0-preview3-006546` and `2.0.0-preview3-006540`

## Steps to reproduce
```
dotnet new console
```
or
```
dotnet restore
```

## Expected  behavior
They should work without error

## Actual behavior
```
PS:13> C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\dotnet.exe new console

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\usr\.dotnet\2.0.0-preview3-006546.dotnetFirstUseSentinel'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.PrintFirstTimeUseNotice()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
```
PS:14> C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\dotnet.exe --info
.NET Command Line Tools (2.0.0-preview3-006546)

Product Information:
 Version:            2.0.0-preview3-006546
 Commit SHA-1 hash:  f4d884a03d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\usr\Downloads\dotnet-sdk-latest-win-x64\sdk\2.0.0-preview3-006546\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25419-01
  Build    : 2fab74ca0ab629adfe1291e3f1b5eeae2a57c156
```

**Comment by livarcocc** [comment]
Thanks for the bug report. This is a dup of https://github.com/dotnet/cli/issues/6989.
