### ISSUE TITLE
Unhandled Exception: System.IO.IOException: No space left on device

### ISSUE THREAD

**Issue by Leathal1** [dotnet/cli#7141]
## Steps to reproduce
I installed the .netcore on debian 8 distro.  Install looked like it went fine no errors.  However when I went to run the first run sample I'm getting the below error.  I was looking to see if there were any requirements for running this?  Currently I'm running in a VM.   

## Expected  behavior
This works as in windows 

## Actual behavior
No space left on device error

## Environment data
`dotnet --info` output:

Unhandled Exception: System.IO.IOException: No space left on device
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted

**Comment by livarcocc** [comment]
The CLI carries with it an archive of all the nuget packages you need in order to restore the asp.net mvc templates that ship with it. When the CLI gets invoked for the first time, we expand such archive. The error that you are hitting above is that your VM does not have enough disk space to fit the archive.

If you are confident that you are not going to need all these packages, you can turn off this first run experience by setting the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to true.

But keep in mind, that you may end up running out of space anyways (because of other packages that you are downloading), in which case restore will fail.

I am closing the issue because I can't think of anything else that we can do in this case. But, feel free to re-activate it if anything comes up.

**Comment by Leathal1** [comment]
Could you let me know the size of the archive to restore the asp.net mvc templates that ship with it?  It's a VM I don't mind expanding.

**Comment by Leathal1** [comment]
Thanks I did get this up and running.
