### ISSUE TITLE
Failure in telemetry during CI

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#7194]
Debug.Fail("Exception during X") without exception details. 😡 

https://ci.dot.net/job/dotnet_cli/job/release_2.0.0/job/debug_ubuntu16.04_x64_prtest/609/testReport/junit/(root)/(empty)/Microsoft_DotNet_Tests_GivenThatTheUserIsRunningDotNetForTheFirstTime_UsingDotnetForTheFirstTimeSucceeds/

https://github.com/dotnet/cli/blob/5a37290f24aba5d35f3f958300aa20329e5ccaa7/src/dotnet/Telemetry.cs#L131

```
FailFast: Exception during TrackEventTask

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at Microsoft.DotNet.Cli.Telemetry.TrackEventTask(String eventName, IDictionary`2 properties, IDictionary`2 measurements)
   at Microsoft.DotNet.Cli.Telemetry.<>c__DisplayClass20_0.<TrackEvent>b__0(Task x)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.DotNet.Cli.Telemetry.TrackEventTask(System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Double>)
   at Microsoft.DotNet.Cli.Telemetry+<>c__DisplayClass20_0.<TrackEvent>b__0(System.Threading.Tasks.Task)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

                                        +++++++++++++++++++
                                        STACK TRACE:
                                           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() in /mnt/j/workspace/dotnet_cli/release_2.0.0/debug_ubuntu16.04_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/CommandResultAssertions.cs:line 30
   at Microsoft.DotNet.Tests.GivenThatTheUserIsRunningDotNetForTheFirstTime.UsingDotnetForTheFirstTimeSucceeds() in /mnt/j/workspace/dotnet_cli/release_2.0.0/debug_ubuntu16.04_x64_prtest/test/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs:line 48
```

**Comment by wli3** [comment]
Agree, this is annoying. It should be something about this multi thread business.

``` C#
            _trackEventTask = _trackEventTask.ContinueWith(
                x => TrackEventTask(eventName, properties, measurements)
            );

```

**Comment by livarcocc** [comment]
I haven't noticed this in a long time. Has anyone noticed this? If not, I am leaning towards closing this issue.

cc @dotnet/dotnet-cli

**Comment by nguerrera** [comment]
We should at least make sure the Exception.ToString() details are part of the Debug.Fail.

**Comment by livarcocc** [comment]
@wli3 can you add that?

**Comment by wli3** [comment]
If the action item is Debug.Fail(ex.ToString()); it has been done already

https://github.com/dotnet/cli/blob/master/src/dotnet/Telemetry/Telemetry.cs#L104

please reopen if you think there is more action item @livarcocc @nguerrera
