### ISSUE TITLE
`git clean -xdf && build.cmd && build.cmd` fails to build the second time

### ISSUE THREAD

**Issue by khyperia** [dotnet/cli#7364]
From a completely clean state, building, and then rebuilding, fails to build the second time.

Is this expected behavior? It makes development on the CLI very difficult/slow.

The error is in target `RunResolvePackageDependencies` in `dotnet.csproj` (followed by many `"predefined type 'x' is not defined or imported"`):

```
C:\c\cli\.dotnet_stage0\x64\sdk\2.1.0-preview1-007002\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(170,5): error MSB4018: The "ResolvePackageDependencies" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\c\cli\artifacts\win10-x64\stage2\sdk\NuGetFallbackFolder'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(LockFile lockFile, String projectPath)
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.get_PackageResolver()
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ResolvePackagePath(LockFileLibrary package)
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.GetPackageAndFileDefinitions()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [C:\c\cli\src\dotnet\dotnet.csproj]
```

A wild guess why is that Target `CompileCLI` in `build.proj` deletes `stage2` *after* the restore, so there's broken paths pointing into `stage2`.

(Any other tips to speed development would be appreciated)

**Comment by wli3** [comment]
Hi @khyperia 
Thank you for your issue. We actually just talked about this yesterday. I feel the pain as well. And we plan to address it after the major release.

You can skip the test by using
./build.cmd /p:CLIBUILD_SKIP_TESTS=true

and run test individually like (dotnet0 is a path point to cli\.dotnet_stage0\)

dotnet0 test --filter "FullyQualifiedName=Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesApps"

**Comment by uframer** [comment]
I don't whether the same issue but I got similar output for a second time build on macOS:
```
     3>/Users/jiaoye/GitHub/uframer-dotnet-suite/uframer-dotnet-cli/.dotnet_stage0/x64/sdk/2.0.1-servicing-006933/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(170,5): error MSB4018: The "ResolvePackageDependencies" task failed unexpectedly. [/Users/jiaoye/GitHub/uframer-dotnet-suite/uframer-dotnet-cli/src/dotnet/dotnet.csproj]
/Users/jiaoye/GitHub/uframer-dotnet-suite/uframer-dotnet-cli/.dotnet_stage0/x64/sdk/2.0.1-servicing-006933/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(170,5): error MSB4018: NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder '/Users/jiaoye/GitHub/uframer-dotnet-suite/uframer-dotnet-cli/artifacts/osx.10.12-x64/stage2/sdk/NuGetFallbackFolder'. [/Users/jiaoye/GitHub/uframer-dotnet-suite/uframer-dotnet-cli/src/dotnet/dotnet.csproj]
```

**Comment by livarcocc** [comment]
Incremental builds have been fixed in master.
