### ISSUE TITLE
Cannot run build.cmd on windows

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#7402]
Repo steps:

- Clone dotnet/cli
- Run build.cmd 

The expected results are that everything succeeds. Instead I end up with the following errors:

```
    15>DOTNETTEST : error Message:  [E:\code\cli\build\test\RunTest.proj]
          System.IO.DirectoryNotFoundException : Could not find a part of the path 'E:\code\cli\.nuget\packages\.tools\dotnet-portable\1.0.0\netcoreapp2.0\project.assets.json'.
         Stack Trace:
            at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at NuGet.ProjectModel.LockFileFormat.Read(String filePath, ILogger log)
            at Microsoft.DotNet.Tests.GivenAProjectToolsCommandResolver.GenerateDepsJsonMethodDoesntOverwriteWhenDepsFileAlreadyExists() in E:\code\cli\test\Microsoft.DotNet.Cli.Utils.Tests\GivenAProjectToolsCommandResolver.cs:line 267
         Executing - E:\code\cli\artifacts\win10-x64\stage2\dotnet.exe restore   --disable-parallel -  in pwd E:\code\cli\test\Microsoft.DotNet.Cli.Utils.Tests\bin\Debug\netcoreapp2.0\ItShowsStackTraceWhenRunAsTool\AppThrowingException\AppDependingOnOtherAsTool
```

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by jaredpar** [comment]
Any updates on this?

**Comment by livarcocc** [comment]
Hey @jaredpar, is this still happening to you?

**Comment by jaredpar** [comment]
Haven't tried in a while. Think we can just close this. If it happens again I can re-open.
