### ISSUE TITLE
Unable to start Kestrel. System.IO.IOException: Failed to bind to address http://localhost:5000 on the IPv4 loopback interface: port already in use.

### ISSUE THREAD

**Issue by djamajo** [dotnet/cli#7422]
## Steps to reproduce

1 - open VSCode
2 - Load the project with `Code .`
2 - run the project using `Dotnet watch run`

## Expected  behavior
to make the app available  http://localhost:5000 

## Actual behavior

Unable to start Kestrel. System.IO.IOException: Failed to bind to address http://localhost:5000 on the IPv4 loopback interface: port already in use.

## Environment data
`dotnet --info` output:

```
Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://localhost:5000 on the IPv4 loopback interface: port already in use. ---> System.AggregateException: One or more errors occurred. (Error -48 EADDRINUSE address already in use) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -48 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_getsockname(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)

Unhandled Exception: System.IO.IOException: Failed to bind to address http://localhost:5000 on the IPv4 loopback interface: port already in use. ---> System.AggregateException: One or more errors occurred. (Error -48 EADDRINUSEaddress already in use) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -48 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_getsockname(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Welocate.Program.Main(String[] args) in /Users/admin/welocate/Program.cs:line 20
watch : Exited with error code 134
watch : Waiting for a file to change before restarting dotnet...

```

**Comment by davidfowl** [comment]
The port is in use... You should be able to use `netstat -a` to see that.

**Comment by djamajo** [comment]
ok, thanks.

For others having the same issue, here is the steps:

on terminal on MAC:

```
1 - soft -t -I :portNumber
process ID will be display (in case the port is in use ) ex: 10872
2 - kill -9 10872 (to kill the process)

```

**Comment by MysteriousBox** [comment]
> The port is in use... You should be able to use `netstat -a` to see that.

How to modify it?

**Comment by MysteriousBox** [comment]
> ok, thanks.
> 
> For others having the same issue, here is the steps:
> 
> on terminal on MAC:
> 
> ```
> 1 - soft -t -I :portNumber
> process ID will be display (in case the port is in use ) ex: 10872
> 2 - kill -9 10872 (to kill the process)
> ```
How do I do this on window?

**Comment by asmaa3107** [comment]
> ok, thanks.
> 
> For others having the same issue, here is the steps:
> 
> on terminal on MAC:
> 
> ```
> 1 - soft -t -I :portNumber
> process ID will be display (in case the port is in use ) ex: 10872
> 2 - kill -9 10872 (to kill the process)
> ```

I still have the same issue Win 10??

**Comment by priyagavs** [comment]
Having issue still while runing win 10 vs2017
 Failed to bind to http://[::]:80 (IPv6Any). Attempting to bind to http://0.0.0.0:80 instead.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4092 EACCES permission denied
