### ISSUE TITLE
Switching between SDK - dotnet new

### ISSUE THREAD

**Issue by sylvaincaillot** [dotnet/cli#7519]
## Steps to reproduce
I have several SDK installed (1.0.4, 1.1.0, 2.0.0).
I am trying to use the SPATemplate by doing `dotnet new`.
Some templates works with 1.1 version, others require 2.0 version

## Expected  behavior
Being able to swith easily between SDK from the command line

## Actual behavior
With SDk 1.0.4 with `dotnet new vue` for example, I obtained:
```
Option variant - for canonical TargetFrameworkOverride was already defined for canonical skipRestore
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.MapTemplateParamToCanon
ical(String variant, String canonical)
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.SetupTemplateParameters
(IParameterSet allParams, IReadOnlyDictionary`2 longNameOverrides, IReadOnlyDict
ionary`2 shortNameOverrides)
   at Microsoft.TemplateEngine.Cli.New3Command.ParseTemplateArgs(ITemplateInfo t
emplateInfo)
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterSingularTemplateManipulatio
nFlowAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsy
nc>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\1.0.4

**Comment by wli3** [comment]
Relate issue https://github.com/dotnet/cli/issues/6051
