### ISSUE TITLE
Specifying both 'TargetFrameworks'  and 'TargetFramework' causes dotnet run to fail badly.  

### ISSUE THREAD

**Issue by fearthecowboy** [dotnet/cli#7563]
I found this bug with a far more complicated example, but distilled it down to the minimum possible repro. 

## Steps to reproduce
``` powershell
# PowerShell Script
mkdir bug
cd bug
dotnet new console
dotnet add package newtonsoft.json 

# Add a "TargetFrameworks" element
(Get-Content .\bug.csproj).replace('<TargetFramework>', "<TargetFrameworks>netcoreapp2.0</Target
Frameworks>`n    <TargetFramework>") | Set-Content bug.csproj

# wipe clean
rmdir -r -force obj ; rmdir -r -force bin ; 

# restore and run project
dotnet restore ; dotnet run

# OUTPUT:
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 606.02 ms for C:\tmp\bug\bug.csproj.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version
=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does
 not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at bug.Program.Main(String[] args)
```

## Expected  behavior

Ideally, having `<TargetFramework>...` specified in the `csproj` file  should negate the necessity of having to use `--framework` on the command line. 

Second, even if that's not the 'expectation' -- it certainly should yell, like it would if you don't have `<TargetFramework>...` in the csproj:

``` powershell
# remove the TargetFramework element
(Get-Content .\bug.csproj).replace('TargetFramework>', "TargetFramework_>") | Set-Content bug.cs
proj

# clean, restore and run again
 rmdir -r -force obj ; rmdir -r -force bin ; dotnet restore ; dotnet run
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 629.54 ms for C:\tmp\bug\bug.csproj.
Unable to run your project
Your project targets multiple frameworks. Please specify which framework to run using '--framework'.
```

But, the real irritant is that it's pulling in the completely weird/wrong dependencies, and dying in a blaze of pain:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version
=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does
```

## Actual behavior
Running the program will throw an exception because it's somehow picked up the wrong assemblies.
``` text
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 606.02 ms for C:\tmp\bug\bug.csproj.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version
=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does
 not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at bug.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16278
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

## Final Thoughts
Why doesn't having a single value in `<TargetFrameworks>...` not behave  exactly the same as just having a `<TargetFramework>...` specified.

**Comment by livarcocc** [comment]
Can you share your csproj with us? I am confused if you have a TargetFrameworks property specifying a single TFM in it or if you have both TargetFrameworks and TargetFramework.

Unfortunately, it was not possible for us to process the TargetFrameworks property and realize it has only one and continue in the single TFM case, just the fact that we were evaluating TargetFrameworks was already what we call the outer-loop.

**Comment by fearthecowboy** [comment]
> Can you share your csproj with us?

The repro steps at the top of this thread produces the following project:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0</TargetFrameworks>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="newtonsoft.json" Version="10.0.3" />
  </ItemGroup>
</Project>
```

> I am confused if you have a TargetFrameworks property specifying a single TFM in it or if you have both TargetFrameworks and TargetFramework.

## Specifying both `TargetFrameworks` and `TargetFramework` causes dotnet run to fail badly.

> Unfortunately, it was not possible for us to process the TargetFrameworks property and realize it has only one and continue in the single TFM case, just the fact that we were evaluating TargetFrameworks was already what we call the outer-loop.

Yeah, I imagined that. Which is why I said:
>> Second, even if that's not the 'expectation' -- it certainly should yell, like it would if you don't have <TargetFramework>... in the csproj:

Even if you can't make single-value of `TargetFrameworks` work like a `TargetFramework` -- it should't die horribly with a unrelated, and useless message. It would be far better to die like it does if you don't have the `TargetFramework` in the file.

Very Bad Failing Example (having both `<TargetFrameworks>` and `<TargetFramework>` in the file):
![image](https://user-images.githubusercontent.com/133736/30330916-348cf3ee-978b-11e7-8bfc-e3aa6bd37b86.png)


Much Less Bad Example (removing just the `<TargetFramework>` from the `.csproj` :
![image](https://user-images.githubusercontent.com/133736/30330981-670b70e8-978b-11e7-93f4-af4f38263275.png)

**Comment by dasMulli** [comment]
The exception only happens when newtonsoft.json is added to the project. 

This may be a conflict resolution issue - the `project.assets.json` diffs only in 

```diff
--- project.assets.json 2017-09-12 16:46:11.248748400 +0200
+++ project.assets.json.bug     2017-09-12 16:48:18.160000000 +0200
@@ -3577,6 +3577,7 @@
       "packagesPath": "C:\\Users\\martin.ullrich\\.nuget\\packages\\",
       "outputPath": "C:\\Users\\martin.ullrich\\Documents\\repos\\testcons\\obj\\",
       "projectStyle": "PackageReference",
+      "crossTargeting": true,
       "fallbackFolders": [
         "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder"
       ],
```

But the generated deps son file has a lot of added runtime assets and the execution fails:

<details>
<summary>project.assets.json diff</summary>

```diff
--- project.assets.json 2017-09-12 16:46:11.248748400 +0200
+++ project.assets.json.bug     2017-09-12 16:48:18.160000000 +0200
@@ -3577,6 +3577,7 @@
       "packagesPath": "C:\\Users\\martin.ullrich\\.nuget\\packages\\",
       "outputPath": "C:\\Users\\martin.ullrich\\Documents\\repos\\testcons\\obj\\",
       "projectStyle": "PackageReference",
+      "crossTargeting": true,
       "fallbackFolders": [
         "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder"
       ],

martin.ullrich@DW10MARTIN-NG MINGW64 ~/Documents/repos
$ diff -u testcons.deps.json testcons.deps.json.bug
--- testcons.deps.json  2017-09-12 16:44:40.477635200 +0200
+++ testcons.deps.json.bug      2017-09-12 16:44:24.983000000 +0200
@@ -32,6 +32,9 @@
           "System.Runtime.Extensions": "4.3.0",
           "System.Runtime.InteropServices": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/Microsoft.CSharp.dll": {}
         }
       },
       "Microsoft.NETCore.Targets/1.1.0": {},
@@ -61,6 +64,9 @@
           "System.Runtime": "4.3.0",
           "System.Runtime.Extensions": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Collections.NonGeneric.dll": {}
         }
       },
       "System.Collections.Specialized/4.3.0": {
@@ -72,11 +78,17 @@
           "System.Runtime": "4.3.0",
           "System.Runtime.Extensions": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Collections.Specialized.dll": {}
         }
       },
       "System.ComponentModel/4.3.0": {
         "dependencies": {
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.ComponentModel.dll": {}
         }
       },
       "System.ComponentModel.Primitives/4.3.0": {
@@ -84,6 +96,9 @@
           "System.ComponentModel": "4.3.0",
           "System.Resources.ResourceManager": "4.3.0",
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.0/System.ComponentModel.Primitives.dll": {}
         }
       },
       "System.ComponentModel.TypeConverter/4.3.0": {
@@ -103,6 +118,9 @@
           "System.Runtime": "4.3.0",
           "System.Runtime.Extensions": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.5/System.ComponentModel.TypeConverter.dll": {}
         }
       },
       "System.Diagnostics.Debug/4.3.0": {
@@ -127,6 +145,9 @@
           "System.Runtime": "4.3.0",
           "System.Runtime.Extensions": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Dynamic.Runtime.dll": {}
         }
       },
       "System.Globalization/4.3.0": {
@@ -144,11 +165,11 @@
           "System.Runtime.InteropServices": "4.3.0"
         },
         "runtimeTargets": {
-          "runtime/unix/lib/_._": {
+          "runtimes/unix/lib/netstandard1.3/System.Globalization.Extensions.dll": {
             "rid": "unix",
             "assetType": "runtime"
           },
-          "runtime/win/lib/_._": {
+          "runtimes/win/lib/netstandard1.3/System.Globalization.Extensions.dll": {
             "rid": "win",
             "assetType": "runtime"
           }
@@ -176,6 +197,9 @@
       "System.IO.FileSystem.Primitives/4.3.0": {
         "dependencies": {
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.IO.FileSystem.Primitives.dll": {}
         }
       },
       "System.Linq/4.3.0": {
@@ -185,6 +209,9 @@
           "System.Resources.ResourceManager": "4.3.0",
           "System.Runtime": "4.3.0",
           "System.Runtime.Extensions": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.6/System.Linq.dll": {}
         }
       },
       "System.Linq.Expressions/4.3.0": {
@@ -206,6 +233,9 @@
           "System.Runtime": "4.3.0",
           "System.Runtime.Extensions": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.6/System.Linq.Expressions.dll": {}
         }
       },
       "System.ObjectModel/4.3.0": {
@@ -215,6 +245,9 @@
           "System.Resources.ResourceManager": "4.3.0",
           "System.Runtime": "4.3.0",
           "System.Threading": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.ObjectModel.dll": {}
         }
       },
       "System.Reflection/4.3.0": {
@@ -232,6 +265,9 @@
           "System.Reflection.Emit.ILGeneration": "4.3.0",
           "System.Reflection.Primitives": "4.3.0",
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Reflection.Emit.dll": {}
         }
       },
       "System.Reflection.Emit.ILGeneration/4.3.0": {
@@ -239,6 +275,9 @@
           "System.Reflection": "4.3.0",
           "System.Reflection.Primitives": "4.3.0",
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Reflection.Emit.ILGeneration.dll": {}
         }
       },
       "System.Reflection.Emit.Lightweight/4.3.0": {
@@ -247,6 +286,9 @@
           "System.Reflection.Emit.ILGeneration": "4.3.0",
           "System.Reflection.Primitives": "4.3.0",
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll": {}
         }
       },
       "System.Reflection.Extensions/4.3.0": {
@@ -266,6 +308,9 @@
         "dependencies": {
           "System.Reflection": "4.3.0",
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.5/System.Reflection.TypeExtensions.dll": {}
         }
       },
       "System.Resources.ResourceManager/4.3.0": {
@@ -309,12 +354,18 @@
           "System.Resources.ResourceManager": "4.3.0",
           "System.Runtime": "4.3.0",
           "System.Runtime.Serialization.Primitives": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.4/System.Runtime.Serialization.Formatters.dll": {}
         }
       },
       "System.Runtime.Serialization.Primitives/4.3.0": {
         "dependencies": {
           "System.Resources.ResourceManager": "4.3.0",
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll": {}
         }
       },
       "System.Text.Encoding/4.3.0": {
@@ -333,12 +384,18 @@
       "System.Text.RegularExpressions/4.3.0": {
         "dependencies": {
           "System.Runtime": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.6/System.Text.RegularExpressions.dll": {}
         }
       },
       "System.Threading/4.3.0": {
         "dependencies": {
           "System.Runtime": "4.3.0",
           "System.Threading.Tasks": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Threading.dll": {}
         }
       },
       "System.Threading.Tasks/4.3.0": {
@@ -352,6 +409,9 @@
           "System.Collections": "4.3.0",
           "System.Runtime": "4.3.0",
           "System.Threading.Tasks": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll": {}
         }
       },
       "System.Xml.ReaderWriter/4.3.0": {
@@ -371,6 +431,9 @@
           "System.Text.RegularExpressions": "4.3.0",
           "System.Threading.Tasks": "4.3.0",
           "System.Threading.Tasks.Extensions": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Xml.ReaderWriter.dll": {}
         }
       },
       "System.Xml.XmlDocument/4.3.0": {
@@ -385,6 +448,9 @@
           "System.Text.Encoding": "4.3.0",
           "System.Threading": "4.3.0",
           "System.Xml.ReaderWriter": "4.3.0"
+        },
+        "runtime": {
+          "lib/netstandard1.3/System.Xml.XmlDocument.dll": {}
         }
       }
     }
```

</details>

**Comment by fearthecowboy** [comment]
It's repro'able with a lot of different packages-- newtonsoft was just the easiest one that exposed the problem.

And it goes away if you specify `--framework` on the cmdline:

``` bash
C:\tmp\bug> cmd /c rmdir /s /q bin obj ;  dotnet restore ; dotnet run --framework=netcoreapp2.0
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 676.97 ms for C:\tmp\bug\bug.csproj.
Hello World!
```

**Comment by dasMulli** [comment]
Cc @ericstj

**Comment by ericstj** [comment]
At initial glance it looks like conflict resolution /cc @dsplaisted 

Suspect same root cause as https://github.com/dotnet/sdk/issues/1510

The thing that doesn't fit is that specifying framework on the commandline fixes it.  I'm investigating why that is.

**Comment by ericstj** [comment]
It's actually not conflict resolution.  Conflict resolution is failing because the NETCore.App props are not being imported.

When framework is not specified our props are skipped:
```
$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.props
```

I am putting together a generic repro.  I believe this is a bug in the multi-targeting portion of the SDK.

**Comment by ericstj** [comment]
Here's an isolated repro:
```
git clone https://github.com/ericstj/scratch.git
cd scratch\multiFxBug\targetsSample
dotnet pack
cd ..
cd multiFxBug
dotnet build
dotnet build --framework:netcoreapp2.0
```
The first build will only print:
```
Imported targetsSample targets
```

However the second build will print:
```
Imported targetsSample props
Imported targetsSample targets
```

Just removing the redundant TargetFramework property also fixes it, so it isn't like multi-targeting is completely broken WRT to importing the props, just broken when both of these are specified.

**Comment by dasMulli** [comment]
So this is probably a NuGet bug since it emits the generated props file as if the project was multitargeting when it really isn't (because `TargetFramework` is defined in the project without any condition hence `TargetFrameworks` should be ignored).

Without `TargetFrameworks`:

```xml
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.app/2.0.0/build/netcoreapp2.0/Microsoft.NETCore.App.props" Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.app/2.0.0/build/netcoreapp2.0/Microsoft.NETCore.App.props')" />
  </ImportGroup>
```

With `TargetFrameworks` **and `TargetFramework`**:

```xml
  <ImportGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.app/2.0.0/build/netcoreapp2.0/Microsoft.NETCore.App.props" Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.app/2.0.0/build/netcoreapp2.0/Microsoft.NETCore.App.props')" />
  </ImportGroup>
```

This import is then never performed since `TargetFramework` is defined later in the project and no "sub-build" is performed, causing conflict resolution to fail.

**Comment by dasMulli** [comment]
cc @emgarten @rohit21agrawal Do you thing it is reasonable to ignore `TargetFrameworks` for restore when when `TargetFramework` is set? I did a quick search through the NuGet code and changing the condition for `_RestoreCrossTargeting` in `NuGet.targets` helps for a single TFM but not for multiple..

**Comment by emgarten** [comment]
From the NuGet side I think we want to restore a super set of all frameworks that are needed. This would let restore noop when changing the TargetFramework value on build.

**Comment by dasMulli** [comment]
The problem is that NuGet and MSBuild come to a different conclusion about whether or not the project is actually multitargeting, causing the build to behave incorrectly.
Though this configuration is unlikely to happen, it would be a nice-to-have if this was either made an error or changed on the NuGet side..

**Comment by buckstephenh** [comment]
I have a similar problem where if I use <TargetFramework>netcoreapp2.0</TargetFramework> my app will launch in Visual Studio Code but not on the command line.  Likewise if I switch to <TargetFrameworks>netcoreapp2.0</TargetFrameworks> I can run on command line by specifying dotnet run --framework=netcoreapp2.0 but can no longer launch in Visual Studio Code.  In both cases the error is as follows:  

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ObjectModel, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

This is on a Mac, if it helps.

**Comment by aminserajian** [comment]
Guys,

Can you help me out on the following issue in Xamarin studio 6.1.2?

![capture](https://user-images.githubusercontent.com/36369628/42792627-a966f9d2-89b9-11e8-9a78-244598e8a044.JPG)

**Comment by ericstj** [comment]
@aminserajian it looks like your Microsoft.Common.CurrentVersion.targets file has been changed.  It looks to me like someone pasted part of a [WebConfig ](https://msdn.microsoft.com/en-us/library/s10awwz0(v=vs.100).aspx) into it.  This type of issue should be filed in http://github.com/microsoft/msbuild.  For reference here is the latest version of that file: https://github.com/Microsoft/msbuild/blob/b3f9eeab651c92bade6e4f64d11b59aa39e149cb/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1169-L1189, I cannot be sure if that is the correct version for you, but I think it should be safe to just to remove the compilation element.
