### ISSUE TITLE
Error not handled for 'dotnet publish -r'

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/cli#7599]
## Steps to reproduce
`mkdir testapp; cd testapp; dotnet new web; dotnet  restore; dotnet build; dotnet publish -r`

## Expected  behavior
Error Message explaining the `-r` options for `dotnet publish -r` that were not supplied.

## Actual behavior
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collecti
n.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TopLevelCommandNameAndOptionToLog.AllowList(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
C:\chris\Git\appinsighttest> dotnet publish -r^C
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by wli3** [comment]
This bug should be fix in parser level, parser should have stopped it before going further

**Comment by wli3** [comment]
#7636
