### ISSUE TITLE
Unable to create a dotnet project in debian x64 - Kali linux 2017.1

### ISSUE THREAD

**Issue by AhmedHussainy** [dotnet/cli#7671]
## Steps to reproduce
dotnet new console  -o example --lang c#

## Expected  behavior
making a console application in the current directory.

## first time it showed me this ...
Getting ready...
Segmentation fault

## second time it showed me this...

```
Getting ready...
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.web.projecttemplates.2.0.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.web.itemtemplates.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.common.projecttemplates.2.0.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.web.spa.projecttemplates.1.0.417.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.test.projecttemplates.2.0.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.common.itemtemplates.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.DotNet.Tools.New.NewCommandShim.FirstRun(IEngineEnvironmentSettings environmentSettings, IInstaller installer)
   at Microsoft.TemplateEngine.Cli.New3Command.ConfigureEnvironment()
   at Microsoft.TemplateEngine.Cli.New3Command.Initialize()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     kali
 OS Version:  2017.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by livarcocc** [comment]
Do other commands work? How did you install the CLI?

@seancpeters @mlorbetske can you take a look?

**Comment by AhmedHussainy** [comment]
all commands of dotnet new give the same result ....
but for dotnet --info  or version
it's working fine. I followed the official [doc from Microsoft in installing it on debian](https://www.microsoft.com/net/core#linuxdebian) ...

**Comment by wli3** [comment]
Looks like this distro is based on Debian 7 and we don't have native installer for it. (We support Debian 8, and 9)

You can try using the tar.gz file

**Comment by wli3** [comment]
Instruction is here
https://www.microsoft.com/net/download/linux

![image](https://user-images.githubusercontent.com/6993335/30613722-fb039692-9d3d-11e7-9435-29c1caa72bb5.png)

**Comment by AhmedHussainy** [comment]
is there a more simplified example for doing this.... like steps .... do 1 then 2 etc...

**Comment by livarcocc** [comment]
I wonder if this is related to this other issue: https://github.com/dotnet/core/issues/973.

Can you try doing `export DOTNET_CLI_TELEMETRY_OPTOUT=1` and seeing if that will fix the problem for you?

**Comment by AhmedHussainy** [comment]
root@Rival:~/Desktop# dotnet new -o ahmed -lang c#
Getting ready...
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.web.projecttemplates.2.0.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.web.itemtemplates.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.common.projecttemplates.2.0.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.web.spa.projecttemplates.1.0.417.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.test.projecttemplates.2.0.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Error: Could not install "/usr/share/dotnet/sdk/2.0.0/Templates/microsoft.dotnet.common.itemtemplates.1.0.0-beta2-20170803-303.nupkg".
Error: Error reading JObject from JsonReader. Path '', line 0, position 0.
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.DotNet.Tools.New.NewCommandShim.FirstRun(IEngineEnvironmentSettings environmentSettings, IInstaller installer)
   at Microsoft.TemplateEngine.Cli.New3Command.ConfigureEnvironment()
   at Microsoft.TemplateEngine.Cli.New3Command.Initialize()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()

**Comment by mlorbetske** [comment]
It looks like it managed to get partially configured by the very first run & is now trying to read that partial configuration and failing. Could you try running `dotnet new --debug:reinit` and then your original command again?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1253
