### ISSUE TITLE
dotnet new mvc fails to restore

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#7736]
## Steps to reproduce
dotnet new mvc
dotnet restore

## Expected  behavior
Restore succeeds.

## Actual behavior
```
E:\delete\test>dotnet restore
  Restoring packages for E:\delete\test\test.csproj...
  Restoring packages for E:\delete\test\test.csproj...
E:\delete\test\test.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.All with version (>= 2.1.0-preview1-26751)
E:\delete\test\test.csproj : error NU1102:   - Found 4 version(s) in nuget.org [ Nearest version: 2.0.0 ]
E:\delete\test\test.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
E:\delete\test\test.csproj : error NU1102:   - Found 0 version(s) in Package source
E:\delete\test\test.csproj : error NU1102: Unable to find package Microsoft.VisualStudio.Web.CodeGeneration.Tools with version (>= 2.1.0-preview1-26751)
E:\delete\test\test.csproj : error NU1102:   - Found 15 version(s) in nuget.org [ Nearest version: 2.0.0 ]
E:\delete\test\test.csproj : error NU1102:   - Found 4 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.1.0-preview4-final ]
E:\delete\test\test.csproj : error NU1102:   - Found 0 version(s) in Package source
C:\Program Files\dotnet\sdk\2.1.0-preview1-007228\NuGet.targets(102,5): error : Value cannot be null. [E:\delete\test\test.csproj]
C:\Program Files\dotnet\sdk\2.1.0-preview1-007228\NuGet.targets(102,5): error : Parameter name: path [E:\delete\test\test.csproj]
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.0-preview1-007228)

Product Information:
 Version:            2.1.0-preview1-007228
 Commit SHA-1 hash:  28a1f7e9d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-007228\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25719-04
  Build    : b5c917c0b24171ae27c7cfcfd2617b1088d41c11
```

**Comment by cdmihai** [comment]
`dotnet msbuild /t:restore /bl`
[msbuild.zip](https://github.com/dotnet/cli/files/1345960/msbuild.zip)

The exception
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at NuGet.Commands.RestoreCommand.GetAssetsFilePath(LockFile lockFile)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.RestoreRunner.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Build.Tasks.RestoreTask.<ExecuteAsync>d__31.MoveNext()
```

**Comment by livarcocc** [comment]
@emgarten @zhili1208 is this the empty NuGet.Config bug again? I will move it to nuget/home.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5973
