### ISSUE TITLE
ItRestoresLibToSpecificDirectory failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/cli#7907]
https://ci.dot.net/job/dotnet_cli/job/master/job/debug_centos7.1_x64_prtest/1626/testReport/junit/(root)/(empty)/Microsoft_DotNet_Restore_Tests_GivenThatIWantToRestoreApp_ItRestoresLibToSpecificDirectory/

```
  MESSAGE:
                                        Expected command to pass but it did not.
File Name: /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/dotnet
Arguments: restore  --configfile /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/NuGet.Config --packages "pkgs" --disable-parallel
WorkingDir:: /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-restore.Tests/ItRestoresLibToSpecificDirectory/temp
Exit Code: 134
StdOut:
  Restoring packages for /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-restore.Tests/ItRestoresLibToSpecificDirectory/temp/temp.csproj...
  Installing NETStandard.Library 2.0.1.
  Installing Microsoft.NETCore.Platforms 1.1.0.
  Generating MSBuild file /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-restore.Tests/ItRestoresLibToSpecificDirectory/temp/obj/temp.csproj.nuget.g.props.
  Generating MSBuild file /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-restore.Tests/ItRestoresLibToSpecificDirectory/temp/obj/temp.csproj.nuget.g.targets.
  Restore completed in 1.3 sec for /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/bin/3/linux-x64/test/dotnet-restore.Tests/ItRestoresLibToSpecificDirectory/temp/temp.csproj.
StdErr:


                                        +++++++++++++++++++
                                        STACK TRACE:
                                           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() in /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/CommandResultAssertions.cs:line 30
   at Microsoft.DotNet.Restore.Tests.GivenThatIWantToRestoreApp.ItRestoresLibToSpecificDirectory() in /mnt/resource/j/workspace/dotnet_cli/master/debug_centos7.1_x64_prtest/test/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs:line 62
```

**Comment by livarcocc** [comment]
This seems like a intermittent failure. It has not happened again since, as such, I am closing this issue. If we see it again, I can re-activate it.
