### ISSUE TITLE
dotnet new fails (Error reading JObject from JsonReader)

### ISSUE THREAD

**Issue by terracott** [dotnet/cli#7965]
Hi.

After update to version 2.0.2 my dotnet tool installation fails, when I want to use `dotnet new` command

## Steps to reproduce
Execute `dotnet new` command. For example, `dotnet new webapi`

## Expected  behavior
Project was initialized

## Actual behavior
```
$ dotnet new webapi
Error reading JObject from JsonReader. Path '', line 1, position 10351.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureLoaded()
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.RebuildCacheFromSettingsIfNotCurrent(Boolean forceRebuild)
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()

```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1319
