### ISSUE TITLE
dotnet restore with multiple sources crashes

### ISSUE THREAD

**Issue by emgarten** [dotnet/cli#8149]
_From @citizenmatt on August 29, 2017 16:34_

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version (x.x.x.xxx): 3.4.3.855

dotnet.exe --version (if appropriate): 2.0.0

OS version (i.e. win10 v1607 (14393.321)): win10 v1703 (16275.1000)

Worked before? If so, with which NuGet version: dotnet.exe 1.x

## Detailed repro steps so we can see the same problem

1. `dotnet new console`
2. `dotnet restore --source foo --source https://foo`

Results in output:

`C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(466,5): error : The given path's format is not supported. [C:\foo\foo.csproj]`

However, `dotnet restore --source https://foo --source foo` works correctly.

I think the two sources are passed through as a string such as `foo;https://foo`, rather than as two values in a string array. Passing this string to `Path.GetFullPath` causes the same error. Modifying NuGet.targets to pass in an ItemGroup containing the same two values works correctly (well, fails since I'm using silly values).

### Verbose Logs

Snipped from `dotnet restore --source foo --source https://foo -v d`:

```
       Using "GetRestoreSettingsTask" task from assembly "C:\Program Files\dotnet\sdk\2.0.0\NuGet.Build.Tasks.dll".
       Task "GetRestoreSettingsTask"
         (in) ProjectUniqueName 'C:\foo\foo.csproj'
         (in) RestoreSources 'foo;https://foo'
         (in) RestorePackagesPath ''
         (in) RestoreFallbackFolders ''
         (in) RestoreConfigFile ''
         (in) RestoreSolutionDirectory ''
         (in) RestorePackagesPathOverride ''
         (in) RestoreSourcesOverride 'foo;foo'
         (in) RestoreFallbackFoldersOverride ''
   1:6>C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(466,5): error : The given path's format is not supported. [C:\foo\foo.csproj]
         System.NotSupportedException: The given path's format is not supported.
            at System.IO.Path.GetFullPath(String path)
            at NuGet.Common.UriUtility.GetAbsolutePath(String rootDirectory, String path)
            at NuGet.Build.Tasks.GetRestoreSettingsTask.<Execute>b__61_4(String e)
            at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
            at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
            at NuGet.Build.Tasks.GetRestoreSettingsTask.<Execute>b__61_3()
            at NuGet.Build.Tasks.RestoreSettingsUtils.GetValue[T](Func`1[] funcs)
            at NuGet.Build.Tasks.GetRestoreSettingsTask.Execute()
       Done executing task "GetRestoreSettingsTask" -- FAILED.
   1:6>Done building target "_GetRestoreSettings" in project "foo.csproj" -- FAILED.
 
```

_Copied from original issue: NuGet/Home#5817_

**Comment by emgarten** [comment]
_From @rohit21agrawal on August 29, 2017 17:44_

@emgarten looks like we need to be more careful when parsing multiple sources - would you take a look at what could be the resolution here?

**Comment by emgarten** [comment]
_From @weshaggard on October 2, 2017 23:17_

I just added similar repro steps in issue https://github.com/NuGet/Home/issues/4094.

**Comment by emgarten** [comment]
_From @dagood on October 3, 2017 14:22_

Looks to me like it could be caused by how CLI passes these args to MSBuild for NuGet, and the logging in the NuGet task just isn't quite enough to tell what's going on.

https://github.com/dotnet/cli/blob/85ce73dfb5caae60a0d225b0fb02ce9a7c216373/src/dotnet/commands/dotnet-restore/RestoreCommandParser.cs#L48-L50

I realized this could be a problem because defining `<RestoreSources>a;https://b</RestoreSources>` in my own project code works fine. Those RestoreCommandParser lines take `--source a --source https://b` and combine them using `%3B` to pass to `/p:RestoreSources=a&3Bhttps://b`. Recently I experimented with this for other reasons and found that you need to use `$([MSBuild]::Unescape('$(InputArgWithHexCodes)')` to turn a `%3B` passed on the command into a "real" separator. With `%3B` escaped, the string gets treated as a single Item when used as one (like for this task).

The reason I say the logging isn't enough is that in the NuGet diagnostic MSBuild logs, the NuGet logging utils join with `;`. That shows up the same whether or not the string is split when passed in.

---

EDIT: Modifying my `NuGet.targets` to unescape makes `--source a --source https://b` work for me (but who knows what side effects it may cause):

```xml
    ...
    <PropertyGroup>
      <UnescapedRestoreSources>$([MSBuild]::Unescape('$(RestoreSources)'))</UnescapedRestoreSources>
      <UnescapedRestoreSourcesOverride>$([MSBuild]::Unescape('$(RestoreSourcesOverride)'))</UnescapedRestoreSourcesOverride>
    </PropertyGroup>
    
    <!-- For transitive project styles, we rely on evaluating all the settings and including them in the dg spec to faciliate no-op restore-->
    <GetRestoreSettingsTask Condition=" '$(RestoreProjectStyle)' == 'PackageReference' OR '$(RestoreProjectStyle)' == 'ProjectJson' "
     ProjectUniqueName="$(MSBuildProjectFullPath)"
     RestoreSources="$(UnescapedRestoreSources)"
    ...
```

**Comment by emgarten** [comment]
Given @dagood's findings it looks like the issue is with how dotnet.exe escapes restore inputs

**Comment by livarcocc** [comment]
@emgarten you where the one who implemented this part of the parsing using the escaped `%3B` here: https://github.com/TheRealPiotrP/cli/commit/fcdc23233e388c4a9c1f6c857ecd697b09621c69#diff-b78d2d6e01a73fd8b0abe1fc08137072R78.

We just moved it to the new parser, but used the same code as you had. So, I don't know why you had to change from `;` to `%3B`. Can you tell us how to fix this?

**Comment by emgarten** [comment]
I seem to recall that it was to work around an msbuild issue at that time. Does it work to use `;` now instead of special casing it?

**Comment by livarcocc** [comment]
Has the msbuild issue been addressed by now? I don't want to change it just to find out that this fixes come cases and regresses others.

**Comment by livarcocc** [comment]
@emgarten we need your help here. You are asking us to undo your change without knowing why you put it in place to begin with.
