### ISSUE TITLE
dotnet new -i Can give unhelpful error messages

### ISSUE THREAD

**Issue by BenHewins** [dotnet/cli#8174]
## Steps to reproduce
`dotnet new -i "giraffe-template:*"`

## Expected  behavior

> "giraffe-template:*" is not a valid template name
Or some similar message

## Actual behavior
```
Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.TemplateEngine.Cli.Installer.InstallLocalPackages(IReadOnlyList`1 packageNames)
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.TemplateEngine.Cli.New3Command.EnterInstallFlow()
   at Microsoft.TemplateEngine.Cli.New3Command.EnterMaintenanceFlow()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1368
