### ISSUE TITLE
"Permission denied" from `dotnet run` on OS X targeting net461

### ISSUE THREAD

**Issue by kibiz0r** [dotnet/cli#8258]
## Steps to reproduce

- Install Mono: `brew install mono`
- [Install dotnet-sdk-2.1.2-osx-gs-x64.pkg](https://www.microsoft.com/net/learn/get-started/macos)
- Add `export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
` to `~/.zshrc` per [Known issues](https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0#using-net-framework-as-targets-framework-the-osxunix-build-fails)
- `dotnet new console -n HelloWorld`
- `cd HelloWorld`
- Edit `HelloWorld.csproj` to target `net461`
- `dotnet run`

## Expected  behavior

`Hello World!`

## Actual behavior

```
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

Note that it behaves as expected when targeting `netcoreapp2.0`.

**Comment by livarcocc** [comment]
Unfortunately, this is not something that we are going to be able to help you with.

Mono is not officially supported in the CLI yet and I am not sure why you are hitting the issue above. I would maybe post in the mono repo and see if they have any workarounds to make the CLI work with mono. But, if they do, it is really a workaround and this point and not really supported.
