### ISSUE TITLE
Error message when the DotNetSettings.xml manifest is malformed is misleading

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8270]
## Steps to reproduce
Create a dotnet cli global tool with a manifest that doesn't match the expected schema.
Example:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<DotNetTool>
  <Commands>
    <Command Name="dotnet-dev-certs" EntryPoint="dotnet-dev-certs.dll" Runner="dotnet" />
  </Commands>
</DotNetTool>
```
Execute `dotnet install tool` the tool package.

## Expected  behavior
Error message should indicate that the DotNetSettings.xml manifest could not be read because it was expecting a "DotnetCliTool" as the root. element

## Actual behavior
The deserializer throws and error that makes it appear as if the file is invalid XML. (Spent 15 minutes trying to figure out why the CLI thought my xml was invalid, only to realize it was just a naming thing.)

```
System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <DotnetTool xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDotNetCliTool.Read4_DotNetCliTool()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Microsoft.DotNet.ToolPackage.ToolConfigurationDeserializer.Deserialize(String pathToXml)
   at Microsoft.DotNet.ToolPackage.ToolPackageObtainer.GetConfiguration(String packageId, String packageVersion, DirectoryPath individualToolVersion)
   at Microsoft.DotNet.ToolPackage.ToolPackageObtainer.ObtainAndReturnExecutablePath(String packageId, String packageVersion, Nullable`1 nugetconfig, String targetframework)
   at Microsoft.DotNet.Tools.Install.Tool.InstallToolCommand.ObtainPackage(String packageId, String packageVersion, Nullable`1 configFile, String framework, DirectoryPath executablePackagePath)
   at Microsoft.DotNet.Tools.Install.Tool.InstallToolCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Install.InstallCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.2.0-preview1-007796)

Product Information:
 Version:            2.2.0-preview1-007796
 Commit SHA-1 hash:  3ac579997c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17025
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\namc\.dotnet\x64\sdk\2.2.0-preview1-007796\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26008-01
  Build    : 0327161c32d0d6175914521e47d91df3db38ebb4

```

cc @wli3  - this is probably a low priority, but still worth noting that the error wasn't helpful in this case.

**Comment by wli3** [comment]
Do you think we should publish XSD file? The intellisense is pretty good with it. But I don't know if people who work with a lot of JSON will be comfortable with it.

**Comment by natemcmaster** [comment]
XSD might help. Some of this might also be solved by adding on-pack validation of the manifest schema.

I'm not sure how you're deserializing the file on install, so not sure how simple it would be to make the on-install validation a little friendlier. This may not be a high priority, but thought I'd open the issue anyways since other tool authors may hit this when authoring tools for preview1.

**Comment by wli3** [comment]
since there is pack tool available. Move the milestone

**Comment by wli3** [comment]
`dotnet pack` helps avoiding the hand editing of the settings file. Please reopen if you think it is still needed.
