### ISSUE TITLE
dotnet build -c throws exception instead of error message

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/cli#8338]
## Steps to reproduce
` dotnet build -c`

## Expected  behavior

Some friendly error message

## Actual behavior
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TopLevelCommandNameAndOptionToLog.AllowList(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

```

**Comment by peterhuene** [comment]
Hi @kunalspathak, thanks for reporting this issue!

This appears to currently be fixed in master by commit https://github.com/dotnet/cli/commit/9c1fa7c9d90db2a683314406fce8eead16db8d25#diff-b792a66d46e9b54698fc1524afcfd69fR171.

The fix is in master and should be available in the upcoming 2.1.3xx preview release.

Please feel free to reopen this issue if you have any questions.  Thanks!
