### ISSUE TITLE
Error building on Linux

### ISSUE THREAD

**Issue by sebastienros** [dotnet/cli#8344]
On Linux only, when building a specific project on Linux with the latest SDK, I get an exception that originates from msbuild.

When using an older SDK the error goes away.

Current installed SDK: `2.2.0-preview1-007866`
SDK that doesn't repro the error: `2.2.0-preview1-007522`

Project to reproduce the issue: https://github.com/aspnet/benchmarks/tree/dev/src/Benchmarks

Logged error
```
Errors
    /tmp/tmpYHoYVk.tmp/l5visbph.cxt/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB3883: Unexpected exception:  [/tmp/tmpYHoYVk.tmp/nshuithb.5nm/benchmarks/src/Benchmarks/Benchmarks.csproj]
    /tmp/tmpYHoYVk.tmp/l5visbph.cxt/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): System.AggregateException: One or more errors occurred. (The system cannot open the device or file specified) ---> System.IO.IOException: The system cannot open the device or file specified
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.<RunServerCompilationCore>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
---> (Inner Exception #0) System.IO.IOException: The system cannot open the device or file specified
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.<RunServerCompilationCore>d__7.MoveNext()<--- [/tmp/tmpYHoYVk.tmp/nshuithb.5nm/benchmarks/src/Benchmarks/Benchmarks.csproj]

```

I also join the full `msbuild.log`

**Comment by sebastienros** [comment]
Attaching the msbuild log
[msbuild.binlog.zip](https://github.com/dotnet/cli/files/1612450/msbuild.binlog.zip)

**Comment by livarcocc** [comment]
@jaredpar this seems like an error with csc itself. I can't see anything wrong on the SDK side in the binlog.

**Comment by livarcocc** [comment]
I am moving this issue to Roslyn and this may be an issue with the VBCSCompiler, given the BuildServerConnection in the stack above.
