### ISSUE TITLE
dotnet test with --diag option throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by grokys** [dotnet/cli#8438]
## Steps to reproduce

Clone https://github.com/AvaloniaUI/Avalonia and run:

```
dotnet test "./tests/Avalonia.Skia.RenderTests/Avalonia.Skia.RenderTests.csproj" --framework netcoreapp2.0 --configuration -d diag.txt
```

## Expected  behavior

A diagnostic log created, or at least an error explaining what I'm doing wrong.

## Actual behavior

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TopLevelCommandNameAndOptionToLog.AllowList(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
> dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by wli3** [comment]
Thank you for the issue. Fixed by https://github.com/dotnet/cli/pull/7636 

in master: 
$ dotnet test with --diag

```
Required argument missing for option: --diag
Usage: dotnet test [options] <PROJECT> [[--] <RunSettings arguments>...]]

Arguments:
  <PROJECT>   The project to test. Defaults to the current directory.

Options:
  -h, --help                                            Show help information.
  -s, --settings <SETTINGS_FILE>                        Settings to use when running tests.
  -t, --list-tests                                      Lists discovered tests
  --filter <EXPRESSION>                                 Run tests that match the given expression.
                                                        Examples:
                                                        Run tests with priority set to 1: --filter "Priority = 1"
                                                        Run a test with the specified full name: --filter "FullyQualifiedName=Namespace.ClassName.MethodName"
                                                        Run tests that contain the specified name: --filter "FullyQualifiedName~Namespace.Class"
                                                        More info on filtering support: https://aka.ms/vstest-filtering

  -a, --test-adapter-path <PATH_TO_ADAPTER>             Use custom adapters from the given path in the test run.
                                                        Example: --test-adapter-path <PATH_TO_ADAPTER>
  -l, --logger <LoggerUri/FriendlyName>                 Specify a logger for test results.
                                                        Example: --logger "trx[;LogFileName=<Defaults to unique file name>]"
                                                        More info on logger arguments support:https://aka.ms/vstest-report
  -c, --configuration <CONFIGURATION>                   Configuration to use for building the project.  Default for most projects is  "Debug".
  -f, --framework <FRAMEWORK>                           Target framework to publish for. The target framework has to be specified in the project file.
  -o, --output <OUTPUT_DIR>                             Directory in which to find the binaries to be run
  -d, --diag <PATH_TO_FILE>                             Enable verbose logs for test platform.
                                                        Logs are written to the provided file.
  --no-build                                            Do not build project before testing.
  -r, --results-directory <PATH_TO_RESULTS_DIRECTORY>   The directory where the test results are going to be placed. The specified directory will be created if it does not exist.
                                                        Example: --results-directory <PATH_TO_RESULTS_DIRECTORY>
  --collect <DATA_COLLECTOR_FRIENDLY_NAME>              Enables data collector for the test run.
                                                        More info here : https://aka.ms/vstest-collect
  --no-restore                                          Does not do an implicit restore when executing the command.
  -v, --verbosity                                       Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].


RunSettings arguments:
  Arguments to pass runsettings configurations through commandline. Arguments may be specified as name-value pair of the form [name]=[value] after "-- ". Note the space after --.
  Use a space to separate multiple[name] =[value].
  More info on RunSettings arguments support: https://aka.ms/vstest-runsettings-arguments
  Example: dotnet test -- MSTest.DeploymentEnabled=false MSTest.MapInconclusiveToFailed=True

```
