### ISSUE TITLE
GivenEnvironmentAndReporterItCanPrintOutInstructionToAddPath failed in CI due to culture issue

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#8586]
https://ci.dot.net/job/dotnet_cli/job/master/job/debug_windows_nt_es_x64_prtest/777/consoleText

Apparently the test is running with en-US locale and the product is running with es-ES locale.

It seems they are supposed by be aligned by this code:
```c#
            string overriddenUILanguage = Environment.GetEnvironmentVariable("DOTNET_CLI_UI_LANGUAGE");
            if (overriddenUILanguage != null)
            {
                CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo(overriddenUILanguage);
            }
```
Is it possible that the environment variable was cleared, which would not result in resetting CultureInfo.DefaultThreadCurrentUICulture ? 

```
    14>RunTest:
         TestAsset Restore 'TestAppSimple'
         [xUnit.net 00:00:01.4547616]     Microsoft.DotNet.ShellShim.Tests.LinuxEnvironmentPathTests.GivenEnvironmentAndReporterItCanPrintOutInstructionToAddPath [FAIL]
         [xUnit.net 00:00:01.4558965]       Expected collection to be equal to {"No se encuentra la ruta de acceso del ejecutable de las herramientas. Compruebe que se ha agregado /myhome/executable/path a su valor PATH.\nSi usa bash, puede hacerlo con la ejecuci�n del comando siguiente:\n\ncat << EOF >> ~/.bash_profile\n# Add .NET Core SDK tools\nexport PATH=\"$PATH:/myhome/executable/path\"\nEOF"}, but {"Cannot find the tools executable path. Please ensure /myhome/executable/path is added to your PATH.\nIf you are using bash. You can do this by running the following command:\n\ncat << EOF >> ~/.bash_profile\n# Add .NET Core SDK tools\nexport PATH=\"$PATH:/myhome/executable/path\"\nEOF"} differs at index 0.
         [xUnit.net 00:00:01.4569435]       Stack Trace:
         [xUnit.net 00:00:01.4579959]         C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs(32,0): at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
         [xUnit.net 00:00:01.4581106]         C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs(197,0): at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
         [xUnit.net 00:00:01.4582070]         C:\projects\fluentassertions-vf06b\Src\Core\Execution\GivenSelector.cs(122,0): at FluentAssertions.Execution.GivenSelector`1.FailWith(String message, Object[] args)
         [xUnit.net 00:00:01.4582977]         C:\projects\fluentassertions-vf06b\Src\Core\Execution\GivenSelectorExtensions.cs(82,0): at FluentAssertions.Execution.GivenSelectorExtensions.AssertCollectionsHaveSameItems[TActual,TExpected](GivenSelector`1 givenSelector, TExpected[] expected, Func`3 findIndex)
         [xUnit.net 00:00:01.4583850]         C:\projects\fluentassertions-vf06b\Src\Core\Collections\CollectionAssertions.cs(204,0): at FluentAssertions.Collections.CollectionAssertions`2.Equal(IEnumerable expected, String because, Object[] becauseArgs)
         [xUnit.net 00:00:01.4584679]         D:\j\workspace\debug_windows---e579a0fd\test\Microsoft.DotNet.ShellShim.Tests\LinuxEnvironmentPathTests.cs(36,0): at Microsoft.DotNet.ShellShim.Tests.LinuxEnvironmentPathTests.GivenEnvironmentAndReporterItCanPrintOutInstructionToAddPath()
         TestAsset Build 'TestAppSimple'
```

**Comment by livarcocc** [comment]
@nguerrera can you take a look?

@danmosemsft we have had these tests running for a while. I don't recall seeing this fail before.

**Comment by livarcocc** [comment]
Also, @wli3 and @peterhuene since from the stack it seems like a Shim test.

**Comment by wli3** [comment]
on it, a missing loc in test

**Comment by nguerrera** [comment]
Not sure how it got through CI. I fixed another one before merging. Possibly due to how changes were merged that we never ran with both the translation and the test until it all settled in master.

**Comment by wli3** [comment]
Sorry, it was not missing loc in test. The tests use `CommonLocalizableStrings.EnvironmentPathOSXManualInstruction` correctly. The test are run in es but the subject production code is in en. I also don't know why "GivenAddPackageExecutablePathToUserPathJustRunItPrintsInstructionToLogout" with similar env set up did not fail

**Comment by wli3** [comment]
Also, there is no inter process happen. The test create a class with some mock object and just call that. It should be a straight forward method call

**Comment by nguerrera** [comment]
This failed once and then never again in CI?

**Comment by wli3** [comment]
I don't know. If it failed again, it should block check in all the time. Or it is a special leg? I always think there is no CI with different loc. How to run this leg? `debug_windows_nt_es_x64_prtest`, is not in the list for PR

**Comment by wli3** [comment]
My understanding is that only happened once. And I cannot get more detail on the repo. Closing. Please reopen when that happen again
