### ISSUE TITLE
dotnet run does not work on osx using netXXX TargetFramework

### ISSUE THREAD

**Issue by patrickjamesbarry** [dotnet/cli#8599]
On Mac--> 10.13.3

## Steps to reproduce
`dotnet new console -o myApp`
change myApp.csproj  to be
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net451</TargetFramework>
  </PropertyGroup>
</Project>
```
`dotnet run`
## Expected  behavior
You see Hello World printed out

## Actual behavior
```
System.ComponentModel.Win32Exception (0x80004005): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

```

**Comment by patrickjamesbarry** [comment]
FYI: I also found I had to set this just so the netXXX frameworks were found:
`export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/`

**Comment by livarcocc** [comment]
This is not supported by the CLI currently. We support full framework on windows and .NET Core cross-platform.

**Comment by patrickjamesbarry** [comment]
Here is some feedback then...  This is really confusing and definitely making a really bad first impression. This was the very first thing I tried after taking a break since the project.json departure.  I have tracked down my issue and will be following up on ticket https://github.com/dotnet/sdk/issues/335.  The interesting thing is is that I can build the project, and even run the exe using mono.  **The `dotnet run` command seems busted.**

If others encounter the same thing, my problem with developing c# console app using .net451 target framework are the following:

- Had to set FrameworkPathOverride so framework libraries are found for `dotnet build` (see above)
- had to use sudo when running dotnet run
- had to run exe using mono command, not dotnet run

Interesting enough.. you can take the same app and run it in Visual Studio Community 2017 for mac and it runs just fine.  So it is just the CLI that doesn't seem to be working.

**Comment by dasMulli** [comment]
If it's any help, you could put a hack into the csproj to make `dotnet run` work:
```xml
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net451</TargetFramework>
  </PropertyGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <RunArguments>$(RunCommand) $(RunArguments)</RunArguments>
    <RunCommand>mono</RunCommand>
  </PropertyGroup>
</Project>
```

**Comment by TheAngryByrd** [comment]
I built a dotnet tool to address this issue. https://github.com/TheAngryByrd/dotnet-mono

I've tried to align it with the same flags so you should just be able to `dotnet mono -f net451 -- --MyProgramFlags`
