### ISSUE TITLE
Error running dnu restore on linux from a Makefile

### ISSUE THREAD

**Issue by ac-esousa** [dotnet/cli#869]
Hello,

When a running `dnu restore` from a Makefile (this is my Makefile [Makefile.zip](https://github.com/dotnet/cli/files/92434/Makefile.zip)) on a linux machine, I got the following error:

    Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231

      CACHE https://api.nuget.org/v3/index.json
    Restoring packages for /home/dudu/acpm/src/BackEnd/Data.Contracts/project.json

    Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at NuGet.VersionUtility.GetNearestCore[T](FrameworkName projectFramework, IEnumerable`1 items, Func`2 fxExtractor, IEnumerable`1& compatibleItems)
       at NuGet.VersionUtility.GetNearest[T](FrameworkName projectFramework, IEnumerable`1 items, IEnumerable`1& compatibleItems)
       at Microsoft.Dnx.Runtime.NuGetDependencyResolver.<GetDependencies>d__4.MoveNext()
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<>c__DisplayClass3_0.<ChainPredicate>b__0(String name)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreOperations.CreateGraphNode(RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreCommand.CreateGraphNode(RestoreOperations restoreOperations, RestoreContext context, LibraryRange libraryRange, Func`2 predicate)
       at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreCommand.RestoreForProject(String projectJsonPath, String rootDirectory, String packagesDirectory, IList`1 remoteProviders, SummaryContext summary)
       at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<Execute>b__2(String projectJsonPath)
       at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreCommand.Execute(String restoreDirectory, PackageFeedCache packageFeeds, SummaryContext summary)
       at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__67.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreCommand.Execute()
       at Microsoft.Dnx.Tooling.RestoreConsoleCommand.<>c__DisplayClass0_0.<<Register>b__1>d.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.Dnx.Tooling.RestoreConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
       at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.<>c__DisplayClass68_0.<OnExecute>b__0()
       at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
       at Microsoft.Dnx.Tooling.Program.Main(String[] args)
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
       at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
       at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
       at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
       at DomainManager.Execute(Int32 argc, Char** argv, NativeBootstrapperContext* context)
    make: *** [src/BackEnd/Services/project.lock.json] Aborted (core dumped)
    make: Leaving directory `/home/dudu/acpm'

If I run `dnu restore` without using make, everything goes ok.

Also, I am able to use this Makefile on a Mac OSX machine.

**Comment by piotrpMSFT** [comment]
@gkhanna79 the AV makes me think that this might be a Linux-specific CoreCLR issue. Can you help us get to the bottom of it?

**Comment by gkhanna79** [comment]
@janvorli Can you please help take a look?

**Comment by skeeping** [comment]
Any ideas on how to get pass this issue?

**Comment by janvorli** [comment]
@skeeping I am sorry for not responding earlier, I've missed the fact that I was asked to help back in January. Can you still repro the issue? And since dnx is now obsolete (see https://github.com/aspnet/dnx/blob/dev/README.md), can you repro it with dotnet cli that replaced the dnx?
There used to be a problem with running the .NET stuff with stack size limit set to unlimited which is what the make does (see https://github.com/dotnet/coreclr/issues/2467). It was fixed in January (https://github.com/dotnet/coreclr/pull/2573), so it is possible that your version of DNX didn't have that fix in yet.

**Comment by ac-esousa** [comment]
I have just upgrade my project to RC2, and test it again. With new `dotnet` command line, everything work fine.
