### ISSUE TITLE
`dotnet test` fails when the file path has an ampersand in it

### ISSUE THREAD

**Issue by cynic** [dotnet/cli#9091]
## Steps to reproduce

1. Move existing solution, which contains a test project, to a directory that has an ampersand in it, e.g. `C:\Projects\Tom&Jerry\`.
2. Run `dotnet test` with the relevant `.csproj` file.

## Expected  behavior

Tests should be executed.

## Actual behavior

An `XmlException` is thrown; a stack trace is printed out; and the tool exits badly.

## Environment data

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by omajid** [comment]
Here is the stack trace:

    Unhandled Exception: System.Xml.XmlException: An error occurred while parsing EntityName. Line 1, position 25.
       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
       at System.Xml.XmlTextReaderImpl.ParseEntityName()
       at System.Xml.XmlTextReaderImpl.ParseEntityReference()
       at System.Xml.XmlTextReaderImpl.Read()
       at System.Xml.XmlLoader.ParsePartialContent(XmlNode parentNode, String innerxmltext, XmlNodeType nt)
       at System.Xml.XmlLoader.LoadInnerXmlElement(XmlElement node, String innerxmltext)
       at System.Xml.XmlElement.set_InnerXml(String value)
       at Microsoft.VisualStudio.TestPlatform.Utilities.XmlUtilities.AppendOrModifyChild(XmlDocument xmlDocument, String nodeXPath, String nodeName, String innerXml)
       at Microsoft.VisualStudio.TestPlatform.Utilities.InferRunSettingsHelper.UpdateRunConfiguration(XmlDocument xmlDocument, Architecture effectivePlatform, Framework effectiveFramework, String resultsDirectory)
       at Microsoft.VisualStudio.TestPlatform.Utilities.InferRunSettingsHelper.UpdateRunSettingsWithUserProvidedSwitches(XmlDocument runSettingsDocument, Architecture architecture, Framework framework, String resultsDirectory)
       at Microsoft.VisualStudio.TestPlatform.Common.Utilities.RunSettingsProviderExtensions.AddDefaultRunSettings(String runSettings)
       at Microsoft.VisualStudio.TestPlatform.Common.Utilities.RunSettingsProviderExtensions.AddDefaultRunSettings(IRunSettingsProvider runSettingsProvider)
       at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(String[] args, List`1& processors)
       at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
       at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args)

It's probably this line:
 https://github.com/Microsoft/vstest/blob/1dc3cadbe99ef5c3de27cd17ba298c06afc9a0f7/src/Microsoft.TestPlatform.Utilities/InferRunSettingsHelper.cs#L456

That in turn calls https://github.com/Microsoft/vstest/blob/1dc3cadbe99ef5c3de27cd17ba298c06afc9a0f7/src/Microsoft.TestPlatform.Utilities/XmlUtilities.cs#L61-L67

The TODO comment pretty much explains the bug.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1554
