### ISSUE TITLE
Build-server shutdown doesn't get credentials to delete Razor PID file

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#9158]
## Steps to reproduce
Install latest RC CLI build
In powershell or cmd prompt, run the following:
dotnet new razor
dotnet build
dotnet build-server shutdown

## Expected  behavior
The Razor build server is shutdown and the PID file is deleted

## Actual behavior
Exception is thrown:

PS C:\Users\v-masche\servertests\test3> dotnet build-server shutdown
Shutting down MSBuild server...
Shutting down VB/C# compiler server...
System.IO.IOException: The process cannot access the file 'C:\Users\v-masche\.dotnet\pids\build\rzc-8784' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.OpenRead(String path)
   at Microsoft.DotNet.BuildServer.RazorPidFile.Read(FilePath path, IFileSystem fileSystem)
   at Microsoft.DotNet.BuildServer.BuildServerProvider.EnumerateBuildServers(ServerEnumerationFlags flags)+MoveNext()
   at Microsoft.DotNet.Tools.BuildServer.Shutdown.BuildServerShutdownCommand.StartShutdown()
   at Microsoft.DotNet.Tools.BuildServer.Shutdown.BuildServerShutdownCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.BuildServer.BuildServerCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:
PS C:\Users\v-masche> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008669
 Commit:    4db4d9b568

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008669\

Host (useful for support):
  Version: 2.1.0-rc1-26425-06
  Commit:  b50a96ee38

.NET Core SDKs installed:
  2.1.300-rc1-008669 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-30676 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-30676 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1-26425-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by mattscheffer** [comment]
@peterhuene

**Comment by peterhuene** [comment]
@livarcocc 2.1.3xx RTM?

**Comment by peterhuene** [comment]
There are two bugs here: 

1) `dotnet` should be opening the file `FileShare.Write | FileShare.Delete` because that's how Razor created the file.  This works on other platforms because the file sharing mechanism is Windows only currently.

2) A failure to access or read the pid file should be handled gracefully and the file should be ignored so that the operation can continue.

**Comment by peterhuene** [comment]
A workaround for RC: `dotnet build-server shutdown --msbuild --vbcscompiler` to skip shutting down Razor servers.  @mattscheffer do you mind testing that workaround?

**Comment by mattscheffer** [comment]
Gotcha. Just wanted to make sure we were on the same page there. The --msbuild and --vbsccompiler arguments definitely work for their respective servers.

**Comment by peterhuene** [comment]
FYI, I have a fix ready, just working on an integration test so that this doesn't break like this again.

**Comment by peterhuene** [comment]
Fixed with #9160.
