### ISSUE TITLE
"dotnet build-server shutdown" throws IOException

### ISSUE THREAD

**Issue by martincostello** [dotnet/cli#9239]
For a .NET Core 2.1 RC1 build running in TeamCity (`2.1.300-rc1-008673`) I'm using the `dotnet build-server shutdown` command to ensure that the local install of .NET Core SDK isn't left running on the build server so that errors aren't caused in subsequent builds by still-running processes preventing the checkout directory from being cleaned.

When the command is run at the end of the build, an `IOException` is thrown, causing the overall TeamCity build to fail due to content being written to stderr:

```ps
[15:53:05]	[Step 2/3] Shutting down MSBuild server...
[15:53:05]	[Step 2/3] Shutting down VB/C# compiler server...
[15:53:05]	[Step 2/3] System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\.dotnet\pids\build\rzc-3568' because it is being used by another process.
[15:53:06]	[Step 2/3] Error message is logged
[15:53:05]	[Step 2/3] at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
[15:53:05]	[Step 2/3] at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
[15:53:05]	[Step 2/3] at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[15:53:05]	[Step 2/3] at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
[15:53:05]	[Step 2/3] at System.IO.File.OpenRead(String path)
[15:53:05]	[Step 2/3] at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.OpenRead(String path)
[15:53:05]	[Step 2/3] at Microsoft.DotNet.BuildServer.RazorPidFile.Read(FilePath path, IFileSystem fileSystem)
[15:53:05]	[Step 2/3] at Microsoft.DotNet.BuildServer.BuildServerProvider.EnumerateBuildServers(ServerEnumerationFlags flags)+MoveNext()
[15:53:05]	[Step 2/3] at Microsoft.DotNet.Tools.BuildServer.Shutdown.BuildServerShutdownCommand.StartShutdown()
[15:53:05]	[Step 2/3] at Microsoft.DotNet.Tools.BuildServer.Shutdown.BuildServerShutdownCommand.Execute()
[15:53:05]	[Step 2/3] at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
[15:53:05]	[Step 2/3] at Microsoft.DotNet.Tools.BuildServer.BuildServerCommand.Run(String[] args)
[15:53:05]	[Step 2/3] at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
[15:53:05]	[Step 2/3] at Microsoft.DotNet.Cli.Program.Main(String[] args)
[15:53:05]	[Step 2/3] Process exited with code 0
```

The `build-server` command should handle transient IO errors on disk when terminating processes.

**Comment by livarcocc** [comment]
cc @peterhuene 

Thanks for reporting this issue. I believe it has already been fixed for RTM. Peter, confirm and close this issue please.

**Comment by peterhuene** [comment]
Hi @martincostello.

This has been fixed for RTM.  The problem manifests itself when you have a running Razor server on Windows.  Unfortunately the command is broken for shutting down Razor servers, but it can still be used to shutdown MSBuild and VB/C# compiler servers by passing `--msbuild --vbcscompiler` options (effectively telling it to skip Razor shutdown).

Thanks!

**Comment by martincostello** [comment]
@peterhuene Thanks. I’ll use those flags as a workaround until RTM or another RC drops.
