### ISSUE TITLE
netcoreapp2.0 test project can't load referenced System.Memory when running on 2.1-rc1

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#9240]
## Steps to reproduce

Running `dotnet test` on this test project using 2.1-rc1

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.0-rc1"/>
  </ItemGroup>
</Project>
```

## Expected  behavior

Test project to run.

## Actual behavior

Outputs:
```
Starting test execution, please wait...
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Net.IPAddress.Parse(String ipString)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.GetIPEndPoint(String value)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient.Start(String endPoint)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.InitializeCommunication()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
```

When the TargetFramework and the .NET Core version are in sync, the test project works.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
@dsplaisted can you take an initial look here?

**Comment by dsplaisted** [comment]
This is a roll-forward issue which should be fixed by https://github.com/dotnet/core-setup/pull/4135

See also https://github.com/dotnet/core-setup/issues/4082

**Comment by dsplaisted** [comment]
This should now be fixed

**Comment by tmds** [comment]
Thanks @dsplaisted , I'll give it a try using a daily.
