### ISSUE TITLE
Mac OS X - DllNotFoundException for libcurl

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#956]
### Mac OS X - DllNotFoundException for libcurl
A DllNotFoundException is thrown when running `dnu restore`.  

### Functional impact
`dnu restore` fails.

### Minimal repro steps
Run `dnu restore` with `CoreClr-x64-1.0.0-rc1-16202`.  

### Expected result
`dnu restore` should succeed.

### Actual result
When running `dnu restore`, the following exception is thrown:
>System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libcurl': The specified module could not be found.
> (Exception from HRESULT: 0x8007007E)
>   at Interop.libcurl.curl_version_info(Int32 curlVersionStamp)
>   at System.Net.Http.CurlHandler..cctor()
>   --- End of inner exception stack trace ---
>   at System.Net.Http.CurlHandler..ctor()
>   at System.Net.Http.HttpClient..ctor()
>   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource..ctor(String baseUri, String userName, String password, Reports reports)
>   at Microsoft.Dnx.Tooling.PackageFeedCache.CreatePackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
>   at Microsoft.Dnx.Tooling.PackageFeedCache.<>c__DisplayClass1_0.<GetPackageFeed>b__0(PackageSource _)
>   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>   at Microsoft.Dnx.Tooling.PackageFeedCache.GetPackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
>   at Microsoft.Dnx.Tooling.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 effectiveSources, PackageFeedCache packageFeeds, SummaryContext summary)
>   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()

### Further technical details
`curl --version` returns:
>curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
>Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
>Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

**Comment by cdmihai** [comment]
+1
```
./build.sh 
*** Building dotnet tools version 1.0.0.001099 - Debug ***
*** Checking Pre-Reqs ***
*** Adjusting file descriptors limit, if necessary ***
info : Increasing file description limit to 1024
*** Restoring Tools and Packages ***
*** Installing dotnet stage 0 ***
dotnet_install: Preparing to install .NET Tools to /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64
dotnet_install: Latest Version: 1.0.0.001098
dotnet_install: Local Version: <none>
dotnet_install: Downloading dotnet-osx-x64.latest.tar.gz from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest
######################################################################## 100.0%
dotnet_install: Extracting tarball
dotnet_install: Moving new CLI into install location and symlinking
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-build -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-build
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-compile -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-compile
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-compile-csc -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-compile-csc
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-compile-fsc -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-compile-fsc
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-compile-native -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-compile-native
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-new -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-new
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-pack -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-pack
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-projectmodel-server -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-projectmodel-server
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-publish -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-publish
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-repl -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-repl
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-repl-csi -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-repl-csi
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-resgen -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-resgen
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-restore -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-restore
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-run -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-run
dotnet_install: Linking /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/bin/dotnet-test -> /Users/micodoba/projects/cli/.dotnet_stage0/osx.10.11-x64/share/dotnet/cli/dotnet-test
dotnet_install: Cleaning dotnet-osx-x64.latest.tar.gz
*** Restoring packages ***
error: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
```

**Comment by tarurar** [comment]
Guys, is there any workaround for this issue?

**Comment by piotrpMSFT** [comment]
LibSSL is required for this scenario to work. Take a look at https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/known-issues.md.
