### ISSUE TITLE
dotnet-sdk-2.1 package for OpenSUSE is broken

### ISSUE THREAD

**Issue by pavelbraginskiy** [dotnet/cli#9735]
I don't know if this is the correct repo for this issue, but I can't think of a better place.

## Steps to reproduce
Attempt to install .NET Core on OpenSUSE Tumbleweed following the instructions at https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial

## Expected  behavior
```
$ sudo zypper install dotnet-sdk-2.1
[sudo] password for root: 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 6 NEW packages are going to be installed:
  aspnetcore-runtime-2.1 dotnet-host dotnet-hostfxr-2.1 dotnet-runtime-2.1 dotnet-runtime-deps-2.1 dotnet-sdk-2.1

6 new packages to install.
Overall download size: 163.1 MiB. Already cached: 0 B. After the operation, additional 163.1 MiB will be used.
Continue? [y/n/...? shows all options] (y):
```

## Actual behavior
```
$ sudo zypper install dotnet-sdk-2.1
[sudo] password for root: 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libicu52_1 needed by dotnet-runtime-deps-2.1-2.1.2-1.x86_64
 Solution 1: do not install dotnet-sdk-2.1-2.1.302-1.x86_64
 Solution 2: break dotnet-runtime-deps-2.1-2.1.2-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): 2
Resolving dependencies...
Resolving package dependencies...

The following 6 NEW packages are going to be installed:
  aspnetcore-runtime-2.1 dotnet-host dotnet-hostfxr-2.1 dotnet-runtime-2.1 dotnet-runtime-deps-2.1 dotnet-sdk-2.1

6 new packages to install.
Overall download size: 163.1 MiB. Already cached: 0 B. After the operation, additional 163.1 MiB will be used.
Continue? [y/n/...? shows all options] (y):
```

## Environment data
`dotnet --info` output:
```
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
[1]    3049 abort (core dumped)  TERM=xterm dotnet --info
```
`dotnet --info` output after setting System.Globalization.Invariant:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     opensuse-tumbleweed
 OS Version:  20180723
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by nguerrera** [comment]
@janvorli Is this an issue in coreclr locating libicu. I'm totally guessing here, but I saw in https://github.com/dotnet/coreclr/pull/15562/files that there is some special code to handle the binding.

**Comment by janvorli** [comment]
@nguerrera this is a problem of the package. Coreclr can run with any libicu version higher or equal to 50, but the package that @pavelbraginskiy is trying to install refers to a version different from the one supported on the tumbleweed. It seems that our instructions describe single feed for opensuse 42.2, which cannot work for tubleweed. It is always possible to install the .tar.gz version that should work with any icu version installed.

**Comment by nguerrera** [comment]
cc @leecow

Should we recommend the .tar.gz for tumbleweed in the instructions or provide an additional feed there that can satisfy the libicu dependency?

**Comment by nguerrera** [comment]
Reading again it seems we're manifesting that we need icu 52 when 50 or greater would work. Should we be changing the package to allow a lower version?

**Comment by wli3** [comment]
This issue was moved to dotnet/core-setup#4413
