### ISSUE TITLE
Build Failure Since Upgrade to 2.1.400

### ISSUE THREAD

**Issue by jamiebrynes7** [dotnet/cli#9839]
## Steps to reproduce
1. Install dotnet 2.1.400
2. Clone https://github.com/spatialos/UnityGDK
3. Ensure that `global.json` has the version set to `2.1.400`
3. Run `./ci/codegen.sh` or run the following command directly from the root of the project:
```
dotnet run -p code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj -- --schema-compiler-path=tools/schema_compiler/win/schema_compiler.exe --schema-path=schema --schema-path=build/dependencies/schema/standard_library --json-dir=workers/unity/Temp/ImprobableJson --native-output-dir=workers/unity/Assets/Generated/Source --network-types-output-dir=workers/unity/Assets/Improbable.Generated.NetworkTypes/Generated
```

## Expected  behavior
The build succeeds and the project is ran.

## Actual behavior
The build fails with the following message:
```
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018: The "TransformAllTask" task failed unexpectedly.
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018: File name: 'System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018:    at Mono.TextTemplating.TemplateGenerator..ctor()
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018:    at Improbable.TextTemplating.TransformAllTask.Execute()
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018:
C:\Workspace\Develop\UnityGDK\code_generator\GdkCodeGenerator\GdkCodeGenerator.csproj(51,5): error MSB4018:

The build failed. Please fix the build errors and run again.
```

Where `TransformAllTask` is a pre-build step to generate `cs` files from `tt` which are then used at execution time. `TransformAllTask` is in `Improbable.TextTemplating.dll` that is pinned, along with its dependencies in the `GdkCodeGenerator` project. (Rebuilding the dlls and replacing doesn't affect the result).

This build succeeds when ran with dotnet 2.1.30x

## Environment data
`dotnet --info` output:

```
λ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by nguerrera** [comment]
This issue was moved to Microsoft/msbuild#3627
