### ISSUE TITLE
dotnet run System.ArgumentNullException: for a simple program with new installation of .netcore 2.1.401

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#9932]
@noorrocks commented on [Wed Aug 29 2018](https://github.com/dotnet/core/issues/1904)

# Issue Title

dotnet run System.ArgumentNullException: for a simple program with new installation of .netcore 2.1.401

# General

Trying to get started with .netcore programming. Followed the basic tut from asp.net website but failed.

https://www.asp.net/get-started

I get the error (attached) after dotnet run command. 

[Powershell output](https://codeshare.io/5w3X9p)

This is my first ever program after a fresh installation of the latest SDK (as of now). I have tried console app and it works fine. Even a simple app with 'web' template works ok and display 'Hello World' in the browser. However, as soon as I add 'services.addMVC' to the app it breaks with the same error. I have done all my research and tried a lot of things, but not sure what is happening.

Program files:
[Files](https://app.box.com/s/kzsy7t5tzmg93ykqkhvxbyci1l5zgre7)

---

@noorrocks commented on [Thu Aug 30 2018](https://github.com/dotnet/core/issues/1904#issuecomment-417336820)

After wrestling with this problem for two days, finally, I have caught the issue.

if you see the 'powershell output', my project directory is ' Directory: C:\#NIN\dotnetcore'

Somehow, it doesn't like the '#' in a folder name. I created a new folder without '#' and it worked like a charm.

I was also able to reproduce this problem on a different PC.

Please note that it only bothers the '#' if it's at the root folder name. Down the chain, it works OK.

This issue can be marked as a **known issue**, I think.

**Comment by livarcocc** [comment]
@peterhuene can you take a look?

**Comment by peterhuene** [comment]
The exception is coming from ASP.NET MVC:

```
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError, Func`2 fileExists, Func`2 loadFile)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetRelatedAssemblies(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetAssemblyItem(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveFromDependencyContext(DependencyContext dependencyContext)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveAssemblies(Assembly entryAssembly)+MoveNext()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at try1.Startup.ConfigureServices(IServiceCollection services) in C:\#NIN\dotnetcore\tryx\try1\Startup.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at try1.Program.Main(String[] args) in C:\#NIN\dotnetcore\tryx\try1\Program.cs:line 17
```

Having ` C:\#NIN\` as the root of this path appears to be tripping up the MVC `RelatedAssemblyAttribute`.

I suspect [this line](https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs#L118) might be treating `#` as an anchor, resulting in a root directory returned, which then gets converted to `null` by `Path.GetDirectoryName` and passed to `Path.Combine`, resulting in the exception.  Just a guess, though.

I'll move this to ASP.NET MVC.

**Comment by peterhuene** [comment]
This issue was moved to aspnet/Mvc#8367
