### ISSUE TITLE
dotnet-restore error

### ISSUE THREAD

**Issue by oneaspnet** [dotnet/cli#994]
```
D:\Projects\Node\dotnet>dotnet restore
info : Running restore with 16 concurrent jobs.
info : Restoring packages for D:\Projects\Node\dotnet\project.json...
warn : The ZIP archive C:\Users\C\AppData\Local\NuGet\v3-cache\43f718f34a186fe5c
f97f6ca327363f6c129bb66$otnet-core_api_v3_flatcontainer_\nupkg_runtime.win7-x64.
Microsoft.NETCore.Runtime.CoreCLR.1.0.1-rc2-23704.dat is corrupt

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.IO.InvalidDataException: End of Central Directory record could not be f
ound.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode,
Boolean leaveOpen)
   at NuGet.Packaging.PackageArchiveReader..ctor(Stream stream, Boolean leaveStr
eamOpen)
   at NuGet.Protocol.Core.v3.RemoteRepositories.PackageUtilities.<OpenNuspecFrom
NupkgAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.Protocol.Core.v3.RemoteRepositories.HttpFileSystemBasedFindPackageBy
IdResource.<GetDependencyInfoAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<GetDependenci
esAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryEntry>d__8.Mov
eNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.Commands.RestoreCommand.<WalkDependenciesAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.Commands.RestoreCommand.<TryRestore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.CommandLine.XPlat.Program.<ExecuteRestore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass1_0.<<Main>b__1>d.MoveNex
t()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(St
ring[] args)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)

```

**Comment by piotrpMSFT** [comment]
@ericstj have you seen something like this before? 
`runtime.win7-x64.
Microsoft.NETCore.Runtime.CoreCLR.1.0.1-rc2-23704.dat is corrupt`

**Comment by emgarten** [comment]
This looks like a network issue caused an incomplete download.

@oneaspnet try clearing the %localappdata%/NuGet/v3-cache and restoring again.

**Comment by oneaspnet** [comment]
@emgarten  Thanks. 
Yesterday, I tried to clean the cache, but still error.
Today, after a successful retry.
